import type { DevotionalEntry } from "./types";

// Enero — Comienzos y tu versículo del año (#199).
export const enero: readonly DevotionalEntry[] = [
  {
    day: 1,
    openingPrayer: "Señor, gracias por permitirme ver el comienzo de este año. Lo pongo en tus manos desde la primera hora.",
    intro: "Isaías habla a un pueblo que miraba con nostalgia las liberaciones del pasado. Dios los invita a levantar la vista, porque está preparando algo nuevo aun en lugares que parecen desierto.",
    verseRef: "Isaías 43:18-19",
    reflection: "Un año nuevo no borra la historia, pero tampoco tiene que quedar atrapado en ella. Dios sigue obrando y abre caminos donde vos solo ves sequedad. Hoy podés soltar lo que ya pasó y prestar atención a lo que él está haciendo.",
    closingPrayer: "Padre, ayudame a no vivir de recuerdos ni de lamentos. Abrí mis ojos para reconocer lo nuevo que estás haciendo este año. En el nombre de Jesús. Amén.",
  },
  {
    day: 2,
    openingPrayer: "Dios de gracia, gracias porque en Cristo hay vida nueva. Que hoy la viva con gratitud.",
    intro: "Pablo explica a los corintios lo que sucede cuando alguien está unido a Cristo. No se trata de una mejora superficial, sino de una nueva creación en la que lo viejo queda atrás.",
    verseRef: "2 Corintios 5:17",
    reflection: "Los propósitos de año nuevo dependen de tu fuerza de voluntad; la nueva creación depende de Cristo. Él no te pide que te reinventés solo, sino que vivás desde lo que ya hizo en vos. Ese es un comienzo que no se agota en febrero.",
    closingPrayer: "Señor Jesús, gracias por hacerme nuevo. Cuando vuelva a lo viejo, recordame quién soy en vos y levantame otra vez. Amén.",
  },
  {
    day: 3,
    openingPrayer: "Señor, no conozco lo que trae este año, pero confío en que vos sí lo conocés.",
    intro: "Jeremías escribe a los judíos deportados en Babilonia. Les dice que se establezcan allí por largo tiempo y, en medio del exilio, les recuerda que Dios tiene pensamientos de paz para su pueblo.",
    verseRef: "Jeremías 29:11",
    reflection: "Esta promesa no fue dicha a gente cómoda, sino a personas que esperarían setenta años. No garantiza que todo salga como queremos, sino que Dios no abandona a los suyos y tiene un futuro con esperanza. Podés recibirla aun si este año comienza en terreno difícil.",
    closingPrayer: "Padre, gracias porque tus planes para tu pueblo son de paz. Dame paciencia en la espera y fe para confiar cuando no entienda. Amén.",
  },
  {
    day: 4,
    openingPrayer: "Dios sabio, hoy quiero apoyarme en vos antes que en mis propias ideas.",
    intro: "En Proverbios, un padre aconseja a su hijo sobre cómo caminar por la vida. Le enseña a confiar en el Señor de todo corazón y a reconocerlo en cada uno de sus caminos.",
    verseRef: "Proverbios 3:5-6",
    reflection: "Tu entendimiento es un regalo, pero no fue hecho para cargar solo con todo el peso del futuro. Confiar en Dios no es dejar de pensar, sino pensar en su presencia. Reconocelo hoy en una decisión pequeña y verás que también guía las grandes.",
    closingPrayer: "Señor, te entrego mis planes para este año. Enderezá mis veredas y librame de confiar solo en mi propia prudencia. Amén.",
  },
  {
    day: 5,
    openingPrayer: "Señor, gracias porque no camino solo. Dame valor para lo que hoy tengo enfrente.",
    intro: "Moisés había muerto y Josué debía guiar al pueblo hacia la tierra prometida. Ante una tarea tan grande, Dios le manda ser fuerte y valiente, porque estaría con él dondequiera que fuera.",
    verseRef: "Josué 1:9",
    reflection: "El valor de Josué no venía de su experiencia, sino de la compañía de Dios. Quizá este año empieza con retos que te quedan grandes. No se te pide que no sintás miedo, sino que no te dejés gobernar por él, porque Dios va con vos.",
    closingPrayer: "Padre, cuando me falte valor, recordame que estás conmigo. Fortalecé mis manos para hacer lo que me toca hoy. En el nombre de Jesús. Amén.",
  },
  {
    day: 6,
    openingPrayer: "Señor Jesús, quiero seguir avanzando hacia vos. Afirmá mis pasos este día.",
    intro: "Pablo escribe a los filipenses desde la prisión. Reconoce que aún no ha llegado a la meta, pero describe su vida como una carrera en la que olvida lo que queda atrás y se extiende hacia adelante.",
    verseRef: "Filipenses 3:13-14",
    reflection: "Olvidar lo de atrás no es negar el pasado, sino no dejar que te defina. Ni tus logros ni tus fracasos son la meta. El premio es Cristo mismo, y hacia él podés seguir corriendo aunque sea a paso lento.",
    closingPrayer: "Señor, librame de quedarme mirando atrás. Dame constancia para avanzar hacia vos un día a la vez. Amén.",
  },
  {
    day: 7,
    openingPrayer: "Dios fiel, te entrego este día y todo lo que me preocupa de él.",
    intro: "David escribe este salmo a quienes se inquietan al ver que a los malos parece irles bien. En lugar de enojarse, los anima a encomendar su camino al Señor y a confiar en él.",
    verseRef: "Salmos 37:5",
    reflection: "Encomendar es soltar algo en manos de otro para que lo cuide. No significa quedarse de brazos cruzados, sino trabajar sin la ansiedad de controlar el resultado. Hoy podés nombrar delante de Dios la carga que más te pesa y dejarla con él.",
    closingPrayer: "Señor, encomiendo en tus manos mi camino de este año. Quitame la inquietud y enseñame a confiar mientras hago mi parte. Amén.",
  },
  {
    day: 8,
    openingPrayer: "Señor, antes de empezar mis tareas quiero ponerlas delante de vos.",
    intro: "Salomón observa que el ser humano hace muchos planes, pero que la vida no depende solo de ellos. Por eso aconseja encomendar nuestras obras al Señor para que nuestros pensamientos sean afirmados.",
    verseRef: "Proverbios 16:3",
    reflection: "Encomendar tus obras a Dios cambia la manera en que trabajás. Ya no se trata solo de que salgan bien, sino de hacerlas para él y con él. Antes de tu primera tarea de hoy, presentásela en oración y pedile que ordene tus intenciones.",
    closingPrayer: "Padre, pongo en tus manos mi trabajo, mis estudios y mis proyectos. Afirmá lo que sea bueno y corregí lo que no te agrade. Amén.",
  },
  {
    day: 9,
    openingPrayer: "Dios creador, todo comenzó en vos. Que este día también empiece en tu presencia.",
    intro: "Las primeras palabras de la Biblia presentan a Dios antes que todo lo demás. Antes de la luz, del mar o de la humanidad, ya estaba él, creando con propósito los cielos y la tierra.",
    verseRef: "Génesis 1:1",
    reflection: "Si todo tiene su principio en Dios, tu vida no es un accidente ni este año un número más. El mismo que puso orden en el caos puede poner orden en tu agenda y en tu corazón. Empezar con él no es un ritual, es reconocer quién está en el centro.",
    closingPrayer: "Señor, gracias porque sos el principio de todo lo que existe. Ordená mi vida alrededor de vos y no de mis afanes. Amén.",
  },
  {
    day: 10,
    openingPrayer: "Señor, ayudame a poner primero lo que de verdad es primero.",
    intro: "En el Sermón del Monte, Jesús habla a gente preocupada por la comida y la ropa. Les muestra el cuidado del Padre por las aves y los lirios, y los invita a buscar primero su reino y su justicia.",
    verseRef: "Mateo 6:33",
    reflection: "Jesús no promete riqueza a quien lo pone primero, sino el cuidado de un Padre que sabe lo que necesitamos. Buscar su reino es ordenar los afanes bajo su gobierno. Cuando él está primero, las demás cosas encuentran su lugar y pierden su poder para angustiarte.",
    closingPrayer: "Padre, perdoname cuando mis afanes ocupan tu lugar. Enseñame a buscar tu reino hoy en mis decisiones concretas. En el nombre de Jesús. Amén.",
  },
  {
    day: 11,
    openingPrayer: "Dios eterno, mis días son pocos, pero en tus manos tienen sentido.",
    intro: "El Salmo 90 se atribuye a Moisés. Contempla la eternidad de Dios y la brevedad de la vida humana, y termina pidiendo que el Señor confirme la obra de nuestras manos.",
    verseRef: "Salmos 90:17",
    reflection: "Moisés no pide fama ni grandeza, sino que la bondad de Dios repose sobre su trabajo cotidiano. Lo que hacés hoy, aunque parezca pequeño, puede tener valor eterno si se hace delante de Dios. Pedile que confirme lo que tus manos emprenden este año.",
    closingPrayer: "Señor, que tu favor esté sobre mi trabajo. Dame fidelidad en lo pequeño y humildad en lo que salga bien. Amén.",
  },
  {
    day: 12,
    openingPrayer: "Señor, traigo mis temores ante vos. Gracias por sostenerme.",
    intro: "Isaías habla a Israel en tiempos de incertidumbre, cuando las naciones vecinas parecían más fuertes. Dios le recuerda a su pueblo que no está solo, porque él lo esfuerza y lo sostiene.",
    verseRef: "Isaías 41:10",
    reflection: "El temor suele crecer cuando creemos que todo depende de nosotros. Esta promesa pone el peso en otro lugar: Dios sostiene. No sabés todo lo que traerá este año, pero sí sabés quién te sostiene en él.",
    closingPrayer: "Padre, cuando el miedo me hable más fuerte, ayudame a escuchar tu promesa. Sostenme con tu mano firme. Amén.",
  },
  {
    day: 13,
    openingPrayer: "Dios santo, preparame para lo que querés hacer en mí y a través de mí.",
    intro: "El pueblo de Israel estaba a la orilla del Jordán, a punto de cruzar a la tierra prometida. Antes del paso, Josué les pide que se santifiquen, porque el Señor haría maravillas entre ellos.",
    verseRef: "Josué 3:5",
    reflection: "Antes de los grandes pasos, Dios a veces nos llama a preparar el corazón. Santificarse es apartar lo que estorba y disponerse para él. Quizá este comienzo de año sea el momento para dejar algo que no te deja avanzar.",
    closingPrayer: "Señor, mostrame lo que debo apartar para seguirte mejor. Preparame para ver tu obra este año. Amén.",
  },
  {
    day: 14,
    openingPrayer: "Señor, me cuesta esperar. Dame un corazón paciente hoy.",
    intro: "David escribe el Salmo 27 rodeado de enemigos y amenazas. Después de expresar su confianza y su anhelo de estar en la casa de Dios, termina animándose a sí mismo a esperar en el Señor.",
    verseRef: "Salmos 27:14",
    reflection: "Esperar no es lo mismo que resignarse. En la Biblia, esperar en Dios es una forma activa de confiar mientras no ves todavía la respuesta. Si este año comenzó con una oración sin contestar, podés seguir esperando con el corazón firme.",
    closingPrayer: "Padre, fortalecé mi corazón mientras espero. Que mi espera no se vuelva amargura sino confianza. En el nombre de Jesús. Amén.",
  },
  {
    day: 15,
    openingPrayer: "Señor, cuidá mi corazón hoy. Que lo que entre en él te honre.",
    intro: "En Proverbios, un padre exhorta a su hijo a guardar la sabiduría. Entre sus consejos, señala que el corazón merece más cuidado que cualquier otra cosa, porque de él mana la vida.",
    verseRef: "Proverbios 4:23",
    reflection: "Lo que guardás en el corazón termina saliendo en tus palabras, tus decisiones y tus relaciones. Al empezar el año, vale la pena revisar qué estás dejando entrar. Guardá tu corazón no por miedo, sino porque es la fuente de donde fluye tu vida.",
    closingPrayer: "Señor, guardá mi corazón de lo que me aleja de vos. Llenalo de tu verdad y de tu paz este día. Amén.",
  },
  {
    day: 16,
    openingPrayer: "Dios de Abraham, dame fe para seguirte aunque no vea todo el camino.",
    intro: "Abram vivía en Harán con su familia cuando Dios lo llamó a salir hacia una tierra que le mostraría. Junto con el llamado, Dios le prometió hacerlo una gran nación y bendecir por medio de él a otros.",
    verseRef: "Génesis 12:1-2",
    reflection: "El llamado de Dios a Abram empezó con dejar algo conocido. La bendición no era solo para él, sino para que fuera de bendición a otros. Este año Dios también puede llamarte a dar pasos de fe pensando en el bien de quienes te rodean.",
    closingPrayer: "Señor, dame un corazón dispuesto a obedecer tu llamado. Que mi vida sea de bendición para otros. Amén.",
  },
  {
    day: 17,
    openingPrayer: "Señor Jesús, quiero fijar mis ojos en vos durante este día.",
    intro: "Después de recordar a los héroes de la fe, el autor de Hebreos compara la vida cristiana con una carrera. Anima a dejar todo peso y a correr con paciencia, mirando a Jesús, el autor y consumador de la fe.",
    verseRef: "Hebreos 12:1-2",
    reflection: "Una carrera larga no se gana con un arranque fuerte, sino con perseverancia. Hay pesos que no son pecado pero igual te frenan. Mirar a Jesús te recuerda que él terminó la carrera y te sostiene en la tuya.",
    closingPrayer: "Señor Jesús, ayudame a soltar lo que me estorba. Dame paciencia para correr con los ojos puestos en vos. Amén.",
  },
  {
    day: 18,
    openingPrayer: "Dios fuerte, llego cansado ante vos. Gracias porque tu fuerza no se agota.",
    intro: "Isaías consuela a un pueblo agotado que se sentía olvidado. Les recuerda que el Creador no se cansa ni se fatiga, y que él da fuerzas al que no tiene ninguna.",
    verseRef: "Isaías 40:29",
    reflection: "Enero puede empezar con energía y terminar con cansancio. Dios no se fatiga cuando vos sí. Su fuerza no es para los que ya son fuertes, sino para los que reconocen que no pueden más.",
    closingPrayer: "Padre, renová mis fuerzas hoy. Enseñame a descansar en vos y no solo en mi resistencia. Amén.",
  },
  {
    day: 19,
    openingPrayer: "Señor, quiero edificar mi vida sobre lo que no se derrumba.",
    intro: "Jesús termina el Sermón del Monte con una imagen sencilla: dos casas, dos cimientos y una misma tormenta. El hombre prudente es el que oye sus palabras y las pone por obra.",
    verseRef: "Mateo 7:24",
    reflection: "Las dos casas se veían parecidas en días de sol; la diferencia apareció con la tormenta. Oír a Jesús no basta, hay que practicar lo que dice. Escogé hoy una enseñanza suya y ponela en práctica, aunque sea en algo pequeño.",
    closingPrayer: "Señor Jesús, que mi vida esté fundada en tus palabras. Dame obediencia para practicar lo que escucho. Amén.",
  },
  {
    day: 20,
    openingPrayer: "Dios sabio, necesito tu sabiduría para las decisiones de hoy.",
    intro: "Santiago escribe a creyentes que enfrentaban pruebas diversas. Les dice que si a alguno le falta sabiduría, la pida a Dios, que da a todos con generosidad y sin reproche.",
    verseRef: "Santiago 1:5",
    reflection: "Dios no te regaña por no saber qué hacer. Al contrario, invita a pedirle sabiduría con confianza. Si este año trae decisiones que te superan, empezá por llevarlas a él en oración antes que a la preocupación.",
    closingPrayer: "Padre, te pido sabiduría para lo que tengo que decidir. Gracias porque das con generosidad y sin reproche. Amén.",
  },
  {
    day: 21,
    openingPrayer: "Señor de los tiempos, gracias porque cada etapa de mi vida está en tus manos.",
    intro: "El Predicador observa la vida con realismo. Nota que hay un tiempo para cada cosa debajo del cielo: para plantar y arrancar, para llorar y reír.",
    verseRef: "Eclesiastés 3:1",
    reflection: "No todo tiempo es de cosecha; algunos son de siembra o de espera. Reconocer la estación en la que estás te libra de exigirte lo que todavía no corresponde. Dios es Señor de todas las estaciones, también de la que hoy te toca vivir.",
    closingPrayer: "Señor, ayudame a aceptar la etapa en la que me encuentro. Enseñame a vivirla con fe y sin prisa. Amén.",
  },
  {
    day: 22,
    openingPrayer: "Dios de misericordia, en esta mañana quiero escuchar de tu bondad.",
    intro: "David ora en un momento de angustia, perseguido y con el espíritu decaído. Pide a Dios que le haga oír su misericordia por la mañana y que le muestre el camino por donde andar.",
    verseRef: "Salmos 143:8",
    reflection: "David empieza su día buscando dos cosas: la misericordia de Dios y su dirección. No le pide primero que cambien sus circunstancias, sino saber por dónde caminar. Esa puede ser también tu oración al iniciar cada jornada.",
    closingPrayer: "Señor, haceme oír tu misericordia esta mañana. Mostrame el camino y dame valor para andar en él. Amén.",
  },
  {
    day: 23,
    openingPrayer: "Señor, quiero estar atento a tu guía en cada paso de este día.",
    intro: "Isaías habla a un pueblo que había buscado ayuda en Egipto en lugar de confiar en Dios. Aun así, el Señor promete tener piedad y guiarlos, mostrándoles el camino cuando se desvíen a derecha o a izquierda.",
    verseRef: "Isaías 30:21",
    reflection: "Dios guía incluso a quienes se han equivocado de rumbo. Su dirección llega por su Palabra, por el consejo sabio y por la paz que da al obedecer. Pedile hoy oídos atentos para reconocer su voz en medio del ruido.",
    closingPrayer: "Padre, gracias porque no abandonás a quien se desvía. Guiame por tu camino y haceme sensible a tu dirección. Amén.",
  },
  {
    day: 24,
    openingPrayer: "Señor, traigo mis planes ante vos. Enseñame a sostenerlos con manos abiertas.",
    intro: "Proverbios reconoce que el ser humano piensa y planea su camino. Pero al mismo tiempo afirma que es el Señor quien endereza sus pasos.",
    verseRef: "Proverbios 16:9",
    reflection: "Planear es bueno y responsable; aferrarse al plan como si fuera Dios no lo es. El Señor puede usar tus planes, ajustarlos o cambiarlos para tu bien. Hoy podés planificar con diligencia y descansar en que él guía los pasos.",
    closingPrayer: "Señor, te entrego los planes que hice para este año. Dirigí mis pasos aunque cambien mis rutas. Amén.",
  },
  {
    day: 25,
    openingPrayer: "Señor Jesús, dame fe para obedecer aun cuando no entienda.",
    intro: "Pedro y sus compañeros habían trabajado toda la noche sin pescar nada. Jesús le pide que lleve la barca mar adentro y eche las redes otra vez, y Pedro obedece por la palabra de Jesús.",
    verseRef: "Lucas 5:4-5",
    reflection: "Pedro era pescador experimentado y sabía que la noche había sido un fracaso. Aun así, obedeció por confiar en Jesús. Tal vez venís de un esfuerzo que no dio fruto; la invitación es volver a intentarlo, ahora en obediencia a él.",
    closingPrayer: "Señor Jesús, cuando esté cansado de intentar, ayudame a escuchar tu palabra. Dame fe para obedecer aunque no vea resultados. Amén.",
  },
  {
    day: 26,
    openingPrayer: "Dios fiel, gracias porque no me dejás sin dirección.",
    intro: "En el Salmo 32, David celebra el perdón de Dios después de confesar su pecado. En ese contexto aparece la promesa de que el Señor instruye y enseña el camino, mirando con cuidado a los suyos.",
    verseRef: "Salmos 32:8",
    reflection: "La guía de Dios es como la de alguien que acompaña de cerca, con la mirada puesta en vos. No te guía con látigo sino con cuidado. Dejate enseñar hoy con un corazón dócil, sin la terquedad que el salmo advierte después.",
    closingPrayer: "Señor, instruime y enseñame el camino. Dame un corazón dócil que responda a tu cuidado. Amén.",
  },
  {
    day: 27,
    openingPrayer: "Señor, renová mi esperanza y dame paciencia en lo que estoy viviendo.",
    intro: "Pablo describe a los romanos cómo se ve el amor cristiano en la vida diaria. En una lista de exhortaciones breves, los anima a gozarse en la esperanza, ser sufridos en la tribulación y constantes en la oración.",
    verseRef: "Romanos 12:12",
    reflection: "Pablo une tres actitudes que se sostienen mutuamente. La esperanza alimenta la paciencia, y la oración mantiene viva la esperanza. Si hoy estás en medio de una prueba, no tenés que fingir alegría, pero sí podés seguir orando.",
    closingPrayer: "Padre, sostené mi esperanza en vos. Dame paciencia en la prueba y constancia para seguir orando. En el nombre de Jesús. Amén.",
  },
  {
    day: 28,
    openingPrayer: "Dios de las promesas, dame fe para seguirte paso a paso.",
    intro: "Hebreos recuerda la fe de Abraham. Cuando fue llamado, obedeció y salió hacia un lugar que recibiría como herencia, sin saber adónde iba.",
    verseRef: "Hebreos 11:8",
    reflection: "Abraham no tenía un mapa, tenía una promesa. La fe no siempre conoce el destino, pero conoce a quien guía. Si este año te toca avanzar sin todas las respuestas, podés hacerlo confiando en la fidelidad de Dios.",
    closingPrayer: "Señor, aunque no sepa adónde me llevás, quiero seguirte. Fortalecé mi fe en tu fidelidad. Amén.",
  },
  {
    day: 29,
    openingPrayer: "Señor, que mi trabajo de hoy sea una ofrenda para vos.",
    intro: "Pablo escribe a los colosenses sobre la vida en el hogar y en el trabajo. Les dice que todo lo que hagan lo hagan de corazón, como para el Señor y no para la gente.",
    verseRef: "Colosenses 3:23",
    reflection: "No hay tareas insignificantes cuando se hacen para Dios. Barrer, estudiar, vender o cuidar a alguien puede ser adoración. Hoy podés trabajar con excelencia no para impresionar, sino porque servís a Cristo.",
    closingPrayer: "Señor, ayudame a trabajar de corazón y con honestidad. Que mis tareas de hoy honren tu nombre. Amén.",
  },
  {
    day: 30,
    openingPrayer: "Señor Jesús, quiero permanecer unido a vos en todo lo que haga hoy.",
    intro: "La noche antes de su muerte, Jesús enseña a sus discípulos con la imagen de la vid y los pámpanos. Les explica que el fruto viene de permanecer unidos a él.",
    verseRef: "Juan 15:5",
    reflection: "Una rama no se esfuerza por producir uvas; simplemente permanece en la vid. El fruto de tu vida cristiana no depende de tu empeño aislado, sino de tu unión con Cristo. Este año, más que hacer más, buscá permanecer más cerca de él.",
    closingPrayer: "Señor Jesús, sin vos nada puedo hacer. Ayudame a permanecer en vos por medio de tu Palabra y la oración. Amén.",
  },
  {
    day: 31,
    openingPrayer: "Dios bueno, gracias por acompañarme este primer mes del año.",
    intro: "David termina el Salmo 16 con una confesión llena de confianza. Afirma que Dios le muestra la senda de la vida, y que en su presencia hay plenitud de gozo.",
    verseRef: "Salmos 16:11",
    reflection: "Al cerrar enero, vale la pena recordar dónde está el gozo verdadero. No en cumplir todos los propósitos, sino en la presencia de Dios. Él sigue mostrando la senda de la vida para los meses que vienen.",
    closingPrayer: "Señor, gracias por tu presencia en este mes. Guiame por la senda de la vida y llename de tu gozo. En el nombre de Jesús. Amén.",
  },
];
