import type { DevotionalEntry } from "./types";

// Febrero — Amor y amistad: el amor de Dios y amar al prójimo (#199).
export const febrero: readonly DevotionalEntry[] = [
  {
    day: 1,
    openingPrayer: "Dios de amor, gracias porque me amaste antes de que yo pudiera amarte.",
    intro: "Juan escribe a iglesias que necesitaban recordar el centro de la fe. En su primera carta insiste en que todo amor verdadero tiene su origen en Dios.",
    verseRef: "1 Juan 4:19",
    reflection: "Nuestro amor siempre es una respuesta. Antes de que buscaras a Dios, él ya te había buscado en Cristo. Este mes, antes de pensar en cómo amar mejor, detenete a recibir el amor que ya te fue dado.",
    closingPrayer: "Padre, gracias por amarme primero. Que mi amor por vos y por otros nazca de esa gratitud. En el nombre de Jesús. Amén.",
  },
  {
    day: 2,
    openingPrayer: "Señor, enseñame a amar como vos amás, con paciencia y bondad.",
    intro: "Pablo escribe a una iglesia en Corinto dividida por la rivalidad y el orgullo espiritual. En medio de esa tensión describe cómo se comporta el amor en la práctica.",
    verseRef: "1 Corintios 13:4-5",
    reflection: "Esta descripción no habla de sentimientos románticos, sino de decisiones diarias. El amor espera, no presume, no lleva cuenta de lo malo. Leé la lista despacio y elegí una sola cualidad para practicar hoy con alguien de tu casa.",
    closingPrayer: "Señor, perdoname cuando he amado con impaciencia y orgullo. Formá en mí un amor que no busque lo suyo. Amén.",
  },
  {
    day: 3,
    openingPrayer: "Señor Jesús, gracias por tu ejemplo de amor. Que hoy se note en mí.",
    intro: "Durante la última cena, después de lavar los pies de sus discípulos, Jesús les da un mandamiento nuevo. Les pide amarse unos a otros como él los había amado.",
    verseRef: "Juan 13:34-35",
    reflection: "Lo nuevo de este mandamiento es la medida: el amor de Jesús. Él no dijo que el mundo reconocería a sus discípulos por su conocimiento, sino por su amor mutuo. Tu manera de tratar a otros creyentes también es testimonio.",
    closingPrayer: "Señor Jesús, ayudame a amar a mis hermanos como vos nos amaste. Que nuestro amor muestre a otros que somos tuyos. Amén.",
  },
  {
    day: 4,
    openingPrayer: "Dios de gracia, me asombra que me hayas amado así. Gracias.",
    intro: "Pablo explica a los romanos la profundidad del amor de Dios. No esperó a que fuéramos dignos: Cristo murió por nosotros cuando todavía éramos pecadores.",
    verseRef: "Romanos 5:8",
    reflection: "El amor de Dios no depende de tu buen comportamiento. Se demostró en la cruz cuando no tenías nada que ofrecer. Por eso, en tus peores días, ese amor sigue firme.",
    closingPrayer: "Padre, gracias por mostrar tu amor en la cruz. Cuando dude de tu amor, recordame lo que Cristo hizo por mí. Amén.",
  },
  {
    day: 5,
    openingPrayer: "Señor, que tu amor sea la marca de mi vida hoy.",
    intro: "Juan exhorta a los creyentes a amarse unos a otros. Explica que el amor viene de Dios, porque Dios es amor, y que quien no ama no lo ha conocido.",
    verseRef: "1 Juan 4:7-8",
    reflection: "Amar no es un adorno de la fe, es una señal de que conocemos a Dios. Esto no significa amar perfectamente, sino dejar que su amor nos transforme. Pensá en alguien difícil de amar y pedile a Dios que te ayude a verlo con sus ojos.",
    closingPrayer: "Dios de amor, llená mi corazón de tu amor. Ayudame a amar aun a quienes me cuesta. Amén.",
  },
  {
    day: 6,
    openingPrayer: "Señor, gracias por las personas fieles que pusiste en mi camino.",
    intro: "Noemí, viuda y sin hijos, decide volver a Belén y anima a sus nueras a quedarse en Moab. Rut se niega a dejarla y le promete ir con ella, compartir su pueblo y su Dios.",
    verseRef: "Rut 1:16",
    reflection: "La lealtad de Rut no nació en un momento fácil, sino en medio del duelo. Amar a veces significa quedarse cuando sería más cómodo irse. Dios usó esa fidelidad sencilla para escribir una historia de redención.",
    closingPrayer: "Padre, dame un amor leal como el de Rut. Que sepa acompañar a quienes atraviesan tiempos de pérdida. Amén.",
  },
  {
    day: 7,
    openingPrayer: "Señor, gracias por mis amigos. Ayudame a ser un buen amigo también.",
    intro: "Proverbios contiene muchos consejos sobre la amistad. Aquí describe al amigo verdadero como alguien que ama en todo tiempo y al hermano que nace para la hora de la angustia.",
    verseRef: "Proverbios 17:17",
    reflection: "Los amigos de buenos tiempos abundan; los de tiempos difíciles son un tesoro. Más que preguntar si tenés amigos así, preguntate si vos sos ese amigo para alguien. Hoy podés escribirle a alguien que esté pasando un momento duro.",
    closingPrayer: "Señor, gracias por los amigos que me han acompañado. Haceme un amigo fiel en todo tiempo. Amén.",
  },
  {
    day: 8,
    openingPrayer: "Dios, gracias porque no me hiciste para vivir aislado.",
    intro: "El Predicador observa a un hombre que trabaja solo, sin compañero ni familia. Concluye que mejores son dos que uno, porque si uno cae, el otro lo levanta.",
    verseRef: "Eclesiastés 4:9-10",
    reflection: "La autosuficiencia puede parecer fuerza, pero nos deja vulnerables. Dios diseñó la vida para compartirse. Dejate ayudar cuando caigás y estate atento para levantar a otros.",
    closingPrayer: "Padre, librame del orgullo de querer cargar todo solo. Dame humildad para recibir ayuda y disposición para darla. Amén.",
  },
  {
    day: 9,
    openingPrayer: "Señor, vestime hoy de tu amor antes que de cualquier otra cosa.",
    intro: "Pablo enumera a los colosenses virtudes como la compasión, la humildad y la paciencia. Después de todas ellas, les pide vestirse de amor, que las une en perfecta armonía.",
    verseRef: "Colosenses 3:14",
    reflection: "Así como una prenda exterior cubre y sostiene todo lo demás, el amor da unidad a las demás virtudes. Sin amor, la paciencia se vuelve resignación y la humildad, apariencia. Al vestirte hoy, pedile a Dios que te revista de su amor.",
    closingPrayer: "Señor, revestime de tu amor para que todo lo que haga tenga sentido. Que mi vida refleje la armonía que viene de vos. Amén.",
  },
  {
    day: 10,
    openingPrayer: "Dios misericordioso, gracias por perdonarme en Cristo. Enseñame a perdonar.",
    intro: "Pablo enseña a los efesios cómo se vive en comunidad. Después de pedirles dejar la amargura y el enojo, los anima a ser bondadosos y a perdonarse como Dios los perdonó en Cristo.",
    verseRef: "Efesios 4:32",
    reflection: "El perdón cristiano no nace de minimizar el daño, sino de recordar cuánto se nos ha perdonado. Perdonar no siempre es inmediato, pero puede empezar hoy con una oración. Dios te da la gracia que necesitás para dar ese paso.",
    closingPrayer: "Padre, ayudame a perdonar como fui perdonado. Saná las heridas que me cuesta soltar. En el nombre de Jesús. Amén.",
  },
  {
    day: 11,
    openingPrayer: "Señor, que mi amor sea profundo y no solo de palabras.",
    intro: "Pedro escribe a creyentes dispersos que sufrían por su fe. Ante el fin de todas las cosas, les pide sobre todo tener entre ellos un amor ferviente, porque el amor cubre multitud de pecados.",
    verseRef: "1 Pedro 4:8",
    reflection: "El amor no ignora el pecado, pero tampoco lo exhibe ni lo usa como arma. Cubrir es elegir la gracia en lugar del chisme o del rencor. Hoy podés decidir no repetir la falta de alguien y orar por esa persona.",
    closingPrayer: "Señor, dame un amor ferviente por mis hermanos. Guardá mi boca del chisme y llename de gracia. Amén.",
  },
  {
    day: 12,
    openingPrayer: "Señor Jesús, gracias por llamarnos amigos y dar tu vida por nosotros.",
    intro: "En su conversación de despedida, Jesús habla a sus discípulos del amor más grande. Lo describe como poner la vida por los amigos, anticipando lo que él mismo haría en la cruz.",
    verseRef: "Juan 15:13",
    reflection: "Jesús no solo habló de este amor; lo vivió hasta el final. Pocas veces se nos pedirá morir por alguien, pero cada día podemos entregar algo de nosotros por otros. El tiempo, la atención y el servicio son maneras de dar la vida en pequeño.",
    closingPrayer: "Señor Jesús, gracias por dar tu vida por mí. Enseñame a entregar la mía en servicio a los demás. Amén.",
  },
  {
    day: 13,
    openingPrayer: "Dios de amor, gracias porque tu amor es firme y no se apaga.",
    intro: "El Cantar de los Cantares celebra el amor entre un esposo y una esposa. Casi al final, la amada afirma que las muchas aguas no pueden apagar el amor ni los ríos ahogarlo.",
    verseRef: "Cantares 8:7",
    reflection: "El amor verdadero no se compra ni se vende, y resiste las tormentas. Este libro honra el amor matrimonial como un regalo de Dios. Si estás casado, orá hoy por tu cónyuge; si no, dale gracias a Dios por el amor fiel que has visto en otros.",
    closingPrayer: "Señor, gracias por el regalo del amor. Guardá los matrimonios de mi familia y de mi iglesia. Amén.",
  },
  {
    day: 14,
    openingPrayer: "Señor, en este Día del Amor y la Amistad te doy gracias por quienes amo.",
    intro: "Pablo cierra su gran capítulo sobre el amor nombrando tres cosas que permanecen: la fe, la esperanza y el amor. Y afirma que el mayor de ellos es el amor.",
    verseRef: "1 Corintios 13:13",
    reflection: "Hoy en Honduras celebramos el amor y la amistad con flores, mensajes y abrazos. Detrás de esos detalles está algo más grande: el amor que permanece cuando todo lo demás pasa. Celebrá a los tuyos y recordá que ese amor tiene su fuente en Dios.",
    closingPrayer: "Padre, gracias por las personas que me has dado para amar. Que mi amor por ellas refleje tu amor eterno. En el nombre de Jesús. Amén.",
  },
  {
    day: 15,
    openingPrayer: "Señor, gracias porque nada puede separarme de tu amor.",
    intro: "Pablo termina una larga sección de Romanos con una declaración de seguridad. Enumera la muerte, la vida, los ángeles, lo presente y lo por venir, y concluye que nada nos separará del amor de Dios en Cristo.",
    verseRef: "Romanos 8:38-39",
    reflection: "Pablo no ignora el sufrimiento; acaba de hablar de angustia y persecución. Aun así, está seguro de que el amor de Dios en Cristo es más fuerte. Lo que estés viviendo hoy no tiene poder para separarte de ese amor.",
    closingPrayer: "Padre, gracias porque tu amor en Cristo me sostiene. Cuando tenga miedo, recordame que nada me separa de vos. Amén.",
  },
  {
    day: 16,
    openingPrayer: "Dios, me cuesta creer que te alegrás por mí. Ayudame a recibirlo.",
    intro: "Sofonías anuncia juicio, pero termina su libro con una promesa de restauración. Describe a Dios en medio de su pueblo, gozándose sobre él con alegría y con cánticos.",
    verseRef: "Sofonías 3:17",
    reflection: "Muchos imaginan a Dios solo como juez severo. Este pasaje lo muestra deleitándose en su pueblo restaurado. En Cristo, sos objeto de ese gozo, no por tu desempeño sino por su gracia.",
    closingPrayer: "Señor, gracias por tu amor que se alegra en tu pueblo. Calmá mis temores con la certeza de tu amor. Amén.",
  },
  {
    day: 17,
    openingPrayer: "Dios eterno, gracias por tu amor que no tiene fecha de vencimiento.",
    intro: "Jeremías anuncia consuelo a un pueblo que había sufrido mucho. Dios le recuerda a Israel que lo ha amado con amor eterno y que por eso lo ha atraído con misericordia.",
    verseRef: "Jeremías 31:3",
    reflection: "El amor humano a veces se cansa; el de Dios es eterno. No te ama hoy y quizá mañana no; te ama con un amor que antecede y sobrevive a tus días. Ese amor también te atrae, te llama a volver cuando te alejás.",
    closingPrayer: "Padre, gracias por tu amor eterno. Atraeme a vos cada día con tu misericordia. Amén.",
  },
  {
    day: 18,
    openingPrayer: "Señor, dame un corazón que honre a los demás.",
    intro: "En Romanos 12, Pablo describe la vida de una comunidad transformada por el evangelio. Los anima a amarse con cariño de hermanos y a adelantarse en honrarse unos a otros.",
    verseRef: "Romanos 12:10",
    reflection: "Honrar a otros es darles valor, reconocer lo bueno que Dios ha puesto en ellos. Pablo propone una competencia diferente: ver quién honra primero. Hoy podés agradecer o reconocer públicamente a alguien que suele pasar desapercibido.",
    closingPrayer: "Señor, librame de buscar mi propia honra. Ayudame a valorar y a honrar a quienes me rodean. Amén.",
  },
  {
    day: 19,
    openingPrayer: "Señor, gracias por las amistades que me acercan a vos.",
    intro: "Después de la victoria de David sobre Goliat, Jonatán, el hijo del rey Saúl, se une a él en una amistad profunda. La Escritura dice que lo amó como a sí mismo.",
    verseRef: "1 Samuel 18:1",
    reflection: "Jonatán podía ver a David como un rival, pero eligió amarlo. Una amistad sana no compite ni envidia, sino que se alegra por el bien del otro. Pedile a Dios amistades así, y ser ese tipo de amigo.",
    closingPrayer: "Padre, dame amistades fieles y libres de envidia. Ayudame a alegrarme por el bien de mis amigos. Amén.",
  },
  {
    day: 20,
    openingPrayer: "Señor, abrí mis ojos a las cargas de quienes me rodean.",
    intro: "Pablo escribe a los gálatas sobre cómo tratar a un hermano que ha caído. Les pide restaurarlo con mansedumbre y sobrellevar los unos las cargas de los otros, cumpliendo así la ley de Cristo.",
    verseRef: "Gálatas 6:2",
    reflection: "Hay cargas que nadie debería llevar solo: el duelo, la enfermedad, una crisis familiar. Sobrellevar es acercarse y compartir el peso. Preguntá hoy a alguien cómo está de verdad y escuchá con atención.",
    closingPrayer: "Señor Jesús, ayudame a cumplir tu ley de amor llevando las cargas de otros. Dame sensibilidad y disposición. Amén.",
  },
  {
    day: 21,
    openingPrayer: "Señor, quitame el egoísmo y dame un corazón atento a otros.",
    intro: "Pablo anima a los filipenses a vivir en unidad. Les pide no hacer nada por rivalidad o vanagloria, sino considerar a los demás como superiores y buscar también el bien de ellos.",
    verseRef: "Filipenses 2:3-4",
    reflection: "La humildad no es pensar mal de vos, sino pensar menos en vos. Mirar por lo de otros cambia la manera de conversar, trabajar y servir. Antes de una reunión o conversación de hoy, preguntate qué necesita la otra persona.",
    closingPrayer: "Señor, librame de la vanagloria. Enseñame a buscar el bien de los demás como Cristo lo hizo. Amén.",
  },
  {
    day: 22,
    openingPrayer: "Señor Jesús, quiero conocer más tu amor. Abrí mi entendimiento.",
    intro: "Pablo ora por los efesios para que Cristo habite en sus corazones por la fe. Pide que, arraigados en amor, comprendan la anchura, la longitud, la profundidad y la altura del amor de Cristo.",
    verseRef: "Efesios 3:17-19",
    reflection: "El amor de Cristo excede todo conocimiento y aun así Pablo ora para que lo conozcamos. Es un amor para explorar toda la vida. Hoy podés pedirle a Dios que te muestre una dimensión de ese amor que todavía no has experimentado.",
    closingPrayer: "Padre, arraigame en el amor de Cristo. Dame a conocer su grandeza y llename de tu plenitud. Amén.",
  },
  {
    day: 23,
    openingPrayer: "Señor, que mi amor se vea en hechos y no solo en palabras.",
    intro: "Juan advierte a los creyentes contra un amor solo de discurso. Les pide amar de hecho y en verdad, especialmente al ver a un hermano en necesidad.",
    verseRef: "1 Juan 3:18",
    reflection: "Es fácil decir que amamos; es más costoso demostrarlo. El amor verdadero se nota en la mesa compartida, en la ayuda concreta y en el tiempo dado. Pensá en una acción sencilla con la que hoy podés mostrar amor a alguien.",
    closingPrayer: "Señor, perdoname por amar solo de palabra. Dame oportunidades para amar con hechos y en verdad. Amén.",
  },
  {
    day: 24,
    openingPrayer: "Dios, quiero amarte con todo lo que soy.",
    intro: "Un intérprete de la ley pregunta a Jesús cuál es el gran mandamiento. Jesús responde con el amor a Dios con todo el corazón, el alma y la mente, y añade el amor al prójimo como a uno mismo.",
    verseRef: "Mateo 22:37-39",
    reflection: "Jesús une dos amores que nunca deben separarse. Amar a Dios sin amar al prójimo es religiosidad vacía, y amar al prójimo sin Dios pierde su fuente. Toda la vida cristiana cabe en estos dos mandamientos.",
    closingPrayer: "Señor, ayudame a amarte con todo mi ser y a amar a mi prójimo como a mí mismo. En el nombre de Jesús. Amén.",
  },
  {
    day: 25,
    openingPrayer: "Señor, que mi amor no haga daño a nadie hoy.",
    intro: "Pablo resume los mandamientos que tienen que ver con el prójimo: no adulterar, no matar, no hurtar, no codiciar. Concluye que el amor no hace mal y por eso es el cumplimiento de la ley.",
    verseRef: "Romanos 13:10",
    reflection: "El amor no anula los mandamientos; los cumple desde adentro. Quien ama no busca aprovecharse ni herir. Esta perspectiva puede guiarte en decisiones de trabajo, de negocios y de familia.",
    closingPrayer: "Padre, que el amor gobierne mis acciones. Guardame de hacer daño a otros con mis palabras o decisiones. Amén.",
  },
  {
    day: 26,
    openingPrayer: "Señor, dame ojos de compasión como los del buen samaritano.",
    intro: "Jesús cuenta la historia de un hombre asaltado y dejado medio muerto en el camino. Un sacerdote y un levita pasan de largo, pero un samaritano se detiene, lo cura y lo lleva a un mesón.",
    verseRef: "Lucas 10:33-34",
    reflection: "El samaritano no preguntó si el herido era de su grupo. Simplemente vio, se compadeció y actuó. Amar al prójimo empieza por detenernos ante el que sufre, aunque eso nos cueste tiempo o recursos.",
    closingPrayer: "Señor Jesús, no me dejés pasar de largo ante el dolor ajeno. Dame compasión que se traduzca en ayuda. Amén.",
  },
  {
    day: 27,
    openingPrayer: "Señor, guardá mi lengua hoy y dame palabras de paz.",
    intro: "Proverbios observa con sabiduría práctica el poder de las palabras. Afirma que la respuesta suave aplaca la ira, mientras que la palabra áspera hace subir el furor.",
    verseRef: "Proverbios 15:1",
    reflection: "Muchas peleas en casa crecen no por el tema, sino por el tono. Responder con suavidad no es debilidad, es dominio propio. La próxima vez que sientas que se calienta una conversación, intentá bajar la voz antes de subir el argumento.",
    closingPrayer: "Señor, dame mansedumbre en mis respuestas. Que mis palabras traigan paz a mi hogar y no conflicto. Amén.",
  },
  {
    day: 28,
    openingPrayer: "Señor, gracias por mi iglesia. Ayudame a animar a otros hoy.",
    intro: "El autor de Hebreos anima a los creyentes a mantenerse firmes en la fe. Les pide considerarse unos a otros para estimularse al amor y a las buenas obras.",
    verseRef: "Hebreos 10:24",
    reflection: "Pensar en cómo animar a otros es una práctica intencional. Un mensaje, una visita o una palabra de aliento pueden reavivar el amor de alguien cansado. Hoy podés ser la razón por la que un hermano no se rinda.",
    closingPrayer: "Padre, mostrame a quién necesito animar hoy. Usame para estimular a otros al amor y a las buenas obras. Amén.",
  },
  {
    day: 29,
    openingPrayer: "Señor, gracias por la familia de la fe. Que vivamos en unidad.",
    intro: "El Salmo 133 es un cántico de los peregrinos que subían a Jerusalén. Celebra cuán bueno y agradable es que los hermanos habiten juntos en armonía.",
    verseRef: "Salmos 133:1",
    reflection: "La unidad no es uniformidad; es amor que sostiene a personas distintas bajo un mismo Señor. Es un regalo de Dios y también una tarea diaria. Este día extra del año puede ser una oportunidad para buscar la reconciliación con alguien.",
    closingPrayer: "Señor, guardá la unidad de mi familia y de mi iglesia. Haceme un instrumento de paz entre mis hermanos. Amén.",
  },
];
