import type { DevotionalEntry } from "./types";

// Marzo — Cuaresma, arrepentimiento y camino a la cruz (#199).
export const marzo: readonly DevotionalEntry[] = [
  {
    day: 1,
    openingPrayer: "Dios misericordioso, quiero volver a vos con todo mi corazón en esta temporada.",
    intro: "El profeta Joel habla en un tiempo de calamidad para Judá. En lugar de ritos vacíos, Dios invita a su pueblo a volver a él de corazón, porque es clemente y misericordioso.",
    verseRef: "Joel 2:12-13",
    reflection: "La invitación no es a romper la ropa, sino a abrir el corazón. Dios no busca apariencias de dolor, sino un regreso sincero. Esta temporada antes de la Pascua puede ser un tiempo para volver, sabiendo que te espera un Dios lento para la ira.",
    closingPrayer: "Padre, gracias porque sos clemente y grande en misericordia. Ayudame a volver a vos con sinceridad y sin miedo. En el nombre de Jesús. Amén.",
  },
  {
    day: 2,
    openingPrayer: "Señor, creá en mí un corazón limpio. Necesito tu obra en mi interior.",
    intro: "David escribe el Salmo 51 después de que el profeta Natán lo confrontara por su pecado con Betsabé. En lugar de excusarse, le pide a Dios un corazón limpio y un espíritu recto.",
    verseRef: "Salmos 51:10",
    reflection: "David no pide solo perdón por un acto, sino una renovación desde adentro. Sabía que no podía limpiar su corazón por sí mismo. Esa misma oración está disponible para vos hoy, cualquiera que sea tu historia.",
    closingPrayer: "Dios santo, creá en mí un corazón limpio y renová un espíritu recto dentro de mí. Gracias porque no despreciás al corazón quebrantado. Amén.",
  },
  {
    day: 3,
    openingPrayer: "Señor, traigo ante vos lo que me pesa. Gracias por tu perdón.",
    intro: "Isaías confronta a Judá por una religión llena de ritos pero vacía de justicia. Aun así, Dios abre la puerta a la reconciliación y promete limpiar pecados rojos como la grana hasta dejarlos blancos.",
    verseRef: "Isaías 1:18",
    reflection: "Dios no se limita a señalar el pecado; ofrece limpiarlo. La mancha que parece imposible de quitar puede ser lavada por su gracia. En Cristo, esta promesa alcanza su cumplimiento pleno.",
    closingPrayer: "Padre, gracias porque tu gracia limpia lo que yo no puedo. Lavame y ayudame a vivir en justicia. Amén.",
  },
  {
    day: 4,
    openingPrayer: "Señor Jesús, gracias porque entendés mis luchas.",
    intro: "El autor de Hebreos presenta a Jesús como nuestro gran sumo sacerdote. Explica que él fue tentado en todo como nosotros, pero sin pecado, y por eso puede compadecerse de nuestras debilidades.",
    verseRef: "Hebreos 4:15",
    reflection: "No te acercás a un Salvador distante. Jesús conoce la tentación desde adentro y nunca cedió a ella. Por eso podés traerle tus luchas sin vergüenza y recibir gracia para el oportuno socorro.",
    closingPrayer: "Señor Jesús, gracias por compadecerte de mi debilidad. Dame tu gracia para resistir la tentación de hoy. Amén.",
  },
  {
    day: 5,
    openingPrayer: "Dios que me conocés, examiná mi corazón con tu luz.",
    intro: "David termina el Salmo 139 maravillado de que Dios lo conoce por completo. En lugar de esconderse, le pide que lo examine, que vea si hay en él camino de perversidad y que lo guíe.",
    verseRef: "Salmos 139:23-24",
    reflection: "Pedirle a Dios que nos examine requiere confianza. David lo hace porque sabe que quien lo conoce también lo ama. Dejar que Dios ilumine tu interior no es para condenarte, sino para guiarte por el camino eterno.",
    closingPrayer: "Señor, examiname y conocé mi corazón. Mostrame lo que debo cambiar y guiame por tu camino. Amén.",
  },
  {
    day: 6,
    openingPrayer: "Señor, quiero buscarte hoy mientras me llamás.",
    intro: "Isaías extiende una invitación a quienes se habían alejado de Dios. Los llama a buscarlo mientras puede ser hallado y a volverse a él, porque es amplio en perdonar.",
    verseRef: "Isaías 55:6-7",
    reflection: "El arrepentimiento tiene dos movimientos: dejar el mal camino y volver a Dios. Lo sorprendente es la respuesta que espera al que regresa: misericordia abundante. No hay pecado tan grande que agote su perdón.",
    closingPrayer: "Padre, gracias porque sos amplio en perdonar. Ayudame a dejar lo que me aleja de vos y a volver hoy. Amén.",
  },
  {
    day: 7,
    openingPrayer: "Padre, gracias por recibirme cuando vuelvo a casa.",
    intro: "Jesús cuenta la historia de un hijo que malgastó su herencia y decidió volver a su padre. Cuando aún estaba lejos, el padre lo vio, corrió hacia él, lo abrazó y lo besó.",
    verseRef: "Lucas 15:20",
    reflection: "El hijo había preparado un discurso, pero el padre corrió antes de escucharlo. Así describe Jesús el corazón de Dios hacia quien se arrepiente. No tenés que ganarte el regreso; solo volver.",
    closingPrayer: "Padre, gracias por correr hacia mí con misericordia. Quitame la vergüenza que me aleja y enseñame a descansar en tu abrazo. Amén.",
  },
  {
    day: 8,
    openingPrayer: "Señor Jesús, quiero seguirte aunque me cueste.",
    intro: "Después de anunciar a sus discípulos que debía sufrir y morir, Jesús les explica qué significa seguirlo. Quien quiera ir en pos de él debe negarse a sí mismo y tomar su cruz.",
    verseRef: "Mateo 16:24",
    reflection: "Seguir a Jesús no es añadirlo a una vida que sigue igual. Implica decirle no al yo que quiere el control y decirle sí a su camino. Ese camino pasa por la cruz, pero termina en vida.",
    closingPrayer: "Señor Jesús, dame valor para negarme a mí mismo y seguirte. Que tu camino sea el mío hoy. Amén.",
  },
  {
    day: 9,
    openingPrayer: "Dios de amor, gracias porque enviaste a tu Hijo para salvar y no para condenar.",
    intro: "En su conversación con Nicodemo, Jesús explica la razón de su venida. Justo después de hablar del amor de Dios por el mundo, aclara que el Hijo no fue enviado para condenar sino para salvar.",
    verseRef: "Juan 3:17",
    reflection: "Muchos ven a Dios como alguien que espera para castigar. Este versículo muestra lo contrario: su propósito al enviar a Jesús fue rescatar. La Cuaresma no es un tiempo para sentirte condenado, sino para recibir la salvación ofrecida.",
    closingPrayer: "Padre, gracias porque en Jesús me ofrecés salvación y no condena. Ayudame a mostrar esa misma gracia a otros. Amén.",
  },
  {
    day: 10,
    openingPrayer: "Señor, vengo herido ante vos. Gracias porque sanás.",
    intro: "Oseas profetiza en un tiempo en que Israel se había alejado de Dios. En este pasaje, el pueblo se anima a volver, confiando en que el mismo Señor que lo disciplinó también lo sanará.",
    verseRef: "Oseas 6:1",
    reflection: "A veces las consecuencias de nuestras decisiones nos duelen. Oseas muestra que el regreso a Dios es también el camino a la sanidad. Él no se queda en la herida; venda y restaura a quien vuelve.",
    closingPrayer: "Señor, vuelvo a vos con mis heridas. Vendá mi corazón y restaurá mi relación con vos. Amén.",
  },
  {
    day: 11,
    openingPrayer: "Dios fiel, quiero ser honesto con vos hoy.",
    intro: "En el Salmo 32, David recuerda el peso que sintió mientras callaba su pecado. Cuando finalmente lo confesó, experimentó el perdón y el alivio de Dios.",
    verseRef: "Salmos 32:5",
    reflection: "Esconder el pecado desgasta por dentro. Confesarlo a Dios no es darle información nueva, sino dejar de cargarlo solo. El perdón llega como alivio a quien deja de esconderse.",
    closingPrayer: "Señor, te confieso lo que he callado. Gracias por perdonar y quitar el peso de mi culpa. Amén.",
  },
  {
    day: 12,
    openingPrayer: "Padre, gracias porque sos fiel para perdonar.",
    intro: "Juan escribe a creyentes que luchaban con el pecado. Les recuerda que decir que no tenemos pecado es engañarnos, pero que si lo confesamos, Dios es fiel y justo para perdonar y limpiar.",
    verseRef: "1 Juan 1:9",
    reflection: "El perdón de Dios no depende de la intensidad de tu arrepentimiento, sino de su fidelidad y de la obra de Cristo. Confesar es estar de acuerdo con Dios sobre tu pecado y confiar en su gracia. No tenés que vivir con cuentas pendientes delante de él.",
    closingPrayer: "Padre, gracias por ser fiel y justo para perdonarme en Cristo. Limpiame de toda maldad y dame paz. Amén.",
  },
  {
    day: 13,
    openingPrayer: "Señor Jesús, enseñame el camino de la entrega.",
    intro: "Poco antes de su muerte, Jesús habla de su hora usando la imagen de un grano de trigo. Si no cae en la tierra y muere, queda solo; pero si muere, lleva mucho fruto.",
    verseRef: "Juan 12:24",
    reflection: "Jesús habla primero de sí mismo: su muerte traería vida a muchos. También muestra un principio para quienes lo siguen. Hay cosas que solo dan fruto cuando las soltamos en manos de Dios.",
    closingPrayer: "Señor Jesús, gracias por entregar tu vida para dar fruto en muchos. Ayudame a soltar lo que retengo por miedo. Amén.",
  },
  {
    day: 14,
    openingPrayer: "Señor, enseñame a servir como Jesús sirvió.",
    intro: "Santiago y Juan le pidieron a Jesús lugares de honor en su reino. Jesús les explica que en su reino la grandeza se mide sirviendo, y que él mismo vino a servir y a dar su vida en rescate por muchos.",
    verseRef: "Marcos 10:45",
    reflection: "El Hijo del Hombre tenía todo derecho a ser servido, pero eligió servir. Su servicio llegó hasta la entrega de su vida como rescate. Seguirlo transforma la manera en que buscamos posición e influencia.",
    closingPrayer: "Señor Jesús, gracias por dar tu vida en rescate por mí. Librame de buscar grandeza y dame un corazón de siervo. Amén.",
  },
  {
    day: 15,
    openingPrayer: "Señor Jesús, me acerco con gratitud a tus heridas.",
    intro: "Isaías describe a un siervo que sufriría por los pecados de otros. Siglos antes de la cruz, anuncia que él sería herido por nuestras rebeliones y que por su llaga seríamos sanados.",
    verseRef: "Isaías 53:5",
    reflection: "Los creyentes reconocemos en este siervo a Jesús. Lo que nosotros merecíamos cayó sobre él, para que recibiéramos paz con Dios. Cada vez que mirás la cruz, ves el precio de tu reconciliación.",
    closingPrayer: "Señor Jesús, gracias por cargar mi castigo. Que nunca dé por sentado el precio de mi paz. Amén.",
  },
  {
    day: 16,
    openingPrayer: "Señor, quiero tener la misma actitud humilde de Cristo.",
    intro: "Pablo presenta a los filipenses el ejemplo supremo de humildad. Cristo, siendo en forma de Dios, se humilló y se hizo obediente hasta la muerte, y muerte de cruz.",
    verseRef: "Filipenses 2:8",
    reflection: "La humildad de Jesús no fue fingida ni parcial; llegó hasta la muerte más vergonzosa de su tiempo. Su obediencia nos salvó y también nos muestra el camino. Mirá su ejemplo cuando el orgullo te pida defender tu lugar.",
    closingPrayer: "Señor Jesús, gracias por humillarte hasta la cruz por mí. Formá en mí tu humildad y obediencia. Amén.",
  },
  {
    day: 17,
    openingPrayer: "Señor Jesús, gracias por ser mi buen pastor.",
    intro: "Jesús se presenta ante sus oyentes como el buen pastor, en contraste con los asalariados que huyen ante el peligro. Afirma que el buen pastor da su vida por las ovejas.",
    verseRef: "Juan 10:11",
    reflection: "Un asalariado cuida las ovejas mientras le conviene; el buen pastor las cuida hasta el final. Jesús no solo guía a los suyos, entregó su vida por ellos. Podés seguirlo con confianza porque ya probó cuánto te ama.",
    closingPrayer: "Señor Jesús, gracias por dar tu vida por tus ovejas. Ayudame a escuchar tu voz y seguirte. Amén.",
  },
  {
    day: 18,
    openingPrayer: "Señor, gracias porque me buscaste cuando estaba perdido.",
    intro: "Zaqueo, jefe de cobradores de impuestos en Jericó, subió a un árbol para ver a Jesús. Jesús se hospedó en su casa, y ante las murmuraciones explicó que había venido a buscar y salvar lo que se había perdido.",
    verseRef: "Lucas 19:10",
    reflection: "La gente veía en Zaqueo un caso perdido; Jesús vio a alguien a quien buscar. Su gracia transformó a Zaqueo de tal manera que quiso devolver lo que había robado. Nadie está demasiado lejos para que Jesús lo busque.",
    closingPrayer: "Señor Jesús, gracias por buscarme y salvarme. Usame para mostrar tu gracia a quienes otros dan por perdidos. Amén.",
  },
  {
    day: 19,
    openingPrayer: "Padre celestial, gracias por tu cuidado y por los padres que reflejan tu amor.",
    intro: "En el Salmo 103, David bendice a Dios por todos sus beneficios. Para describir su compasión, usa la imagen de un padre que se compadece de sus hijos.",
    verseRef: "Salmos 103:13",
    reflection: "Hoy en Honduras celebramos el Día del Padre. Algunos tienen recuerdos hermosos de su papá y otros cargan heridas. En ambos casos, Dios se presenta como un Padre compasivo que conoce nuestra fragilidad y nos trata con ternura.",
    closingPrayer: "Padre, bendecí a los papás de mi familia y de mi iglesia. Saná las heridas de quienes no tuvieron un padre presente. En el nombre de Jesús. Amén.",
  },
  {
    day: 20,
    openingPrayer: "Señor Jesús, gracias porque en vos hay vida aun frente a la muerte.",
    intro: "Lázaro había muerto y sus hermanas lloraban. Ante Marta, Jesús se presenta como la resurrección y la vida, y poco después llama a Lázaro a salir de la tumba.",
    verseRef: "Juan 11:25",
    reflection: "Jesús no da una explicación sobre la muerte, se presenta a sí mismo como la respuesta. Antes de resucitar a Lázaro, lloró con quienes lloraban. Mientras nos acercamos a la cruz, esta promesa anticipa la victoria de la resurrección.",
    closingPrayer: "Señor Jesús, gracias porque sos la resurrección y la vida. Consolá a quienes hoy lloran la pérdida de un ser querido. Amén.",
  },
  {
    day: 21,
    openingPrayer: "Rey Jesús, te recibo con humildad y gozo en mi vida.",
    intro: "Siglos antes de la Semana Santa, Zacarías anunció la llegada de un rey justo y salvador. No vendría en caballo de guerra, sino humilde, montado sobre un asno.",
    verseRef: "Zacarías 9:9",
    reflection: "Los evangelios ven cumplida esta profecía cuando Jesús entra en Jerusalén. Es un rey diferente: no conquista con espada, sino con humildad y paz. En esta Semana Santa, preguntate cómo lo recibís en tu propia vida.",
    closingPrayer: "Señor Jesús, sos mi Rey humilde y salvador. Reiná en mi corazón con tu paz. Amén.",
  },
  {
    day: 22,
    openingPrayer: "Señor Jesús, quiero alabarte con todo mi corazón.",
    intro: "Cuando Jesús entró en Jerusalén, la multitud tendió mantos y ramas en el camino. Lo aclamaban con el Hosanna, reconociéndolo como el que viene en el nombre del Señor.",
    verseRef: "Mateo 21:9",
    reflection: "La misma ciudad que lo aclamó pronto pediría su crucifixión. El entusiasmo de un día no basta; Jesús busca seguidores que permanezcan. Recordar el Domingo de Ramos nos invita a una alabanza que dure más allá de la emoción.",
    closingPrayer: "Señor Jesús, quiero alabarte no solo con mis labios sino con mi vida. Hacé que mi fe permanezca firme. Amén.",
  },
  {
    day: 23,
    openingPrayer: "Señor Jesús, enseñame a servir con humildad como vos serviste.",
    intro: "En la noche de la última cena, Jesús se levantó de la mesa, tomó una toalla y lavó los pies de sus discípulos. Luego les explicó que les había dado ejemplo para que hicieran lo mismo.",
    verseRef: "Juan 13:14-15",
    reflection: "Lavar pies era tarea de siervos, y el Maestro la hizo sin dudar. Pocas horas antes de la cruz, Jesús mostró que el amor se expresa sirviendo. Hoy podés buscar una manera humilde y concreta de servir a alguien.",
    closingPrayer: "Señor Jesús, gracias por tu ejemplo de servicio. Dame humildad para servir a otros sin esperar reconocimiento. Amén.",
  },
  {
    day: 24,
    openingPrayer: "Señor Jesús, gracias por tu cuerpo entregado y tu sangre derramada.",
    intro: "Durante la última cena, Jesús tomó el pan y la copa y les dio un nuevo significado. Les pidió a sus discípulos que lo hicieran en memoria de él, anunciando el nuevo pacto en su sangre.",
    verseRef: "Lucas 22:19-20",
    reflection: "Cada vez que la iglesia celebra la Cena del Señor, recuerda la entrega de Jesús. No es un rito vacío, sino una memoria viva de su amor y del nuevo pacto. Recordar su sacrificio renueva nuestra gratitud y nuestra esperanza.",
    closingPrayer: "Señor Jesús, gracias por el nuevo pacto en tu sangre. Que nunca olvide el precio de tu amor. Amén.",
  },
  {
    day: 25,
    openingPrayer: "Padre, enseñame a confiar en tu voluntad aun cuando duele.",
    intro: "En el huerto de Getsemaní, Jesús oró con angustia antes de su arresto. Le pidió al Padre que, si era posible, pasara de él aquella copa, pero se sometió a su voluntad.",
    verseRef: "Mateo 26:39",
    reflection: "Jesús no fingió que la cruz era fácil; expresó su angustia con honestidad. Aun así, eligió la voluntad del Padre por amor a nosotros. Su oración te enseña que podés ser sincero con Dios y a la vez rendirte a él.",
    closingPrayer: "Padre, gracias por la obediencia de Jesús en Getsemaní. Dame un corazón que confíe en tu voluntad cuando no entienda. Amén.",
  },
  {
    day: 26,
    openingPrayer: "Señor, reconozco que me he desviado. Gracias por tu gracia.",
    intro: "Isaías compara a la humanidad con ovejas descarriadas, cada una por su propio camino. Luego anuncia que el Señor cargó en su siervo el pecado de todos.",
    verseRef: "Isaías 53:6",
    reflection: "El versículo empieza y termina con la palabra todos: todos nos desviamos, y el pecado de todos fue cargado sobre él. Nadie queda fuera de la necesidad ni fuera del alcance de esa gracia. En la cruz, Jesús llevó lo que no podíamos cargar.",
    closingPrayer: "Señor Jesús, gracias por cargar mi pecado. Hacé que vuelva a vos como oveja a su pastor. Amén.",
  },
  {
    day: 27,
    openingPrayer: "Señor Jesús, me detengo ante la cruz con gratitud y reverencia.",
    intro: "Juan relata los últimos momentos de Jesús en la cruz. Después de recibir el vinagre, Jesús declaró que todo estaba consumado, inclinó la cabeza y entregó el espíritu.",
    verseRef: "Juan 19:30",
    reflection: "Consumado significa completo, terminado, pagado. La obra de salvación no quedó a medias ni depende de tus esfuerzos para completarse. Podés descansar en lo que Jesús terminó en la cruz.",
    closingPrayer: "Señor Jesús, gracias porque tu obra está completa. Ayudame a vivir confiando en lo que hiciste por mí. Amén.",
  },
  {
    day: 28,
    openingPrayer: "Señor Jesús, tu perdón en la cruz me asombra.",
    intro: "Mientras era crucificado, Jesús oró por quienes lo estaban clavando y por los que se burlaban de él. Le pidió al Padre que los perdonara, porque no sabían lo que hacían.",
    verseRef: "Lucas 23:34",
    reflection: "En el momento de mayor dolor, Jesús oró por sus verdugos. Su perdón alcanza también a quienes lo rechazaron, y nos alcanza a nosotros. Desde ese amor podemos empezar a perdonar a quienes nos han herido.",
    closingPrayer: "Señor Jesús, gracias por perdonarme cuando no lo merecía. Ayudame a perdonar a quienes me han ofendido. Amén.",
  },
  {
    day: 29,
    openingPrayer: "Señor Jesús, gracias porque la tumba está vacía.",
    intro: "Al amanecer del primer día de la semana, unas mujeres fueron al sepulcro donde habían puesto a Jesús. Un ángel les anunció que no tuvieran miedo, porque Jesús había resucitado como había dicho.",
    verseRef: "Mateo 28:5-6",
    reflection: "La resurrección es el corazón de nuestra esperanza. Las mujeres fueron a buscar a un muerto y encontraron una noticia que cambió la historia. Jesús cumplió su palabra, y por eso podemos confiar en todas sus promesas.",
    closingPrayer: "Señor Jesús, gracias porque venciste a la muerte. Llená mi vida de la esperanza de tu resurrección. Amén.",
  },
  {
    day: 30,
    openingPrayer: "Dios de vida, gracias por la victoria de Cristo sobre la muerte.",
    intro: "Algunos en Corinto dudaban de la resurrección de los muertos. Pablo les responde con firmeza que Cristo ha resucitado y que es primicia de los que durmieron.",
    verseRef: "1 Corintios 15:20",
    reflection: "Las primicias eran el primer fruto de la cosecha, la garantía de que vendría el resto. La resurrección de Cristo anuncia la resurrección de todos los que son suyos. La muerte no tiene la última palabra para quienes están en él.",
    closingPrayer: "Padre, gracias por la resurrección de Jesús. Dame esperanza firme ante la muerte y gozo en la vida. Amén.",
  },
  {
    day: 31,
    openingPrayer: "Señor, gracias por la vida nueva en Cristo. Que hoy camine en ella.",
    intro: "Pablo explica a los romanos el significado del bautismo. Así como Cristo murió y resucitó, los creyentes son sepultados con él para andar en vida nueva.",
    verseRef: "Romanos 6:4",
    reflection: "El camino de la cruz no termina en la tumba, sino en una vida nueva. Lo que Jesús hizo afecta tu manera de vivir hoy. Al cerrar este mes, recordá que la gracia que perdona también transforma.",
    closingPrayer: "Señor, gracias por unirme a Cristo en su muerte y resurrección. Ayudame a andar en vida nueva cada día. En el nombre de Jesús. Amén.",
  },
];
