import type { DevotionalEntry } from "./types";

// Abril — Pascua y vida nueva: la resurrección y la esperanza viva (#199).
export const abril: readonly DevotionalEntry[] = [
  {
    day: 1,
    openingPrayer: "Señor, al comenzar este mes, quiero mirar de nuevo la tumba vacía. Despertá en mí la esperanza.",
    intro: "Al amanecer del primer día de la semana, unas mujeres llegaron al sepulcro con especias para el cuerpo de Jesús. Esperaban encontrar a un muerto, pero unos ángeles les anunciaron una noticia que nadie esperaba.",
    verseRef: "Lucas 24:5-6",
    reflection: "Las mujeres fueron fieles en medio del dolor, pero buscaban en el lugar equivocado. A veces también buscamos vida entre lo que ya terminó. Cristo resucitó, y su resurrección abre caminos donde vos solo veías un final.",
    closingPrayer: "Padre, gracias porque Jesús no quedó en la tumba. Ayudame a dejar de buscar vida donde no la hay y a mirar a Cristo resucitado. En el nombre de Jesús. Amén.",
  },
  {
    day: 2,
    openingPrayer: "Dios de misericordia, gracias por darme una esperanza que no se apaga.",
    intro: "Pedro escribe a creyentes dispersos que sufrían por su fe. Antes de hablar de sus pruebas, alaba a Dios por algo que ya tienen: un nuevo nacimiento ligado a la resurrección de Jesús.",
    verseRef: "1 Pedro 1:3",
    reflection: "La esperanza cristiana no es optimismo ni buena actitud. Está viva porque descansa en un Cristo vivo. Aun en días grises, tu futuro está unido al de él, y eso no lo cambia ninguna circunstancia.",
    closingPrayer: "Señor, gracias por la vida nueva que me diste en Cristo. Cuando el desánimo me pese, recordame que mi esperanza está viva. Amén.",
  },
  {
    day: 3,
    openingPrayer: "Señor Jesús, gracias porque conocés mi nombre. Quiero reconocer tu voz hoy.",
    intro: "María Magdalena lloraba junto al sepulcro vacío, convencida de que se habían llevado el cuerpo de su Señor. Jesús estaba frente a ella, pero no lo reconoció hasta que él la llamó por su nombre.",
    verseRef: "Juan 20:16",
    reflection: "Las lágrimas pueden nublar la vista al punto de no ver que Jesús está cerca. Él no se presentó a María con un discurso, sino llamándola por su nombre. El Resucitado te conoce personalmente y sale a tu encuentro en medio del llanto.",
    closingPrayer: "Señor, gracias porque no soy un número para vos. Abrí mis ojos para reconocerte cerca, aun cuando estoy triste. Amén.",
  },
  {
    day: 4,
    openingPrayer: "Dios de gracia, gracias porque nunca es tarde para volverse a vos.",
    intro: "Junto a Jesús fueron crucificados dos malhechores. Uno de ellos, en sus últimas horas, reconoció su culpa y le pidió a Jesús que se acordara de él cuando viniera en su reino.",
    verseRef: "Lucas 23:42-43",
    reflection: "Aquel hombre no tenía obras que presentar ni tiempo para enmendar su vida. Solo tenía fe en Jesús, y eso bastó. La salvación no se gana con un historial limpio; se recibe confiando en Cristo, incluso al final del camino.",
    closingPrayer: "Señor Jesús, acordate de mí. Gracias porque tu gracia alcanza a quien se vuelve a vos con sinceridad. Ayudame a no dar a nadie por perdido. Amén.",
  },
  {
    day: 5,
    openingPrayer: "Padre santo, me acerco con gratitud por lo que Cristo hizo en mi lugar.",
    intro: "Pablo explica a los corintios el corazón del evangelio. Cristo, que no conoció pecado, cargó con el nuestro, para que en él recibiéramos la justicia de Dios.",
    verseRef: "2 Corintios 5:21",
    reflection: "Aquí hay un intercambio asombroso: Jesús tomó lo que era nuestro y nos dio lo que era suyo. No tenés que fabricar tu propia justicia delante de Dios. En Cristo ya fuiste aceptado, y desde ahí podés vivir con libertad.",
    closingPrayer: "Señor, gracias porque Jesús cargó mi pecado y me vistió de su justicia. Que esta verdad me quite el miedo y me llene de gratitud. Amén.",
  },
  {
    day: 6,
    openingPrayer: "Dios eterno, gracias porque en Cristo la muerte no tiene la última palabra.",
    intro: "Al final de su gran capítulo sobre la resurrección, Pablo casi canta. Se dirige a la muerte como a un enemigo vencido que ya perdió su aguijón.",
    verseRef: "1 Corintios 15:55",
    reflection: "La muerte sigue doliendo, y es justo llorar a quienes partieron. Pero para quien está en Cristo, ya no es una derrota definitiva. La resurrección de Jesús le quitó el poder de separarnos para siempre de Dios.",
    closingPrayer: "Señor, gracias porque Cristo venció a la muerte. Consolá a quienes hoy extrañan a alguien y afirmá nuestra esperanza en la resurrección. Amén.",
  },
  {
    day: 7,
    openingPrayer: "Espíritu Santo, gracias por habitar en mí. Que hoy viva desde esa presencia.",
    intro: "En Romanos 8 Pablo habla de la vida en el Espíritu. Afirma que el mismo Espíritu que levantó a Jesús de los muertos habita en los creyentes y dará vida también a sus cuerpos mortales.",
    verseRef: "Romanos 8:11",
    reflection: "El poder que resucitó a Cristo no es una idea lejana; está obrando en quienes creen. Eso no significa que todo será fácil, sino que no dependés solo de tus fuerzas. Dios está trayendo vida a lo que en vos parecía muerto.",
    closingPrayer: "Padre, gracias por tu Espíritu que habita en mí. Dame vida donde me siento cansado y seco. En el nombre de Jesús. Amén.",
  },
  {
    day: 8,
    openingPrayer: "Señor Jesús, gracias por restaurar a los que te fallan. Aquí estoy, tal como soy.",
    intro: "Después de la resurrección, Jesús se encontró con Pedro a la orilla del lago. Pedro lo había negado tres veces, y ahora Jesús le pregunta tres veces si lo ama y le encarga cuidar de sus ovejas.",
    verseRef: "Juan 21:17",
    reflection: "Jesús no humilló a Pedro ni lo descartó por su caída. Lo restauró con preguntas que sanaban y le devolvió una misión. Si le fallaste a Dios, él no te cierra la puerta; te invita a volver a amarlo y a servir.",
    closingPrayer: "Señor, vos sabés todas las cosas y sabés que te amo, aunque a veces te falle. Restaurame y usame para cuidar a otros. Amén.",
  },
  {
    day: 9,
    openingPrayer: "Dios mío, levantá mi mirada por encima de las preocupaciones de hoy.",
    intro: "Pablo escribe a los colosenses que, si han resucitado con Cristo, su vida tiene una nueva orientación. Los anima a buscar y a pensar en las cosas de arriba, donde Cristo está.",
    verseRef: "Colosenses 3:1-2",
    reflection: "Poner la mira en las cosas de arriba no es desentenderse de la vida diaria. Es mirar el trabajo, la familia y los problemas desde la perspectiva de Cristo. Cuando él está en el centro, lo urgente deja de dominarte.",
    closingPrayer: "Señor, ordená mis pensamientos alrededor de Cristo. Ayudame a vivir lo cotidiano con la mirada puesta en vos. Amén.",
  },
  {
    day: 10,
    openingPrayer: "Señor, abrí mis ojos para verte en lo sencillo de este día.",
    intro: "Dos discípulos caminaban hacia Emaús, tristes y confundidos. Un desconocido los acompañó y les explicó las Escrituras, pero solo lo reconocieron cuando partió el pan en la mesa.",
    verseRef: "Lucas 24:30-31",
    reflection: "Jesús caminó con ellos antes de que lo reconocieran. Muchas veces él está presente en nuestras conversaciones, comidas y caminos sin que lo notemos. Hoy pedile que se haga visible en lo ordinario.",
    closingPrayer: "Señor Jesús, gracias por caminar conmigo aunque no siempre te reconozca. Quedate en mi mesa y en mi casa. Amén.",
  },
  {
    day: 11,
    openingPrayer: "Dios todopoderoso, gracias porque nada puede retener lo que vos querés levantar.",
    intro: "En el día de Pentecostés, Pedro predica ante una multitud en Jerusalén. Les anuncia que Dios resucitó a Jesús, porque era imposible que la muerte lo retuviera.",
    verseRef: "Hechos 2:24",
    reflection: "Pedro habla con valentía apenas semanas después de haber negado a Jesús. La resurrección cambió su miedo en testimonio. Esa misma verdad puede darte firmeza para hablar de tu fe con sencillez y sin vergüenza.",
    closingPrayer: "Padre, gracias porque la muerte no pudo retener a tu Hijo. Dame valor para contar lo que Cristo hizo en mi vida. Amén.",
  },
  {
    day: 12,
    openingPrayer: "Señor Jesús, gracias porque tu vida sostiene la mía.",
    intro: "En la última cena, Jesús prepara a sus discípulos para su partida. Les promete que no los dejará huérfanos y les asegura que, porque él vive, ellos también vivirán.",
    verseRef: "Juan 14:19",
    reflection: "La vida del creyente está atada a la vida de Cristo. Mientras él viva, y vive para siempre, tu vida en él está segura. Esa promesa sostuvo a los discípulos en la noche más oscura y puede sostenerte hoy.",
    closingPrayer: "Señor, gracias porque Jesús vive y mi vida está escondida en él. Cuando me sienta solo, recordame que no soy huérfano. Amén.",
  },
  {
    day: 13,
    openingPrayer: "Señor, gracias por la cruz. Que hoy la mire con un corazón agradecido.",
    intro: "Pedro anima a creyentes que sufrían injusticias a mirar el ejemplo de Cristo. Les recuerda que Jesús cargó nuestros pecados en la cruz para que vivamos para la justicia, y que sus heridas trajeron nuestra sanidad.",
    verseRef: "1 Pedro 2:24",
    reflection: "La cruz no solo nos perdona; también nos libera para vivir de otra manera. Las heridas de Cristo sanan la herida más profunda, la del pecado que nos separaba de Dios. Desde ahí podés comenzar a vivir para la justicia.",
    closingPrayer: "Señor Jesús, gracias por cargar mis pecados. Que tu sacrificio me impulse a vivir para lo que es justo. Amén.",
  },
  {
    day: 14,
    openingPrayer: "Dios santo, me postro delante de vos con reverencia y confianza.",
    intro: "En la isla de Patmos, Juan tuvo una visión de Cristo glorificado y cayó como muerto a sus pies. Jesús puso su mano sobre él, le dijo que no temiera y se presentó como el que vive, que estuvo muerto y tiene las llaves de la muerte.",
    verseRef: "Apocalipsis 1:17-18",
    reflection: "El mismo Cristo glorioso que hizo temblar a Juan es el que lo tocó con ternura. Su majestad no lo aleja de los suyos. Si él tiene las llaves de la muerte, no hay puerta en tu vida que esté fuera de su autoridad.",
    closingPrayer: "Señor, gracias porque Cristo vive y tiene autoridad sobre la muerte. Quitá mis temores y dame paz bajo su mano. Amén.",
  },
  {
    day: 15,
    openingPrayer: "Dios de consuelo, traigo ante vos las lágrimas que todavía cargo.",
    intro: "Isaías describe un banquete que Dios preparará para todos los pueblos. En esa visión, el Señor destruye la muerte para siempre y enjuga las lágrimas de todos los rostros.",
    verseRef: "Isaías 25:8",
    reflection: "Dios no ignora tu dolor; promete quitarlo de raíz. La imagen de él secando lágrimas muestra un cuidado personal y tierno. Mientras esperamos ese día, podés llorar delante de él sabiendo que tus lágrimas le importan.",
    closingPrayer: "Señor, gracias porque un día no habrá más muerte ni llanto. Mientras tanto, sostené mi corazón y secá mis lágrimas. Amén.",
  },
  {
    day: 16,
    openingPrayer: "Padre, gracias porque la obra de Cristo está completa. Descanso en ella.",
    intro: "Pablo cierra su reflexión sobre la fe de Abraham hablando de Jesús. Explica que fue entregado por nuestras transgresiones y resucitado para nuestra justificación.",
    verseRef: "Romanos 4:25",
    reflection: "La cruz y la resurrección van juntas. En la cruz Cristo cargó nuestro pecado; en la resurrección Dios mostró que ese pago fue aceptado. No tenés que vivir preguntándote si alcanzó: la tumba vacía es la respuesta.",
    closingPrayer: "Señor, gracias porque Jesús murió por mis pecados y resucitó para declararme justo. Que viva en la seguridad de tu perdón. Amén.",
  },
  {
    day: 17,
    openingPrayer: "Dios rico en gracia, gracias por el perdón que me diste en Cristo.",
    intro: "Al inicio de su carta a los efesios, Pablo enumera las bendiciones que tenemos en Cristo. Una de ellas es la redención por su sangre, el perdón de pecados según las riquezas de su gracia.",
    verseRef: "Efesios 1:7",
    reflection: "El perdón de Dios no es escaso ni medido con tacañería. Es tan rico como su gracia. Si todavía cargás culpa por algo que ya confesaste, hoy podés recibir ese perdón como un regalo completo.",
    closingPrayer: "Padre, gracias por redimirme por la sangre de Cristo. Ayudame a creer que estoy perdonado y a perdonar con la misma generosidad. Amén.",
  },
  {
    day: 18,
    openingPrayer: "Señor Jesús, gracias por ser el buen pastor. Quiero seguirte hoy.",
    intro: "Jesús se presenta como el buen pastor que cuida de sus ovejas. Contrasta al ladrón, que viene a robar y destruir, con su propia venida, que es para dar vida en abundancia.",
    verseRef: "Juan 10:10",
    reflection: "La vida abundante que Jesús ofrece no se mide en cosas, sino en comunión con él. Es la vida de quien es conocido, guiado y protegido por el pastor. Aun en tiempos de escasez, podés tener esa plenitud que nadie te puede robar.",
    closingPrayer: "Señor, gracias por la vida plena que hay en vos. Guardame de lo que roba mi paz y enseñame a encontrar en vos lo que necesito. Amén.",
  },
  {
    day: 19,
    openingPrayer: "Dios de gracia, gracias porque Cristo intercede por mí aun cuando no sé orar.",
    intro: "La carta a los Hebreos presenta a Jesús como un sacerdote superior a todos los anteriores. Porque vive para siempre, puede salvar por completo a los que se acercan a Dios por medio de él.",
    verseRef: "Hebreos 7:25",
    reflection: "La obra de Cristo no terminó en la resurrección; él sigue intercediendo por los suyos. Eso significa que tu salvación no depende de lo fuerte que te sentís hoy. Cristo vive y está presentando tu causa delante del Padre.",
    closingPrayer: "Señor, gracias porque Jesús intercede por mí. Cuando mi fe se sienta débil, ayudame a descansar en su sacerdocio perfecto. Amén.",
  },
  {
    day: 20,
    openingPrayer: "Padre, vengo ante vos sin miedo a la condenación. Gracias por Cristo.",
    intro: "Pablo hace una serie de preguntas para mostrar la seguridad del creyente. Pregunta quién podrá condenar, y responde señalando a Cristo, que murió, resucitó y está a la diestra de Dios intercediendo por nosotros.",
    verseRef: "Romanos 8:34",
    reflection: "Hay voces que te acusan: la conciencia, el pasado, otras personas. Pero el único que tendría derecho a condenarte es el mismo que dio su vida por vos. En Cristo, la sentencia ya fue cambiada por gracia.",
    closingPrayer: "Señor, gracias porque en Cristo no hay condenación para mí. Silenciá las voces de acusación y llename de tu paz. Amén.",
  },
  {
    day: 21,
    openingPrayer: "Señor, gracias por invitarme a ser parte de tu misión. Enseñame a obedecer.",
    intro: "Antes de ascender, Jesús reunió a sus discípulos en un monte de Galilea. Les encargó hacer discípulos de todas las naciones y les prometió su presencia todos los días hasta el fin.",
    verseRef: "Mateo 28:19-20",
    reflection: "La gran comisión no es solo para predicadores o misioneros. Comienza en tu casa, tu trabajo y tu barrio, enseñando con palabras y con ejemplo. Y no la cumplís solo: Cristo prometió estar con los suyos cada día.",
    closingPrayer: "Señor Jesús, gracias por tu presencia que no me deja. Mostrame a quién puedo acompañar en la fe esta semana. Amén.",
  },
  {
    day: 22,
    openingPrayer: "Espíritu Santo, llename de tu poder para vivir y hablar de Cristo.",
    intro: "Justo antes de su ascensión, los discípulos le preguntaron a Jesús por el reino. Él les prometió que recibirían poder cuando viniera sobre ellos el Espíritu Santo y serían sus testigos hasta lo último de la tierra.",
    verseRef: "Hechos 1:8",
    reflection: "Ser testigo no es tener todas las respuestas, sino contar lo que has visto y vivido. El poder para hacerlo no sale de tu personalidad, sino del Espíritu Santo. Comenzá cerca, con alguien a quien ya conocés.",
    closingPrayer: "Padre, gracias por el Espíritu que capacita a tus hijos. Dame valor y sencillez para ser testigo de Cristo donde vivo. Amén.",
  },
  {
    day: 23,
    openingPrayer: "Señor, gracias por el evangelio que no cambia. Afirmame en lo esencial.",
    intro: "Pablo recuerda a los corintios el mensaje que les predicó desde el principio. Lo resume en hechos concretos: Cristo murió por nuestros pecados, fue sepultado y resucitó al tercer día, conforme a las Escrituras.",
    verseRef: "1 Corintios 15:3-4",
    reflection: "El corazón de la fe cristiana no es una teoría, sino acontecimientos que ocurrieron en la historia. Cuando las dudas o las modas te confundan, volvé a lo primero. Cristo murió, fue sepultado y resucitó, y sobre eso descansa todo.",
    closingPrayer: "Señor, gracias por la sencillez y la firmeza del evangelio. Ayudame a no perder de vista lo más importante. Amén.",
  },
  {
    day: 24,
    openingPrayer: "Dios fiel, aun en la prueba quiero declarar que confío en vos.",
    intro: "Job lo había perdido casi todo y sus amigos lo acusaban. En medio de ese dolor, expresa una convicción asombrosa: sabe que su Redentor vive y que al final se levantará.",
    verseRef: "Job 19:25",
    reflection: "La fe de Job no nació de una vida tranquila, sino del sufrimiento sin respuestas. No entendía lo que pasaba, pero se aferró a que su Redentor vive. Podés tener preguntas sin resolver y aun así sostenerte en esa certeza.",
    closingPrayer: "Señor, cuando no entienda mi situación, ayudame a confiar en que mi Redentor vive. Sostené mi fe en los días difíciles. Amén.",
  },
  {
    day: 25,
    openingPrayer: "Señor, gracias porque la tristeza no es el final de mi historia.",
    intro: "David compuso este salmo después de experimentar la ayuda de Dios en un tiempo difícil. Contrasta la brevedad del enojo de Dios con la duración de su favor, y la noche de llanto con la alegría que trae la mañana.",
    verseRef: "Salmos 30:5",
    reflection: "Algunas noches parecen eternas. Este salmo no niega el llanto, pero le pone un límite. La mañana de Dios llega, a veces de formas que no esperabas, y la resurrección de Cristo es la prueba más grande de que él convierte el luto en gozo.",
    closingPrayer: "Padre, si estoy pasando una noche larga, dame paciencia para esperar tu mañana. Gracias porque tu favor permanece. Amén.",
  },
  {
    day: 26,
    openingPrayer: "Señor Jesús, traigo mi corazón inquieto delante de vos.",
    intro: "En la noche antes de su muerte, los discípulos estaban turbados por lo que Jesús les había anunciado. Él los animó a no angustiarse y a creer en Dios y también en él.",
    verseRef: "Juan 14:1",
    reflection: "Jesús sabía que venían horas terribles, y aun así consoló a sus amigos. La respuesta a la turbación no fue una explicación completa, sino una invitación a confiar en él. Hoy podés entregarle aquello que te quita el sueño.",
    closingPrayer: "Señor, calmá mi corazón turbado. Ayudame a confiar en vos aunque no tenga todas las respuestas. Amén.",
  },
  {
    day: 27,
    openingPrayer: "Dios de luz, gracias porque en Cristo la vida venció a la muerte.",
    intro: "Desde la cárcel, Pablo escribe a Timoteo para animarlo a no avergonzarse del evangelio. Le recuerda que Cristo quitó la muerte y sacó a luz la vida y la inmortalidad.",
    verseRef: "2 Timoteo 1:10",
    reflection: "Pablo escribió esto encadenado y cerca del final de su vida. Aun así, hablaba de vida y no de derrota. Cuando la muerte y la pérdida te asusten, recordá que Cristo ya iluminó lo que hay más allá.",
    closingPrayer: "Señor, gracias porque Cristo trajo a la luz la vida eterna. Dame confianza para vivir sin miedo a la muerte. Amén.",
  },
  {
    day: 28,
    openingPrayer: "Señor Jesús, gracias porque entendés lo que es ser tentado.",
    intro: "La carta a los Hebreos insiste en que Jesús se hizo plenamente humano. Como él mismo padeció siendo tentado, puede socorrer a los que son tentados.",
    verseRef: "Hebreos 2:18",
    reflection: "Jesús no te ayuda desde lejos, como alguien que no conoce la lucha. Él enfrentó la tentación sin pecar y sabe exactamente lo que estás viviendo. Acudí a él en el momento de la prueba, no solo después de caer.",
    closingPrayer: "Señor, gracias por comprender mis luchas. Socorreme cuando sea tentado y dame fuerzas para elegir lo que te agrada. Amén.",
  },
  {
    day: 29,
    openingPrayer: "Dios de esperanza, gracias por el futuro que preparás para tu pueblo.",
    intro: "En las últimas páginas de la Biblia, Juan ve un cielo nuevo y una tierra nueva. Dios habita con su pueblo, enjuga toda lágrima, y ya no hay muerte, llanto ni dolor.",
    verseRef: "Apocalipsis 21:4",
    reflection: "La resurrección de Cristo es el comienzo de una nueva creación que un día será completa. Lo que hoy duele no durará para siempre. Esa esperanza no niega el sufrimiento presente, pero te permite atravesarlo sin perder el rumbo.",
    closingPrayer: "Señor, gracias porque un día harás nuevas todas las cosas. Mientras tanto, ayudame a vivir con esperanza y a consolar a otros. Amén.",
  },
  {
    day: 30,
    openingPrayer: "Señor Jesús, más que cualquier cosa, quiero conocerte a vos.",
    intro: "Pablo, que tenía muchos logros religiosos, declara que todo lo considera pérdida comparado con conocer a Cristo. Su deseo es conocerlo a él y el poder de su resurrección, y participar de sus padecimientos.",
    verseRef: "Filipenses 3:10",
    reflection: "Conocer a Cristo no es solo saber datos sobre él, sino caminar con él en la alegría y en el dolor. El poder de la resurrección y la comunión en el sufrimiento van juntos. Al cerrar este mes, preguntate cómo podés conocerlo más de cerca.",
    closingPrayer: "Padre, que el anhelo más grande de mi vida sea conocer a Cristo. Hacé que su vida resucitada se vea en la mía cada día. Amén.",
  },
];
