import type { DevotionalEntry } from "./types";

// Mayo — Madres y familia: el cuidado de Dios en el hogar (#199).
export const mayo: readonly DevotionalEntry[] = [
  {
    day: 1,
    openingPrayer: "Señor, pongo en tus manos mi casa y a las personas que amo.",
    intro: "Este salmo se atribuye a Salomón, el rey que construyó el templo de Jerusalén. Abre el mes recordando que cualquier casa, por bien hecha que esté, necesita que Dios sea quien la edifique.",
    verseRef: "Salmos 127:1",
    reflection: "Trabajamos mucho por nuestras familias, y eso es bueno. Pero el esfuerzo humano no basta para sostener un hogar. Invitar a Dios a ser el constructor te libra de cargar solo lo que no podés controlar.",
    closingPrayer: "Padre, edificá mi hogar sobre vos. Dame sabiduría para cuidar a los míos sin pretender hacerlo todo con mis fuerzas. Amén.",
  },
  {
    day: 2,
    openingPrayer: "Dios sabio, gracias por las mujeres que reflejan tu carácter con fortaleza y bondad.",
    intro: "El último capítulo de Proverbios describe a una mujer virtuosa. Más que una lista de tareas, es un retrato de dignidad, de serenidad ante el futuro y de palabras llenas de sabiduría y bondad.",
    verseRef: "Proverbios 31:25-26",
    reflection: "La fuerza de esta mujer no se ve en la dureza, sino en una confianza tranquila. Habla con sabiduría y enseña con bondad. Ese carácter no está reservado para las madres; es un fruto que Dios quiere formar en cada creyente.",
    closingPrayer: "Señor, vestime de dignidad y fortaleza. Que mis palabras sean sabias y amables con quienes me rodean. Amén.",
  },
  {
    day: 3,
    openingPrayer: "Señor, ayudame a valorar lo que vos valorás.",
    intro: "Al cierre del retrato de la mujer virtuosa, Proverbios contrasta lo pasajero con lo duradero. La gracia exterior y la belleza se desvanecen, pero el temor del Señor merece alabanza.",
    verseRef: "Proverbios 31:30",
    reflection: "Vivimos rodeados de mensajes sobre la apariencia y la imagen. Dios mira otra cosa: un corazón que lo reverencia. Lo que cultivás por dentro permanece cuando lo de afuera cambia con los años.",
    closingPrayer: "Padre, formá en mí un corazón que te honre. Librame de medir mi valor o el de otros por la apariencia. Amén.",
  },
  {
    day: 4,
    openingPrayer: "Dios de consuelo, vengo a vos como quien busca un abrazo.",
    intro: "Isaías habla a un pueblo herido que regresaba del exilio. Para describir cómo Dios consolará a Jerusalén, usa la imagen de una madre que consuela a su hijo.",
    verseRef: "Isaías 66:13",
    reflection: "Dios eligió una imagen materna para mostrar su ternura. Si tuviste una madre que te consoló, ahí viste un reflejo de él. Si no la tuviste, el consuelo de Dios está disponible para vos con la misma cercanía.",
    closingPrayer: "Señor, gracias por consolarme con ternura. Saná las heridas que cargo y hacé de mí alguien que consuela a otros. Amén.",
  },
  {
    day: 5,
    openingPrayer: "Señor, gracias porque nunca te olvidás de mí.",
    intro: "Sion se sentía abandonada y olvidada por Dios. Por medio de Isaías, el Señor responde comparando su amor con el de una madre que amamanta. Aun si una madre llegara a olvidar a su hijo, Dios no olvidará a su pueblo.",
    verseRef: "Isaías 49:15",
    reflection: "El amor de una madre es de los más fuertes que conocemos, y aun así puede fallar. El amor de Dios va más allá. Si alguna vez te sentiste olvidado por tu familia, Dios no te ha perdido de vista.",
    closingPrayer: "Padre, gracias porque tu amor es más fiel que cualquier amor humano. Cuando me sienta olvidado, recordame que estoy en tu memoria. Amén.",
  },
  {
    day: 6,
    openingPrayer: "Dios fiel, gracias por quienes me transmitieron la fe.",
    intro: "Pablo escribe a su joven colaborador Timoteo y recuerda su fe sincera. Menciona que esa fe habitó primero en su abuela Loida y en su madre Eunice.",
    verseRef: "2 Timoteo 1:5",
    reflection: "La fe se transmite muchas veces de forma callada: una oración en la cocina, una Biblia abierta, un ejemplo constante. Quizás vos recibiste la fe así, o quizás llegó por otro camino. En cualquier caso, hoy podés sembrarla en alguien más joven.",
    closingPrayer: "Señor, gracias por las personas que me mostraron a Cristo. Ayudame a dejar una herencia de fe sincera a quienes vienen detrás. Amén.",
  },
  {
    day: 7,
    openingPrayer: "Señor, te traigo mis anhelos más profundos. Gracias porque escuchás.",
    intro: "Ana había orado con lágrimas durante años porque no podía tener hijos. Cuando Dios le concedió a Samuel, lo llevó al templo y reconoció que ese niño era la respuesta a su oración.",
    verseRef: "1 Samuel 1:27",
    reflection: "La historia de Ana honra a quienes esperan con dolor. Ella llevó su anhelo a Dios con sinceridad, y luego entregó a él lo que había recibido. Sea cual sea tu espera hoy, podés hablarle a Dios con la misma honestidad.",
    closingPrayer: "Padre, recibí mis anhelos y mis lágrimas. Enseñame a confiar en vos mientras espero y a devolverte con gratitud lo que me das. Amén.",
  },
  {
    day: 8,
    openingPrayer: "Dios soberano, gracias porque obrás aun en los momentos más inciertos.",
    intro: "En tiempos de opresión en Egipto, la madre de Moisés escondió a su hijo y lo puso en una canasta en el río. La hija del faraón lo encontró y, sin saberlo, le pidió a la propia madre que lo criara.",
    verseRef: "Éxodo 2:9",
    reflection: "Esta madre soltó a su hijo en medio del peligro, y Dios se lo devolvió para cuidarlo. Hay momentos en que tenés que entregar a tus seres queridos a Dios sin saber qué pasará. Él sigue obrando detrás de lo que no ves.",
    closingPrayer: "Señor, pongo en tus manos a quienes amo y no puedo proteger del todo. Gracias porque tu cuidado es mayor que el mío. Amén.",
  },
  {
    day: 9,
    openingPrayer: "Señor, dame sabiduría para guiar a las nuevas generaciones.",
    intro: "Este proverbio habla sobre la formación de los niños. Anima a instruirlos en el camino correcto desde temprano, con la esperanza de que ese camino los acompañe toda la vida.",
    verseRef: "Proverbios 22:6",
    reflection: "Un proverbio es un principio de sabiduría, no una garantía mecánica. Si tus hijos se alejaron, no significa que fallaste por completo. Seguí sembrando con paciencia y orando, porque Dios sigue obrando en sus corazones.",
    closingPrayer: "Padre, ayudame a enseñar con el ejemplo y con amor. Cuidá a los niños y jóvenes de mi familia y guialos hacia vos. Amén.",
  },
  {
    day: 10,
    openingPrayer: "Señor Jesús, hoy pienso en las madres. Gracias por tu amor por ellas.",
    intro: "Desde la cruz, en medio de su sufrimiento, Jesús vio a su madre María junto al discípulo amado. Le encomendó a ese discípulo que la cuidara, y él la recibió en su casa.",
    verseRef: "Juan 19:26-27",
    reflection: "Aun en su agonía, Jesús se ocupó de su madre. Ese gesto honra a todas las madres y también a quienes cuidan como madres. Si hoy extrañás a la tuya, o este día te trae sentimientos difíciles, Jesús entiende y te acompaña.",
    closingPrayer: "Señor, bendecí a las madres y a quienes cuidan con amor de madre. Consolá a quienes hoy sienten ausencia o dolor. En el nombre de Jesús. Amén.",
  },
  {
    day: 11,
    openingPrayer: "Dios generoso, enseñame a agradecer a quienes me cuidan.",
    intro: "En Proverbios 31, la mujer virtuosa recibe el reconocimiento de su propia familia. Sus hijos se levantan y la llaman bienaventurada, y su esposo también la alaba.",
    verseRef: "Proverbios 31:28",
    reflection: "Muchas veces damos por sentado el cuidado de quienes nos aman. Una palabra de gratitud puede renovar a alguien cansado. Pensá hoy en una persona que te ha cuidado y decíselo con sencillez.",
    closingPrayer: "Señor, gracias por quienes han cuidado de mí. Dame un corazón agradecido y palabras que animen a los de mi casa. Amén.",
  },
  {
    day: 12,
    openingPrayer: "Señor, quiero creer en tus promesas aunque todavía no las vea cumplidas.",
    intro: "María, embarazada de Jesús, visitó a su pariente Elisabet. Llena del Espíritu Santo, Elisabet la bendijo y la llamó bienaventurada por haber creído lo que Dios le había dicho.",
    verseRef: "Lucas 1:45",
    reflection: "María no entendía todo, pero confió en la palabra de Dios. Su fe no eliminó las preguntas ni los riesgos. Creer es seguir adelante apoyado en lo que Dios dijo, aun cuando el camino no está claro.",
    closingPrayer: "Padre, fortalecé mi fe en tus promesas. Ayudame a confiar como María, aun cuando no entiendo todo. Amén.",
  },
  {
    day: 13,
    openingPrayer: "Dios mío, que tu Palabra esté viva en mi hogar.",
    intro: "Moisés instruye a Israel antes de entrar a la tierra prometida. Les pide guardar los mandamientos en el corazón y enseñarlos a sus hijos en la casa, en el camino, al acostarse y al levantarse.",
    verseRef: "Deuteronomio 6:6-7",
    reflection: "La fe no se transmite solo en el templo, sino en lo cotidiano. Una conversación en el bus, una oración antes de dormir, una pregunta en la mesa. Buscá hoy un momento sencillo para hablar de Dios con alguien de tu casa.",
    closingPrayer: "Señor, que tu Palabra esté primero en mi corazón. Dame naturalidad para compartirla en la vida diaria de mi familia. Amén.",
  },
  {
    day: 14,
    openingPrayer: "Señor, gracias porque ves a quienes se sienten solos o vacíos.",
    intro: "Este salmo alaba a Dios, que se inclina para mirar a los humildes. Termina celebrando que él da hogar a la mujer estéril y la hace madre gozosa de hijos.",
    verseRef: "Salmos 113:9",
    reflection: "El salmo muestra a un Dios que se fija en quienes otros pasan por alto. No todas las historias terminan con hijos biológicos, y eso no reduce el valor de nadie ante Dios. Él da hogar y familia de muchas maneras, también en su iglesia.",
    closingPrayer: "Padre, gracias porque ves mi historia con compasión. Dame un lugar de pertenencia en tu familia y hacé de mí un hogar para otros. Amén.",
  },
  {
    day: 15,
    openingPrayer: "Señor, quiero que mi casa te sirva. Ayudame a decidirlo hoy.",
    intro: "Al final de su vida, Josué reunió a Israel y les pidió elegir a quién servirían. Él declaró con firmeza que él y su casa servirían al Señor.",
    verseRef: "Josué 24:15",
    reflection: "Servir a Dios en familia comienza con una decisión personal. No podés obligar a nadie a creer, pero sí podés elegir cómo vas a vivir. Tu fidelidad diaria puede ser la semilla que otros en tu casa necesitan.",
    closingPrayer: "Señor, renuevo mi decisión de servirte. Que mi hogar sea un lugar donde se te honra con sencillez. Amén.",
  },
  {
    day: 16,
    openingPrayer: "Dios de paz, aquieto mi alma delante de vos.",
    intro: "En este breve salmo, David describe un corazón humilde y tranquilo. Lo compara con un niño destetado que descansa en brazos de su madre, ya sin exigir, solo confiando.",
    verseRef: "Salmos 131:2",
    reflection: "Un niño destetado no busca a su madre solo por lo que puede recibir, sino por estar con ella. Así podemos acercarnos a Dios: no solo con peticiones, sino buscando su presencia. Tomá un momento hoy para estar en silencio delante de él.",
    closingPrayer: "Señor, calmá mi alma inquieta. Enseñame a descansar en vos como un niño en brazos de su madre. Amén.",
  },
  {
    day: 17,
    openingPrayer: "Dios de refugio, gracias porque bajo tu cuidado encuentro protección.",
    intro: "Rut era una extranjera viuda que acompañó a su suegra Noemí hasta Belén. Booz, al conocer su lealtad, la bendijo deseando que Dios la recompensara, pues había venido a refugiarse bajo sus alas.",
    verseRef: "Rut 2:12",
    reflection: "Rut eligió la lealtad cuando hubiera sido más fácil volver atrás. Su historia muestra que la familia puede formarse también por amor y compromiso. Dios recibe a quien busca refugio en él, venga de donde venga.",
    closingPrayer: "Padre, me refugio bajo tus alas. Haceme leal con las personas que me confiaste y abrí mi corazón al que llega de lejos. Amén.",
  },
  {
    day: 18,
    openingPrayer: "Señor, dame un corazón dispuesto a aprender de quienes me aman.",
    intro: "Proverbios comienza como el consejo de un padre a su hijo. Lo anima a escuchar la instrucción del padre y a no abandonar la enseñanza de la madre.",
    verseRef: "Proverbios 1:8",
    reflection: "Escuchar consejo requiere humildad, a cualquier edad. No todos recibimos buena enseñanza en casa, pero Dios pone a otros mayores en el camino. Valorá la sabiduría que te han compartido y filtrala siempre por la Palabra.",
    closingPrayer: "Señor, dame humildad para recibir consejo. Gracias por las personas que me han enseñado con amor. Amén.",
  },
  {
    day: 19,
    openingPrayer: "Dios justo, enseñame a honrar a mi familia de una manera que te agrade.",
    intro: "Este es el quinto de los diez mandamientos. Dios ordena honrar al padre y a la madre, y es el primer mandamiento acompañado de una promesa.",
    verseRef: "Éxodo 20:12",
    reflection: "Honrar no siempre significa estar de acuerdo, ni aceptar el abuso. Significa tratar con respeto, cuidar y reconocer la dignidad de quienes nos dieron la vida o nos criaron. Para algunos esto es fácil; para otros requiere la gracia de Dios para sanar.",
    closingPrayer: "Señor, ayudame a honrar a mis padres con sabiduría. Saná lo que está herido en mi historia familiar. Amén.",
  },
  {
    day: 20,
    openingPrayer: "Padre, gracias por los niños. Enseñame a verlos como vos los ves.",
    intro: "En el mismo salmo que habla de la casa edificada por Dios, se describe a los hijos como herencia del Señor. Son presentados como un regalo y no como una posesión.",
    verseRef: "Salmos 127:3",
    reflection: "Los niños no son una carga ni un logro personal, sino un regalo confiado por Dios. Eso incluye a hijos, sobrinos, ahijados y niños de la iglesia. Cada adulto puede ser bendición para un niño que necesita atención.",
    closingPrayer: "Señor, gracias por los niños que pusiste cerca de mí. Haceme un adulto que los cuide, los escuche y les muestre tu amor. Amén.",
  },
  {
    day: 21,
    openingPrayer: "Señor Jesús, gracias por tu amor que quiere reunirnos.",
    intro: "Jesús se lamentó por Jerusalén, que rechazaba a los mensajeros de Dios. Usó la imagen de una gallina que junta a sus polluelos bajo las alas para expresar cuánto había querido reunir a su pueblo.",
    verseRef: "Mateo 23:37",
    reflection: "Jesús eligió una imagen tierna y materna para describir su deseo de proteger. Su amor no fuerza, invita. Hoy podés dejar de resistirte y acercarte a él para encontrar refugio.",
    closingPrayer: "Señor, gracias por querer cobijarme. No quiero alejarme de tu cuidado. Recibime bajo tus alas. Amén.",
  },
  {
    day: 22,
    openingPrayer: "Dios de ternura, haceme alguien que cuide a otros con delicadeza.",
    intro: "Pablo recuerda a los tesalonicenses cómo se comportó entre ellos. Dice que fue tierno, como una madre que cuida con cariño a sus propios hijos.",
    verseRef: "1 Tesalonicenses 2:7",
    reflection: "Un apóstol con autoridad eligió la ternura en lugar de imponerse. El liderazgo cristiano y el servicio en la iglesia se parecen más al cuidado de una madre que a un mando frío. Pensá a quién podés acompañar hoy con paciencia.",
    closingPrayer: "Señor, ablandá mi trato con las personas. Que sirva a otros con la ternura que vos tenés conmigo. Amén.",
  },
  {
    day: 23,
    openingPrayer: "Dios que ve, gracias porque mi vida no pasa desapercibida para vos.",
    intro: "Agar era una esclava egipcia que huyó al desierto después de ser maltratada. Allí el ángel del Señor la encontró, y ella llamó a Dios el Dios que la ve.",
    verseRef: "Génesis 16:13",
    reflection: "Agar era invisible para muchos, pero no para Dios. Él la buscó en el desierto, en su peor momento. Si hoy te sentís ignorado o maltratado, Dios te ve y conoce tu historia completa.",
    closingPrayer: "Señor, gracias porque me ves. Encontrame en mis desiertos y dame esperanza para seguir. Amén.",
  },
  {
    day: 24,
    openingPrayer: "Padre, gracias porque nunca me soltás, aun cuando otros lo hacen.",
    intro: "En el salmo 27, David expresa su confianza en Dios ante enemigos y temores. En medio de su oración, afirma que aunque su padre y su madre lo dejaran, el Señor lo recogería.",
    verseRef: "Salmos 27:10",
    reflection: "Hay personas que fueron abandonadas o heridas por su propia familia. Este versículo no minimiza ese dolor, pero ofrece una seguridad más profunda. Dios te recibe y no te deja, sin importar lo que otros hayan hecho.",
    closingPrayer: "Señor, sostené a quienes cargan heridas de abandono. Gracias porque en vos encuentro un hogar seguro. Amén.",
  },
  {
    day: 25,
    openingPrayer: "Señor, dame sabiduría para construir y no destruir.",
    intro: "Proverbios contrasta dos formas de vivir en el hogar. La mujer sabia edifica su casa, mientras que la necia la derriba con sus propias manos.",
    verseRef: "Proverbios 14:1",
    reflection: "Este principio aplica a cualquier persona en una familia. Las palabras, las actitudes y las decisiones diarias edifican o desgastan. Hoy podés elegir una acción concreta que construya paz en tu casa.",
    closingPrayer: "Padre, dame sabiduría para edificar mi hogar. Guardá mi lengua de palabras que hieren y usame para traer paz. Amén.",
  },
  {
    day: 26,
    openingPrayer: "Señor, enseñame a guardar en el corazón lo que vos hacés.",
    intro: "Después de encontrar a Jesús de doce años en el templo, sus padres regresaron con él a Nazaret. Lucas cuenta que Jesús les estaba sujeto y que María guardaba todas estas cosas en su corazón.",
    verseRef: "Lucas 2:51",
    reflection: "María no entendía todo lo que pasaba con su hijo, pero lo atesoraba y lo meditaba. Hay momentos en que no tenemos explicación, solo recuerdos y preguntas. Guardarlos delante de Dios es también una forma de fe.",
    closingPrayer: "Señor, ayudame a meditar en tus obras aunque no las entienda del todo. Que mi corazón sea un lugar donde guardo tus maravillas. Amén.",
  },
  {
    day: 27,
    openingPrayer: "Dios fiel, gracias por la fuerza para el trabajo de cada día.",
    intro: "El retrato de la mujer virtuosa incluye su diligencia en el hogar. Proverbios dice que está atenta a la marcha de su casa y no come el pan de la ociosidad.",
    verseRef: "Proverbios 31:27",
    reflection: "El trabajo de cuidar un hogar muchas veces es invisible y no recibe pago. Dios lo ve y lo valora. Si estás cansado de ese esfuerzo diario, recordá que servís también a él, y buscá ayuda y descanso cuando lo necesités.",
    closingPrayer: "Señor, gracias por la fuerza para servir a mi familia. Dame descanso cuando esté agotado y un corazón que trabaje para vos. Amén.",
  },
  {
    day: 28,
    openingPrayer: "Señor, abrí mi corazón para recibir tu Palabra.",
    intro: "En Filipos, Pablo habló a unas mujeres reunidas junto al río. Una de ellas, Lidia, vendedora de púrpura, escuchó atentamente; Dios abrió su corazón y ella fue bautizada junto con su familia.",
    verseRef: "Hechos 16:14-15",
    reflection: "La fe de Lidia comenzó con un corazón abierto por Dios y se extendió a toda su casa. Después, abrió su hogar para hospedar a los misioneros. La fe verdadera se vuelve hospitalidad y bendice a otros.",
    closingPrayer: "Padre, abrí mi corazón como el de Lidia. Que mi casa sea un lugar abierto para servir a tu pueblo. Amén.",
  },
  {
    day: 29,
    openingPrayer: "Dios de paz, formá en mí un espíritu tranquilo.",
    intro: "Pedro escribe sobre la verdadera belleza. Contrasta el adorno exterior con el interno, el de un espíritu afable y apacible, que es de gran valor delante de Dios.",
    verseRef: "1 Pedro 3:4",
    reflection: "La mansedumbre no es debilidad ni silencio forzado. Es una fortaleza tranquila que nace de confiar en Dios. Ese carácter se cultiva con tiempo, y Dios lo valora mucho más que cualquier apariencia.",
    closingPrayer: "Señor, cultivá en mí un espíritu manso y apacible. Que mi confianza en vos se note en cómo trato a los demás. Amén.",
  },
  {
    day: 30,
    openingPrayer: "Señor Jesús, gracias por tu amor por los niños.",
    intro: "Unas personas llevaban niños a Jesús para que los tocara, pero los discípulos las reprendían. Jesús se indignó, pidió que los dejaran acercarse y explicó que el reino de Dios pertenece a quienes son como ellos.",
    verseRef: "Marcos 10:14",
    reflection: "Jesús defendió a los más pequeños cuando otros los consideraban una molestia. Su reino recibe a quienes llegan con confianza sencilla. Hoy podés ayudar a que un niño se acerque a Jesús, y también acercarte vos con esa misma confianza.",
    closingPrayer: "Señor, protegé a los niños de mi familia y de mi país. Dame un corazón sencillo para confiar en vos como un niño. Amén.",
  },
  {
    day: 31,
    openingPrayer: "Dios de mi vida, gracias por sostenerme desde el principio.",
    intro: "El autor de este salmo, ya mayor, repasa su historia con Dios. Reconoce que desde el vientre de su madre fue sostenido por él, y por eso lo alaba siempre.",
    verseRef: "Salmos 71:6",
    reflection: "Antes de que pudieras conocer a Dios, él ya te sostenía. Tu historia familiar puede tener alegrías y heridas, pero Dios ha estado presente en cada capítulo. Al cerrar este mes, agradecé su fidelidad desde el principio de tu vida.",
    closingPrayer: "Señor, gracias por sostenerme desde antes de nacer. Que mi vida sea una alabanza continua a tu fidelidad. Amén.",
  },
];
