import type { DevotionalEntry } from "./types";

// Junio — Crecer en la fe: el Espíritu Santo y la paternidad de Dios (#199).
export const junio: readonly DevotionalEntry[] = [
  {
    day: 1,
    openingPrayer: "Espíritu Santo, gracias por obrar en mí. Quiero crecer este mes en tu fruto.",
    intro: "Pablo escribe a los gálatas sobre la libertad cristiana. Contrasta las obras de la carne con el fruto del Espíritu, una lista de virtudes que crecen en quien vive guiado por Dios.",
    verseRef: "Gálatas 5:22-23",
    reflection: "Es fruto, no producto de fábrica: crece con tiempo, desde adentro, como resultado de estar unido a Cristo. No se trata de esforzarte para aparentar amor o paciencia. Se trata de permanecer cerca de Dios y dejar que él haga crecer lo que solo él puede.",
    closingPrayer: "Señor, hacé crecer en mí el fruto de tu Espíritu. Que mi carácter se parezca cada día más al de Cristo. Amén.",
  },
  {
    day: 2,
    openingPrayer: "Señor, gracias por tu iglesia. Enseñame a vivir mi fe en comunidad.",
    intro: "Después de Pentecostés, miles se unieron a la iglesia en Jerusalén. Lucas describe cómo vivían: perseveraban en la enseñanza de los apóstoles, la comunión, el partimiento del pan y las oraciones.",
    verseRef: "Hechos 2:42",
    reflection: "El crecimiento espiritual no ocurre en aislamiento. La primera iglesia creció escuchando la Palabra, compartiendo la vida, recordando a Cristo en la mesa y orando juntos. Buscá hoy una manera concreta de fortalecer tu vínculo con tu congregación.",
    closingPrayer: "Padre, gracias por ponerme en una familia de fe. Ayudame a perseverar en tu Palabra, en la comunión y en la oración. Amén.",
  },
  {
    day: 3,
    openingPrayer: "Espíritu Santo, enseñame y recordame lo que Jesús enseñó.",
    intro: "En la última cena, Jesús prometió a sus discípulos que el Padre enviaría al Consolador en su nombre. Les explicó que el Espíritu Santo les enseñaría todas las cosas y les recordaría sus palabras.",
    verseRef: "Juan 14:26",
    reflection: "No estás solo cuando leés la Biblia. El Espíritu Santo es maestro y trae a la memoria la enseñanza de Jesús en el momento justo. Antes de leer hoy, pedile que te ayude a entender y a recordar.",
    closingPrayer: "Señor, gracias por el Espíritu que me enseña. Abrí mi entendimiento y traé a mi memoria tu Palabra cuando la necesite. Amén.",
  },
  {
    day: 4,
    openingPrayer: "Dios mío, a veces no sé cómo orar. Gracias porque me ayudás.",
    intro: "Pablo reconoce que en nuestra debilidad no sabemos pedir como conviene. Afirma que el Espíritu mismo nos ayuda e intercede por nosotros con gemidos que no se pueden expresar con palabras.",
    verseRef: "Romanos 8:26",
    reflection: "Hay días en que las palabras no salen, por cansancio, dolor o confusión. Eso no te aleja de Dios. El Espíritu Santo ora en vos y por vos, y presenta delante del Padre lo que no lográs decir.",
    closingPrayer: "Padre, gracias porque tu Espíritu me ayuda en mi debilidad. Recibí mis silencios y mis suspiros como oración. Amén.",
  },
  {
    day: 5,
    openingPrayer: "Señor, renovame por dentro. Quiero un corazón sensible a vos.",
    intro: "Ezequiel habla a un pueblo en el exilio, endurecido por años de desobediencia. Dios promete darles un corazón nuevo y un espíritu nuevo, cambiando el corazón de piedra por uno de carne.",
    verseRef: "Ezequiel 36:26",
    reflection: "El cambio verdadero no comienza con mejores reglas, sino con un corazón nuevo que solo Dios puede dar. Él no solo pule lo que hay; transforma desde la raíz. Si sentís que tu corazón se ha endurecido, podés pedirle que lo ablande otra vez.",
    closingPrayer: "Señor, quitá lo duro de mi corazón y dame un corazón sensible a tu voz. Gracias por tu obra de renovación. Amén.",
  },
  {
    day: 6,
    openingPrayer: "Dios todopoderoso, dependo de tu Espíritu y no de mi fuerza.",
    intro: "Zorobabel tenía la tarea de reconstruir el templo, pero los obstáculos eran enormes. Por medio del profeta Zacarías, Dios le recuerda que la obra no se logra con ejército ni con fuerza, sino con su Espíritu.",
    verseRef: "Zacarías 4:6",
    reflection: "Muchas veces queremos resolver todo con recursos, influencias o puro esfuerzo. Dios no desprecia el trabajo, pero recuerda que su obra avanza por su Espíritu. Lo que parece imposible para vos no lo es para él.",
    closingPrayer: "Señor, ante lo que me supera, ayudame a depender de tu Espíritu. Que tu obra avance en mí y por medio de mí. Amén.",
  },
  {
    day: 7,
    openingPrayer: "Abba Padre, gracias por adoptarme como tu hijo.",
    intro: "Pablo explica que quienes son guiados por el Espíritu de Dios son hijos de Dios. No recibieron un espíritu de esclavitud para vivir con temor, sino el Espíritu de adopción, por el cual llaman a Dios Padre.",
    verseRef: "Romanos 8:14-15",
    reflection: "La relación con Dios no es la de un esclavo con miedo a su amo, sino la de un hijo con su Padre. La palabra Abba expresa cercanía y confianza. Hoy podés acercarte a Dios sin temor, sabiendo que te recibe como suyo.",
    closingPrayer: "Padre, gracias por adoptarme en Cristo. Quitá de mí el temor y enseñame a vivir como tu hijo amado. Amén.",
  },
  {
    day: 8,
    openingPrayer: "Dios de los huérfanos y las viudas, gracias por tu cuidado.",
    intro: "Este salmo celebra a Dios como el que cabalga sobre los cielos. Sin embargo, en medio de su grandeza, se presenta como padre de huérfanos y defensor de viudas.",
    verseRef: "Salmos 68:5",
    reflection: "El Dios más poderoso se acerca a los más vulnerables. Si creciste sin padre o con un padre ausente, Dios quiere ser para vos lo que te faltó. Y su iglesia está llamada a reflejar ese cuidado a quienes están solos.",
    closingPrayer: "Señor, gracias por ser padre de los que no tienen padre. Saná mis heridas de ausencia y usame para cuidar a otros. Amén.",
  },
  {
    day: 9,
    openingPrayer: "Padre bueno, vengo a pedirte con confianza.",
    intro: "Jesús enseñó a sus discípulos sobre la oración. Les recordó que aun los padres imperfectos saben dar cosas buenas a sus hijos, y que el Padre celestial dará el Espíritu Santo a quienes se lo pidan.",
    verseRef: "Lucas 11:13",
    reflection: "Jesús usa la comparación con padres humanos para mostrar cuánto más generoso es Dios. El mejor regalo que ofrece no es algo material, sino su propia presencia por el Espíritu. Pedile hoy con sencillez que te llene de él.",
    closingPrayer: "Padre, gracias por tu bondad. Te pido que me llenes de tu Espíritu Santo y me guíes en todo. Amén.",
  },
  {
    day: 10,
    openingPrayer: "Señor, enseñame a criar y acompañar con amor y paciencia.",
    intro: "Pablo da instrucciones para la vida familiar en Éfeso. A los padres les pide no provocar a ira a sus hijos, sino criarlos en la disciplina y la instrucción del Señor.",
    verseRef: "Efesios 6:4",
    reflection: "La autoridad en casa no es para aplastar, sino para formar. Un trato duro o injusto puede desanimar a los hijos y alejarlos. Pedile a Dios paciencia y ternura para corregir sin herir.",
    closingPrayer: "Padre, enseñame a guiar a los niños con firmeza y amor. Perdoná mis reacciones duras y dame tu sabiduría. Amén.",
  },
  {
    day: 11,
    openingPrayer: "Dios justo, quiero caminar en integridad delante de vos y de los míos.",
    intro: "Proverbios observa que la vida de una persona íntegra deja huella en su familia. El justo que camina en integridad bendice a los hijos que vienen después de él.",
    verseRef: "Proverbios 20:7",
    reflection: "La integridad no es perfección, sino coherencia entre lo que creés y cómo vivís. Esa coherencia es un regalo que dejás a quienes te observan. Tus decisiones pequeñas de hoy enseñan más que muchas palabras.",
    closingPrayer: "Señor, ayudame a vivir con integridad cuando nadie me ve. Que mi ejemplo sea bendición para quienes vienen detrás. Amén.",
  },
  {
    day: 12,
    openingPrayer: "Señor, saná lo que está roto en mi familia.",
    intro: "El último versículo del Antiguo Testamento habla de un mensajero que Dios enviaría. Su misión incluiría reconciliar a padres e hijos, acercando de nuevo sus corazones.",
    verseRef: "Malaquías 4:6",
    reflection: "Dios se interesa por la reconciliación en las familias. Las distancias entre padres e hijos pueden ser profundas, pero no están fuera de su alcance. Orá hoy por una relación familiar que necesita restauración, y si es seguro y sabio, da un paso hacia ella.",
    closingPrayer: "Padre, volvé nuestros corazones unos hacia otros. Dame humildad para buscar la reconciliación donde sea posible. Amén.",
  },
  {
    day: 13,
    openingPrayer: "Señor, gracias porque tu corrección nace de tu amor.",
    intro: "Proverbios aconseja no despreciar la disciplina del Señor ni cansarse de su corrección. Explica que Dios corrige a quien ama, como un padre a un hijo en quien se deleita.",
    verseRef: "Proverbios 3:11-12",
    reflection: "La corrección de Dios no es castigo de alguien que te rechaza, sino cuidado de un Padre que te quiere bien. A veces llega por medio de consecuencias, consejos o la propia Palabra. Recibirla con humildad es señal de madurez.",
    closingPrayer: "Señor, cuando me corrijas, ayudame a no endurecerme. Gracias porque tu disciplina es amor. Amén.",
  },
  {
    day: 14,
    openingPrayer: "Dios de Abraham, enseñame a guiar a mi casa en tus caminos.",
    intro: "Antes de la destrucción de Sodoma, Dios revela su propósito para Abraham. Lo escogió para que mandara a sus hijos y a su casa guardar el camino del Señor, haciendo justicia y juicio.",
    verseRef: "Génesis 18:19",
    reflection: "El llamado de Abraham no era solo personal, sino familiar. Guiar a otros en el camino de Dios es parte de una vida de fe. No necesitás ser perfecto para hacerlo; necesitás caminar con Dios y abrir espacio para que otros lo conozcan.",
    closingPrayer: "Padre, ayudame a guiar a mi casa hacia vos con justicia y amor. Que mi fe se vea en lo que hago. Amén.",
  },
  {
    day: 15,
    openingPrayer: "Señor, quiero contar tus obras a la próxima generación.",
    intro: "Asaf introduce un largo salmo que repasa la historia de Israel. Se propone no esconder a los hijos las alabanzas del Señor, su poder y las maravillas que hizo.",
    verseRef: "Salmos 78:4",
    reflection: "Contar lo que Dios ha hecho es una forma de sembrar fe. Tus testimonios, aun los sencillos, pueden fortalecer a los más jóvenes. Pensá hoy en una historia de la fidelidad de Dios que podés compartir.",
    closingPrayer: "Señor, no quiero callar tus maravillas. Dame oportunidades para contar tu fidelidad a los que vienen detrás. Amén.",
  },
  {
    day: 16,
    openingPrayer: "Dios fuerte, dame firmeza en la fe y amor en mi trato.",
    intro: "Al cerrar su carta a los corintios, Pablo da instrucciones breves. Los anima a velar, a estar firmes en la fe, a portarse con valentía y a ser fuertes, haciendo todo con amor.",
    verseRef: "1 Corintios 16:13",
    reflection: "La firmeza cristiana no es dureza. Pablo une la valentía con el amor en la misma exhortación. Estar firme en la fe significa no ceder ante lo que contradice a Cristo, sin perder la ternura con las personas.",
    closingPrayer: "Señor, haceme firme en tu verdad y amable con todos. Dame valor sin orgullo y fuerza sin dureza. Amén.",
  },
  {
    day: 17,
    openingPrayer: "Señor, examiná mi corazón. Quiero servirte de verdad.",
    intro: "Ya anciano, David entrega a Salomón la tarea de construir el templo. Le aconseja conocer al Dios de su padre y servirle con corazón íntegro y ánimo voluntario, porque el Señor escudriña los corazones.",
    verseRef: "1 Crónicas 28:9",
    reflection: "David no le dejó a su hijo solo un proyecto, sino un consejo espiritual. Conocer a Dios personalmente es más importante que cualquier tarea. La fe heredada tiene que volverse fe propia.",
    closingPrayer: "Padre, quiero conocerte personalmente y no solo por lo que otros me contaron. Dame un corazón íntegro para servirte. Amén.",
  },
  {
    day: 18,
    openingPrayer: "Dios de gozo, gracias por las alegrías que trae la familia.",
    intro: "Proverbios describe la alegría de un padre cuando su hijo camina en justicia y sabiduría. Quien engendra un hijo sabio se goza en él.",
    verseRef: "Proverbios 23:24",
    reflection: "Hay una alegría especial en ver a otros crecer en sabiduría. Si sos padre o madre, mentor o maestro, esa alegría es un regalo de Dios. Y si sos hijo, tu caminar con Dios también puede alegrar el corazón de quienes te formaron.",
    closingPrayer: "Señor, gracias por la alegría de ver a otros crecer en tus caminos. Ayudame a ser fuente de gozo para mi familia. Amén.",
  },
  {
    day: 19,
    openingPrayer: "Padre nuestro, gracias porque podemos acercarnos a vos juntos.",
    intro: "Jesús enseñó a sus discípulos un modelo de oración. Comienza llamando a Dios Padre nuestro, que está en los cielos, y pidiendo que su nombre sea santificado.",
    verseRef: "Mateo 6:9",
    reflection: "La oración de Jesús empieza con una relación: Dios es Padre, y es nuestro, no solo mío. Esa palabra nos une a toda la familia de la fe. Antes de pedir, la oración pone a Dios en el centro y honra su nombre.",
    closingPrayer: "Padre, que tu nombre sea honrado en mi vida. Gracias porque puedo llamarte Padre junto con tus hijos. Amén.",
  },
  {
    day: 20,
    openingPrayer: "Dios de amor, gracias porque me llamás tu hijo.",
    intro: "Juan escribe asombrado del amor del Padre. Se maravilla de que Dios nos haya dado el nombre de hijos suyos, y afirma que eso es lo que realmente somos.",
    verseRef: "1 Juan 3:1",
    reflection: "Ser hijo de Dios no es un título vacío; es tu identidad más profunda. No depende de tu desempeño ni de cómo te vean otros. Cuando dudes de tu valor, volvé a esta verdad: el Padre te ama y te llama suyo.",
    closingPrayer: "Padre, gracias por tu amor que me hace tu hijo. Que esta identidad sostenga mi corazón hoy. Amén.",
  },
  {
    day: 21,
    openingPrayer: "Señor, confío en que vos proveés lo que realmente necesito.",
    intro: "Abraham subía al monte Moriah con su hijo Isaac. Cuando Isaac preguntó por el animal para el sacrificio, Abraham le respondió con una confianza firme en la provisión de Dios.",
    verseRef: "Génesis 22:8",
    reflection: "Abraham no tenía todas las respuestas, pero confiaba en que Dios proveería. Siglos después, Dios proveyó el Cordero definitivo en Jesús. Tu necesidad más profunda, la de reconciliación con Dios, ya fue suplida en Cristo.",
    closingPrayer: "Padre, gracias por proveer a Jesús como el Cordero. Ayudame a confiar en vos cuando no veo el camino. Amén.",
  },
  {
    day: 22,
    openingPrayer: "Señor, me pongo en tus manos. Formame según tu voluntad.",
    intro: "Isaías ora en nombre de un pueblo que reconoce su pecado. En medio de esa confesión, declara que Dios es su Padre, que ellos son barro y él es el alfarero.",
    verseRef: "Isaías 64:8",
    reflection: "El barro no se forma solo; necesita las manos del alfarero. Dios no te desecha por tus imperfecciones, sino que sigue trabajando en vos con paciencia. Entregate hoy a su obra, aunque el proceso sea lento.",
    closingPrayer: "Padre, soy barro en tus manos. Moldeame con paciencia y hacé de mí lo que vos querés. Amén.",
  },
  {
    day: 23,
    openingPrayer: "Señor, ayudame a ver tu propósito en los procesos difíciles.",
    intro: "La carta a los Hebreos anima a creyentes cansados por las pruebas. Reconoce que ninguna disciplina parece agradable en el momento, pero después da un fruto apacible de justicia.",
    verseRef: "Hebreos 12:11",
    reflection: "Las temporadas difíciles no son agradables, y la Biblia no lo niega. Pero Dios usa esos procesos para formar en nosotros un carácter más parecido a Cristo. El fruto no se ve de inmediato; llega después, con paz.",
    closingPrayer: "Padre, sostené mi fe en los procesos difíciles. Que de ellos salga el fruto de justicia y paz que vos querés. Amén.",
  },
  {
    day: 24,
    openingPrayer: "Señor, guiá mis pasos hoy. Confío en tu dirección.",
    intro: "David, ya mayor, reflexiona sobre la vida del justo. Afirma que Dios guía el andar de quien confía en él y se agrada de su camino.",
    verseRef: "Salmos 37:23",
    reflection: "Dios se interesa por tu camino, paso a paso. No necesitás conocer el plan completo para avanzar con confianza. Incluso cuando tropezás, él sostiene tu mano y te ayuda a seguir.",
    closingPrayer: "Señor, ordená mis pasos según tu voluntad. Gracias porque te interesás por mi camino. Amén.",
  },
  {
    day: 25,
    openingPrayer: "Dios, gracias por las personas que me ayudan a crecer.",
    intro: "Proverbios usa una imagen del trabajo diario. Compara la amistad con dos piezas de hierro que se afilan mutuamente al rozarse.",
    verseRef: "Proverbios 27:17",
    reflection: "El crecimiento espiritual necesita amistades que nos animen y nos confronten con amor. A veces el roce incomoda, pero nos afina. Buscá relaciones que te acerquen a Cristo y sé ese tipo de amigo para alguien más.",
    closingPrayer: "Señor, gracias por los amigos que me afilan. Ayudame a ser una presencia que anima y edifica a otros. Amén.",
  },
  {
    day: 26,
    openingPrayer: "Dios de paz, enseñame a convivir con humildad y paciencia.",
    intro: "Pablo exhorta a los efesios a vivir de manera digna de su llamado. Les pide humildad, mansedumbre y paciencia, soportándose con amor y cuidando la unidad del Espíritu.",
    verseRef: "Efesios 4:2-3",
    reflection: "La unidad no es automática; requiere esfuerzo diligente. En la familia y en la iglesia, convivir implica soportar con amor las diferencias. El Espíritu da la unidad, y nosotros la cuidamos con actitudes concretas.",
    closingPrayer: "Señor, dame humildad y paciencia con quienes me rodean. Ayudame a guardar la unidad con amor. Amén.",
  },
  {
    day: 27,
    openingPrayer: "Señor Jesús, quiero permanecer en tu amor.",
    intro: "En el discurso de la vid y los pámpanos, Jesús habla del amor que los une. Explica que así como el Padre lo amó a él, él amó a sus discípulos, y los invita a permanecer en ese amor.",
    verseRef: "Juan 15:9",
    reflection: "El amor de Jesús por vos tiene la misma calidad que el amor del Padre por él. Permanecer en ese amor es la fuente del fruto espiritual. No se trata de producir más, sino de quedarte cerca de él.",
    closingPrayer: "Señor, gracias por amarme así. Ayudame a permanecer en tu amor en cada momento de este día. Amén.",
  },
  {
    day: 28,
    openingPrayer: "Dios fiel, gracias porque no abandonás lo que empezaste en mí.",
    intro: "Desde la cárcel, Pablo escribe a los filipenses con gratitud. Expresa su seguridad de que Dios terminará la obra buena que inició en ellos, hasta el regreso de Cristo.",
    verseRef: "Filipenses 1:6",
    reflection: "Tu crecimiento espiritual no depende solo de tu constancia. Dios comenzó la obra y se comprometió a terminarla. Cuando te sentís estancado, podés descansar en que él sigue trabajando.",
    closingPrayer: "Padre, gracias porque terminás lo que empezás. Dame paciencia conmigo mismo y confianza en tu obra. Amén.",
  },
  {
    day: 29,
    openingPrayer: "Señor, quiero conocerte más cada día.",
    intro: "Al final de su segunda carta, Pedro anima a los creyentes a mantenerse firmes ante falsas enseñanzas. Su consejo final es crecer en la gracia y en el conocimiento de Jesucristo.",
    verseRef: "2 Pedro 3:18",
    reflection: "Crecer en gracia significa depender cada vez más del favor inmerecido de Dios. Crecer en conocimiento es conocer más a Cristo por medio de su Palabra. Las dos cosas van juntas y nos protegen del error.",
    closingPrayer: "Señor, hacé que crezca en tu gracia y en el conocimiento de Cristo. Que toda la gloria sea para él. Amén.",
  },
  {
    day: 30,
    openingPrayer: "Dios eterno, gracias porque en vos puedo dar fruto en toda etapa.",
    intro: "El salmo 92 es un cántico para el día de reposo. Compara al justo con la palmera y con el cedro del Líbano, árboles firmes que crecen y dan fruto.",
    verseRef: "Salmos 92:12",
    reflection: "La palmera resiste el viento y el cedro crece alto y fuerte. Así puede ser la vida de quien está plantado en Dios. Al cerrar este mes, agradecé el crecimiento que él ha dado y confiá en que seguirá obrando en vos.",
    closingPrayer: "Señor, plantame firme en vos para crecer y dar fruto. Gracias por tu obra en mi vida este mes. Amén.",
  },
];
