import type { DevotionalEntry } from "./types";

// Julio — Mitad de año: descanso, perseverancia y Dios en la dificultad (#199).
export const julio: readonly DevotionalEntry[] = [
  {
    day: 1,
    openingPrayer: "Señor, llego a la mitad del año con algo de cansancio. Gracias porque puedo empezar este mes a tus pies.",
    intro: "Jesús hablaba a gente agotada por cargas religiosas y por el peso de la vida diaria. En medio de su enseñanza hizo una invitación abierta a todos los que estaban cansados y agobiados.",
    verseRef: "Mateo 11:28",
    reflection: "La invitación de Jesús no exige que primero te ordenés o te pongás fuerte. Él recibe a los cansados tal como llegan. Antes de planear la segunda mitad del año, acercate a él y dejá que te dé el descanso que no encontrás en otro lado.",
    closingPrayer: "Señor Jesús, acepto tu invitación. Recibí mis cargas y enseñame a descansar en vos durante este mes. Amén.",
  },
  {
    day: 2,
    openingPrayer: "Dios de paz, al comenzar este día te entrego lo que me quitó el sueño anoche.",
    intro: "David escribió este salmo en un tiempo de presión y de voces en su contra. Aun así, cierra con una declaración de confianza: puede acostarse y dormir porque el Señor lo guarda.",
    verseRef: "Salmos 4:8",
    reflection: "Dormir en paz es un acto de confianza: soltás el control por unas horas y reconocés que Dios sigue despierto. No significa que los problemas desaparecieron, sino que no dependen solo de vos. Esta noche podés acostarte entregándole lo que quedó pendiente.",
    closingPrayer: "Padre, gracias porque vos velás cuando yo no puedo. Dame un descanso tranquilo esta noche y confianza para dejar en tus manos lo que no resolví. Amén.",
  },
  {
    day: 3,
    openingPrayer: "Señor Jesús, gracias porque te importa mi descanso tanto como mi trabajo.",
    intro: "Los discípulos regresaban de una misión intensa, y era tanta la gente que ni tiempo tenían para comer. Jesús, al verlos, los invitó a apartarse a un lugar tranquilo para descansar un poco.",
    verseRef: "Marcos 6:31",
    reflection: "Jesús no aplaudió el agotamiento de sus discípulos; los llevó aparte. Descansar no es pereza ni falta de compromiso, es parte de una vida sana delante de Dios. Buscá hoy un momento quieto, aunque sea corto, para estar con él sin prisa.",
    closingPrayer: "Señor, enseñame a apartarme con vos cuando estoy cansado. Librame de la culpa por descansar y dame sabiduría para cuidar mis fuerzas. Amén.",
  },
  {
    day: 4,
    openingPrayer: "Dios eterno, vos no te cansás ni te fatigás. Renová hoy mis fuerzas.",
    intro: "Isaías habla a un pueblo desanimado que sentía que Dios lo había olvidado. Les recuerda que el Señor es Creador incansable y que da fuerzas a quienes esperan en él.",
    verseRef: "Isaías 40:31",
    reflection: "Esperar en Dios no es quedarse de brazos cruzados, sino apoyarse en él mientras seguís caminando. Hay días para volar, días para correr y días en que solo podés caminar; en todos ellos él sostiene. Tu fuerza no se mide por cuánto aguantás, sino por en quién confiás.",
    closingPrayer: "Señor, renová mis fuerzas donde me siento agotado. Ayudame a esperar en vos con paciencia y a seguir caminando un paso a la vez. Amén.",
  },
  {
    day: 5,
    openingPrayer: "Señor, aquieto mi alma delante de vos. Quiero escucharte antes que a mis preocupaciones.",
    intro: "David escribió este salmo rodeado de personas que querían derribarlo. En lugar de defenderse con desesperación, describe un alma que reposa en silencio delante de Dios, de quien viene su salvación.",
    verseRef: "Salmos 62:1",
    reflection: "El silencio delante de Dios no es vacío; es confianza. Cuando callás tus quejas y tus cálculos por un momento, recordás que tu salvación no depende de tu ruido. Tomá unos minutos hoy para estar quieto ante él, sin pedir nada, solo descansando.",
    closingPrayer: "Padre, calmá el ruido de mi mente. Que mi alma aprenda a reposar en vos y no en mis propias soluciones. En el nombre de Jesús. Amén.",
  },
  {
    day: 6,
    openingPrayer: "Dios fiel, no quiero dar un paso sin tu compañía. Andá conmigo hoy.",
    intro: "Después de que el pueblo falló gravemente en el desierto, Moisés intercedió y le rogó a Dios que no los dejara. El Señor le prometió que su presencia iría con él y le daría descanso.",
    verseRef: "Éxodo 33:14",
    reflection: "Moisés entendía que sin la presencia de Dios el viaje no tenía sentido. El verdadero descanso no viene de llegar a un lugar ideal, sino de saber que Dios camina con nosotros. Cualquiera que sea tu desierto en este tiempo, no lo cruzás solo.",
    closingPrayer: "Señor, gracias por tu presencia que acompaña. Que tu compañía sea mi descanso en medio del camino que estoy recorriendo. Amén.",
  },
  {
    day: 7,
    openingPrayer: "Padre, gracias porque puedo acercarme a vos sin miedo, por medio de Jesús.",
    intro: "La carta a los Hebreos presenta a Jesús como el gran sumo sacerdote que entiende nuestras debilidades. Por eso anima a los creyentes a acercarse con confianza al trono de la gracia.",
    verseRef: "Hebreos 4:16",
    reflection: "No tenés que esperar a sentirte digno para orar. El trono de Dios es llamado trono de gracia, y allí se encuentra ayuda en el momento oportuno. Si hoy estás en necesidad, ese es justamente el momento para acercarte.",
    closingPrayer: "Señor, me acerco con confianza porque Jesús abrió el camino. Dame la gracia y la ayuda que necesito para este día. Amén.",
  },
  {
    day: 8,
    openingPrayer: "Señor, hay cargas que llevo desde hace tiempo. Hoy quiero ponerlas en tus manos.",
    intro: "Este salmo nace del dolor de David al ser traicionado por alguien cercano. En medio de esa angustia, invita a echar la carga sobre el Señor, quien sostiene al justo.",
    verseRef: "Salmos 55:22",
    reflection: "David no negó su dolor; lo dijo con honestidad y luego lo entregó. Echar la carga sobre Dios es un acto concreto: nombrar lo que te pesa y soltarlo en oración. Él no promete quitar todo problema, pero sí sostenerte para que no caigas.",
    closingPrayer: "Padre, te entrego esta carga que no puedo llevar solo. Sosteneme cuando me sienta débil y dame paz para seguir. Amén.",
  },
  {
    day: 9,
    openingPrayer: "Dios de amor, gracias porque mis preocupaciones te importan.",
    intro: "Pedro escribe a creyentes que sufrían por su fe y vivían dispersos lejos de casa. Les enseña a ser humildes ante Dios y a echar sobre él toda su ansiedad, porque él cuida de ellos.",
    verseRef: "1 Pedro 5:7",
    reflection: "La razón para entregar tu ansiedad no es una técnica, sino una persona: Dios cuida de vos. No hay preocupación demasiado pequeña ni demasiado grande para traérsela. Hacé hoy una lista de lo que te inquieta y entregala, una por una, en oración.",
    closingPrayer: "Señor, gracias porque cuidás de mí. Te entrego mis ansiedades y te pido que guardés mi corazón en tu cuidado. Amén.",
  },
  {
    day: 10,
    openingPrayer: "Señor, antes de preocuparme, quiero aprender a orar.",
    intro: "Pablo escribe a los filipenses desde la cárcel, con un futuro incierto. Aun así, los anima a presentar sus peticiones a Dios con gratitud, y les asegura que la paz de Dios guardará sus corazones.",
    verseRef: "Filipenses 4:6-7",
    reflection: "Pablo no ofrece una vida sin problemas, sino un camino para enfrentarlos: oración con gratitud. La paz de Dios no siempre llega como una explicación; llega como un guardián que cuida tu corazón y tus pensamientos. Convertí hoy cada preocupación en una petición.",
    closingPrayer: "Padre, te presento mis necesidades con gratitud por lo que ya hiciste. Que tu paz guarde mi corazón y mi mente en Cristo Jesús. Amén.",
  },
  {
    day: 11,
    openingPrayer: "Dios fiel, ayudame a vivir el día de hoy sin cargar el de mañana.",
    intro: "En el Sermón del Monte, Jesús habla de las aves y de los lirios para mostrar el cuidado del Padre. Termina esa enseñanza recordando que cada día trae su propio afán.",
    verseRef: "Mateo 6:34",
    reflection: "Jesús no prohíbe planear; nos libra de vivir angustiados por lo que todavía no llegó. Las fuerzas de hoy son para hoy, y la gracia de mañana llegará mañana. Enfocate en lo que te toca hacer este día y confiá el resto al Padre.",
    closingPrayer: "Señor, te entrego el mañana que tanto me preocupa. Dame fidelidad para lo que tengo enfrente hoy y confianza en tu cuidado. Amén.",
  },
  {
    day: 12,
    openingPrayer: "Señor, levanto mis ojos hacia vos. Sé mi ayuda en este día.",
    intro: "Este salmo era cantado por los peregrinos que subían a Jerusalén por caminos de montaña. Al mirar los montes, el caminante se pregunta de dónde vendrá su ayuda y responde que viene del Señor.",
    verseRef: "Salmos 121:1-2",
    reflection: "Los montes podían esconder peligros, pero también recordaban la grandeza del Creador. Tu ayuda no viene de las circunstancias ni de las personas, sino de quien hizo los cielos y la tierra. Si hoy el camino es cuesta arriba, levantá la mirada hacia él.",
    closingPrayer: "Padre, mi ayuda viene de vos. Guardá mis pasos en el camino de hoy y recordame que no camino solo. Amén.",
  },
  {
    day: 13,
    openingPrayer: "Dios de paz, quiero fijar mis pensamientos en vos y no en mis temores.",
    intro: "Isaías presenta un cántico de confianza para el pueblo de Dios. Allí afirma que Dios guarda en paz a quien fija su mente en él con confianza.",
    verseRef: "Isaías 26:3",
    reflection: "La mente tiende a dar vueltas sobre lo que podría salir mal. La paz que describe Isaías nace de dirigir el pensamiento hacia Dios una y otra vez. Cada vez que notés que la ansiedad te arrastra, volvé con calma tu atención a su fidelidad.",
    closingPrayer: "Señor, afirmá mi mente en vos. Guardame en tu paz cuando mis pensamientos se inquieten. Amén.",
  },
  {
    day: 14,
    openingPrayer: "Señor Jesús, gracias porque ya venciste. Quiero vivir hoy con ánimo.",
    intro: "Jesús habló estas palabras a sus discípulos la noche antes de su crucifixión. Sabía que vendrían tiempos difíciles, y por eso les anunció que en él tendrían paz, porque él había vencido al mundo.",
    verseRef: "Juan 16:33",
    reflection: "Jesús fue honesto: en este mundo habrá aflicción. Pero no dejó a sus discípulos con esa noticia; les dio una razón para tener ánimo. La victoria de Cristo no elimina todas tus luchas, pero sí define cómo terminan.",
    closingPrayer: "Señor, gracias porque tu victoria es más grande que mis aflicciones. Dame paz en vos y ánimo para enfrentar este día. Amén.",
  },
  {
    day: 15,
    openingPrayer: "Padre, hoy me siento débil. Gracias porque tu gracia es suficiente.",
    intro: "Pablo cuenta que tenía un aguijón en la carne y que pidió tres veces a Dios que se lo quitara. La respuesta del Señor no fue quitarlo, sino asegurarle que su gracia era suficiente y que su poder se mostraría en esa debilidad.",
    verseRef: "2 Corintios 12:9",
    reflection: "No todas las oraciones reciben la respuesta que esperamos, pero ninguna queda sin respuesta. Pablo aprendió que su debilidad era el lugar donde se veía el poder de Cristo. Lo que hoy te hace sentir limitado puede ser el espacio donde Dios muestre su gracia.",
    closingPrayer: "Señor, ayudame a aceptar tu gracia cuando no recibo lo que pido. Que tu poder se muestre en mis debilidades. Amén.",
  },
  {
    day: 16,
    openingPrayer: "Dios fuerte, sos mi refugio. Hoy me escondo en vos.",
    intro: "David compuso este salmo después de que Dios lo libró de sus enemigos y de la mano de Saúl. Usa imágenes de guerra y de montaña para describir al Señor: roca, fortaleza, escudo y libertador.",
    verseRef: "Salmos 18:2",
    reflection: "David acumula nombres para Dios porque uno solo no le alcanzaba para expresar su experiencia. Cada imagen habla de protección firme cuando todo alrededor es inestable. Pensá hoy cuál de esas imágenes necesitás más y descansá en ella.",
    closingPrayer: "Señor, sos mi roca y mi fortaleza. Cuando me sienta expuesto, recordame que en vos estoy seguro. Amén.",
  },
  {
    day: 17,
    openingPrayer: "Señor, renová mis ganas de hacer el bien aunque no vea resultados.",
    intro: "Pablo cierra su carta a los gálatas con consejos prácticos sobre la vida en comunidad. Los anima a no cansarse de hacer el bien, porque a su tiempo cosecharán si no desmayan.",
    verseRef: "Gálatas 6:9",
    reflection: "Hacer el bien cansa, sobre todo cuando parece que nadie lo nota. Pablo habla de una cosecha que llega a su tiempo, no al nuestro. Seguí sembrando con fidelidad; Dios ve lo que otros no ven.",
    closingPrayer: "Padre, cuando me canse de hacer el bien, dame paciencia. Ayudame a confiar en tu tiempo para la cosecha. Amén.",
  },
  {
    day: 18,
    openingPrayer: "Dios sabio, enseñame a mirar mis pruebas con tus ojos.",
    intro: "Santiago escribe a creyentes dispersos que enfrentaban diversas pruebas. Desde el inicio de su carta les enseña que la prueba de la fe produce paciencia.",
    verseRef: "Santiago 1:2-3",
    reflection: "Santiago no dice que la prueba sea agradable, sino que tiene un propósito. El gozo del que habla no niega el dolor; nace de saber que Dios está formando algo firme en vos. Preguntale hoy qué quiere hacer crecer en tu vida a través de esta situación.",
    closingPrayer: "Señor, no entiendo todo lo que estoy pasando, pero confío en que obrás en medio de ello. Formá en mí una fe paciente. Amén.",
  },
  {
    day: 19,
    openingPrayer: "Padre, gracias porque nada de lo que vivo queda fuera de tu propósito.",
    intro: "Pablo explica a los romanos los frutos de haber sido justificados por la fe. Entre ellos menciona algo sorprendente: aun las tribulaciones producen paciencia, carácter probado y esperanza.",
    verseRef: "Romanos 5:3-4",
    reflection: "Pablo describe una cadena que Dios va formando con el tiempo. La paciencia no aparece de un día para otro, y el carácter se prueba en lo difícil. Al final de esa cadena hay esperanza, una esperanza que se apoya en el amor de Dios y no en las circunstancias.",
    closingPrayer: "Señor, usá mis tribulaciones para formar paciencia y carácter en mí. Guardá viva mi esperanza en vos. En el nombre de Jesús. Amén.",
  },
  {
    day: 20,
    openingPrayer: "Señor, quiero echar raíces profundas en vos.",
    intro: "Jeremías contrasta dos maneras de vivir: confiar en el ser humano o confiar en el Señor. Quien confía en Dios es como un árbol plantado junto a las aguas, que no teme cuando llega el calor.",
    verseRef: "Jeremías 17:7-8",
    reflection: "El árbol junto al río también enfrenta el calor y la sequía; la diferencia está en sus raíces. Las temporadas difíciles llegan para todos, pero quien está arraigado en Dios sigue teniendo de dónde beber. Cuidá hoy tus raíces: oración, Palabra y comunidad.",
    closingPrayer: "Padre, plantá mi vida junto a tus aguas. Que en tiempos secos siga confiando y dando fruto. Amén.",
  },
  {
    day: 21,
    openingPrayer: "Dios altísimo, busco tu sombra y tu abrigo en este día.",
    intro: "El salmo 91 es una canción de confianza para quien vive cerca de Dios. Comienza describiendo a quien vive bajo el cuidado del Altísimo y lo reconoce como su refugio seguro.",
    verseRef: "Salmos 91:1-2",
    reflection: "Habitar es más que visitar de vez en cuando; es quedarse. La protección que describe este salmo está ligada a una relación cercana y constante con Dios. Hoy podés elegir vivir bajo su sombra en cada momento, no solo cuando llega la emergencia.",
    closingPrayer: "Señor, sos mi refugio y mi castillo. Enseñame a habitar cerca de vos cada día. Amén.",
  },
  {
    day: 22,
    openingPrayer: "Señor, gracias porque sos bueno aun cuando el día es difícil.",
    intro: "Nahúm anuncia el juicio de Dios contra Nínive, una potencia cruel de su tiempo. En medio de ese mensaje recuerda que el Señor es bueno, fortaleza en el día de la angustia, y que conoce a los que en él confían.",
    verseRef: "Nahúm 1:7",
    reflection: "Dios no es indiferente al mal ni a quienes sufren por él. Su bondad se vuelve refugio concreto en el día de la angustia. Y hay algo más: él conoce a los que confían en él, no sos un nombre perdido en la multitud.",
    closingPrayer: "Padre, gracias porque sos mi fortaleza en la angustia y me conocés. Ayudame a confiar en tu bondad hoy. Amén.",
  },
  {
    day: 23,
    openingPrayer: "Dios fiel, gracias porque no me dejás solo en la tentación.",
    intro: "Pablo recuerda a los corintios las caídas del pueblo de Israel en el desierto como advertencia. Luego les da una palabra de ánimo: Dios es fiel y con la prueba dará también la salida.",
    verseRef: "1 Corintios 10:13",
    reflection: "Tus luchas no son únicas ni extrañas; otros las han enfrentado antes. Y Dios no te deja a merced de ellas: es fiel y provee una salida. Pedile hoy que te muestre esa salida y valor para tomarla.",
    closingPrayer: "Señor, gracias por tu fidelidad en mis tentaciones. Abrí mis ojos para ver la salida y dame fuerza para elegirla. Amén.",
  },
  {
    day: 24,
    openingPrayer: "Señor, en medio de las aguas profundas, quiero sentir tu compañía.",
    intro: "Isaías habla a un pueblo que pasaría por el exilio y la pérdida. Dios les recuerda que los formó y los redimió, y les promete estar con ellos cuando pasen por las aguas y por el fuego.",
    verseRef: "Isaías 43:2",
    reflection: "La promesa no es que nunca pasarás por aguas o fuego, sino que no pasarás solo. Dios no siempre nos evita la dificultad, pero sí nos acompaña dentro de ella. Si hoy sentís que el agua te llega al cuello, recordá quién camina a tu lado.",
    closingPrayer: "Padre, gracias porque estás conmigo en las aguas y en el fuego. Sosteneme y no permitás que me arrastre la corriente. Amén.",
  },
  {
    day: 25,
    openingPrayer: "Dios de esperanza, hoy mi alma está abatida. Vengo a vos con honestidad.",
    intro: "El autor de este salmo se siente lejos de Dios y extraña los tiempos de adoración con su pueblo. En medio de la tristeza se habla a sí mismo y se anima a esperar en Dios.",
    verseRef: "Salmos 42:11",
    reflection: "El salmista no esconde su tristeza, pero tampoco la deja tener la última palabra. Se pregunta por qué se abate su alma y se recuerda a quién puede seguir alabando. Está bien estar triste delante de Dios; él escucha también esas oraciones.",
    closingPrayer: "Señor, mi alma está cansada, pero espero en vos. Levantá mi ánimo y dame motivos para volver a alabarte. Amén.",
  },
  {
    day: 26,
    openingPrayer: "Señor, gracias porque aunque me golpeen las circunstancias, no me dejás caer del todo.",
    intro: "Pablo describe a los corintios las dificultades de su ministerio. Usa una serie de contrastes para mostrar que, aunque eran presionados y golpeados, nunca quedaron abandonados ni vencidos.",
    verseRef: "2 Corintios 4:8-9",
    reflection: "Pablo no pinta una vida cristiana sin golpes. Pero en cada frase hay un límite que la dificultad no logra cruzar, porque el poder viene de Dios. Puede que hoy te sintás derribado; eso no significa que estés destruido.",
    closingPrayer: "Padre, cuando me sienta acorralado, recordame que no estoy desamparado. Sosteneme con tu poder. Amén.",
  },
  {
    day: 27,
    openingPrayer: "Dios fiel, gracias porque tu presencia no depende de lo que tengo.",
    intro: "La carta a los Hebreos termina con exhortaciones prácticas para la vida cristiana. Una de ellas invita a vivir sin amor al dinero y contentos con lo que se tiene, porque Dios prometió no dejarnos.",
    verseRef: "Hebreos 13:5",
    reflection: "El contentamiento no nace de tener suficiente, sino de saber que Dios no nos abandona. Cuando la seguridad descansa en él, las cosas pierden su poder de dominarnos. Agradecé hoy por lo que tenés y por su compañía, que vale más.",
    closingPrayer: "Señor, librame del afán por tener más. Enseñame a estar contento sabiendo que nunca me dejás. Amén.",
  },
  {
    day: 28,
    openingPrayer: "Señor, gracias porque estás cerca. Te invoco con sinceridad.",
    intro: "David cierra varios de sus salmos con alabanza, y este es un himno a la grandeza y la bondad de Dios. Allí afirma que el Señor está cerca de todos los que lo invocan de veras.",
    verseRef: "Salmos 145:18",
    reflection: "Dios no está lejos esperando que lo alcancemos con palabras perfectas. Está cerca de quien lo invoca con verdad, aunque sea con una oración torpe. Hablale hoy con sinceridad, tal como estás.",
    closingPrayer: "Padre, gracias por estar cerca de mí. Que mi oración sea sincera y mi corazón esté abierto a vos. Amén.",
  },
  {
    day: 29,
    openingPrayer: "Señor Jesús, recibo la paz que vos das. Calmá mi corazón.",
    intro: "En la última cena, Jesús preparó a sus discípulos para su partida. Les dejó como herencia su paz, distinta de la que ofrece el mundo, y los animó a no vivir con el corazón atemorizado.",
    verseRef: "Juan 14:27",
    reflection: "La paz del mundo depende de que todo salga bien; la de Jesús se sostiene aun cuando no sale. Es un regalo que él deja, no un logro que tenés que fabricar. Recibila hoy y no dejés que el temor se adueñe de tu corazón.",
    closingPrayer: "Señor, gracias por tu paz que el mundo no puede dar. Guardá mi corazón del temor y la turbación. Amén.",
  },
  {
    day: 30,
    openingPrayer: "Dios de luz, que mi vida refleje tu bondad hoy.",
    intro: "En el Sermón del Monte, Jesús usa la imagen de una lámpara y de una ciudad sobre un monte. Llama a sus seguidores la luz del mundo y los anima a que sus buenas obras lleven a otros a glorificar al Padre.",
    verseRef: "Mateo 5:14-16",
    reflection: "Aun en medio de tu cansancio, tu vida puede alumbrar a otros. La luz no se trata de brillar para ser vistos, sino de que la gente vea a Dios a través de lo que hacemos. Un acto sencillo de bondad hoy puede ser luz en el día de alguien.",
    closingPrayer: "Padre, que mi vida apunte hacia vos. Usá mis obras sencillas para alumbrar a quienes me rodean. Amén.",
  },
  {
    day: 31,
    openingPrayer: "Señor, termino este mes reconociendo que vos sos mi porción.",
    intro: "Asaf confiesa en este salmo que casi tropezó al ver la prosperidad de los malvados. Al entrar en la presencia de Dios cambió su perspectiva, y concluye que aunque su cuerpo y su corazón desfallezcan, Dios es su fortaleza.",
    verseRef: "Salmos 73:26",
    reflection: "Asaf no fingió fortaleza; admitió que su carne y su corazón podían fallar. Pero descubrió que Dios mismo es su porción, su herencia segura. Al cerrar julio, entregale lo que quedó débil y recibí su fuerza para lo que viene.",
    closingPrayer: "Padre, gracias por sostenerme este mes. Sé mi fortaleza y mi porción en los días que vienen. En el nombre de Jesús. Amén.",
  },
];
