import type { DevotionalEntry } from "./types";

// Agosto — Sabiduría, carácter y servicio al prójimo (#199).
export const agosto: readonly DevotionalEntry[] = [
  {
    day: 1,
    openingPrayer: "Señor, comienzo este mes pidiéndote sabiduría. Quiero aprender de vos.",
    intro: "El libro de Proverbios fue escrito para formar a los jóvenes en una vida sabia. Su primera gran afirmación pone el fundamento de todo: el temor del Señor es el principio del conocimiento.",
    verseRef: "Proverbios 1:7",
    reflection: "El temor del Señor no es pánico, sino reverencia: reconocer que Dios es Dios y que nosotros no lo somos. Desde ese lugar humilde empieza la verdadera sabiduría. Este mes, antes de buscar respuestas, buscá a quien las tiene.",
    closingPrayer: "Padre, enseñame a vivir con reverencia delante de vos. Que tu sabiduría guíe mis decisiones durante este mes. Amén.",
  },
  {
    day: 2,
    openingPrayer: "Señor, no quiero solo escuchar tu Palabra. Ayudame a ponerla en práctica.",
    intro: "Santiago escribe una carta muy práctica a creyentes dispersos. Les advierte que escuchar la Palabra sin obedecerla es engañarse a sí mismos.",
    verseRef: "Santiago 1:22",
    reflection: "Es fácil confundir saber con hacer. Podemos conocer muchos versículos y aun así no dejar que cambien nuestra manera de tratar a otros. Elegí hoy una enseñanza que ya conocés y dale un paso concreto de obediencia.",
    closingPrayer: "Señor, que tu Palabra no se quede en mis oídos. Dame un corazón dispuesto a obedecer en lo pequeño. Amén.",
  },
  {
    day: 3,
    openingPrayer: "Dios justo, mostrame lo que es bueno ante tus ojos.",
    intro: "Miqueas habló en tiempos de mucha religiosidad y poca justicia. Frente a la pregunta sobre qué ofrenda agrada a Dios, el profeta responde con tres actitudes sencillas y profundas.",
    verseRef: "Miqueas 6:8",
    reflection: "Dios no busca primero grandes sacrificios, sino una vida justa, misericordiosa y humilde ante él. Las tres cosas van juntas: la justicia sin misericordia se vuelve dura, y ambas sin humildad se vuelven orgullo. Pensá hoy en cuál de las tres necesitás crecer.",
    closingPrayer: "Señor, enseñame a hacer justicia, amar la misericordia y caminar humildemente con vos. Formá ese carácter en mí. Amén.",
  },
  {
    day: 4,
    openingPrayer: "Padre generoso, gracias por todo lo que me has dado. Abrí mis manos para dar.",
    intro: "Proverbios observa la vida diaria y saca lecciones sobre el carácter. En este versículo describe al alma generosa y a quien sacia a otros, que también es saciado.",
    verseRef: "Proverbios 11:25",
    reflection: "La generosidad no es una inversión para recibir más, sino una forma de vivir que refresca a otros y nos libra del egoísmo. Quien da con alegría descubre una riqueza que no se mide en dinero. Buscá hoy a alguien a quien podás refrescar con tu tiempo, tus palabras o tus recursos.",
    closingPrayer: "Señor, librame de la tacañería del corazón. Haceme generoso como vos lo sos conmigo. Amén.",
  },
  {
    day: 5,
    openingPrayer: "Señor Jesús, me acerco a tus palabras reconociendo mi necesidad.",
    intro: "Hoy comenzamos una serie sobre las bienaventuranzas, el inicio del Sermón del Monte. Jesús empieza hablando de los pobres en espíritu y del lugar que tienen en el reino.",
    verseRef: "Mateo 5:3",
    reflection: "Ser pobre en espíritu es reconocer que no tenemos nada que ofrecer a Dios para ganarnos su favor. Esa humildad no es una derrota, es la puerta de entrada al reino. Quien se sabe necesitado está listo para recibir la gracia.",
    closingPrayer: "Señor, reconozco mi necesidad de vos. Quitá de mí la autosuficiencia y llename de tu gracia. Amén.",
  },
  {
    day: 6,
    openingPrayer: "Dios de consuelo, traigo ante vos mis pérdidas y mis lágrimas.",
    intro: "Continuamos con las bienaventuranzas. La segunda se dirige a quienes lloran y les anuncia el consuelo de Dios.",
    verseRef: "Mateo 5:4",
    reflection: "Jesús no celebra el sufrimiento, pero sí honra el llanto sincero: por el pecado, por las pérdidas, por un mundo roto. Quienes lloran delante de Dios no son ignorados; él promete consolarlos. No tenés que esconder tu tristeza para acercarte a él.",
    closingPrayer: "Padre, recibí mis lágrimas. Consolame con tu presencia y ayudame a consolar a otros que lloran. Amén.",
  },
  {
    day: 7,
    openingPrayer: "Señor, enseñame la fuerza de la mansedumbre.",
    intro: "La tercera bienaventuranza habla de los mansos. Jesús les asegura una herencia, retomando una promesa del Salmo 37.",
    verseRef: "Mateo 5:5",
    reflection: "La mansedumbre no es debilidad, sino fuerza bajo control. El manso no necesita imponerse ni defenderse a toda costa, porque confía en que Dios hará justicia. En una conversación difícil de hoy, elegí responder con calma en vez de con dureza.",
    closingPrayer: "Señor Jesús, vos sos manso y humilde de corazón. Formá en mí esa misma mansedumbre. Amén.",
  },
  {
    day: 8,
    openingPrayer: "Dios santo, despertá en mí hambre de lo que es justo.",
    intro: "La cuarta bienaventuranza usa la imagen del hambre y la sed. Jesús describe a quienes anhelan la justicia con esa intensidad y les promete que su deseo no quedará vacío.",
    verseRef: "Mateo 5:6",
    reflection: "Tener hambre y sed de justicia es anhelar que la voluntad de Dios se haga en tu vida y en el mundo. No es conformarse con una fe tibia, sino desear de verdad lo que agrada a Dios. Él promete saciar ese deseo, no dejarlo vacío.",
    closingPrayer: "Señor, dame hambre de tu justicia más que de cualquier otra cosa. Saciá mi corazón con lo que es bueno a tus ojos. Amén.",
  },
  {
    day: 9,
    openingPrayer: "Padre misericordioso, gracias por la compasión que tenés conmigo.",
    intro: "La quinta bienaventuranza mira hacia los misericordiosos. Jesús muestra que quien da compasión también la recibe.",
    verseRef: "Mateo 5:7",
    reflection: "La misericordia no se gana siendo misericordioso; más bien, quien ha recibido misericordia aprende a darla. Cuando recordás cuánto te ha perdonado Dios, se vuelve más fácil tener paciencia con otros. Pensá hoy en alguien que necesita tu compasión más que tu juicio.",
    closingPrayer: "Señor, que la misericordia que recibí de vos fluya hacia los demás. Ablandá mi corazón donde se ha endurecido. Amén.",
  },
  {
    day: 10,
    openingPrayer: "Dios santo, limpiá mi corazón para que pueda verte.",
    intro: "La sexta bienaventuranza habla de los de limpio corazón. Jesús les promete el mayor de los regalos: contemplar a Dios.",
    verseRef: "Mateo 5:8",
    reflection: "Un corazón limpio no es un corazón que nunca falló, sino uno que no vive dividido. Busca a Dios con sinceridad, sin dobles intenciones. Pedile hoy que purifique tus motivos, no solo tus acciones.",
    closingPrayer: "Señor, creá en mí un corazón limpio y sincero. Quitá lo que me divide y dame ojos para verte. Amén.",
  },
  {
    day: 11,
    openingPrayer: "Dios de paz, haceme un instrumento de tu paz hoy.",
    intro: "Cerramos la serie con la séptima bienaventuranza. Jesús habla de quienes trabajan por la paz y de la identidad que reciben como parte de la familia de Dios.",
    verseRef: "Mateo 5:9",
    reflection: "Pacificar no es evitar los conflictos ni callar para no incomodar. Es trabajar activamente por la reconciliación, como Dios lo hizo con nosotros en Cristo. En tu familia, tu trabajo o tu iglesia, buscá hoy un paso pequeño hacia la paz.",
    closingPrayer: "Padre, gracias por reconciliarme con vos en Cristo. Dame valor y humildad para buscar la paz con los demás. Amén.",
  },
  {
    day: 12,
    openingPrayer: "Señor, quiero que mi vida dé sabor a donde vaya.",
    intro: "Después de las bienaventuranzas, Jesús describe la identidad de sus seguidores. Los llama sal de la tierra y advierte sobre la sal que pierde su sabor.",
    verseRef: "Mateo 5:13",
    reflection: "En tiempos de Jesús la sal preservaba y daba sabor. Los creyentes están llamados a ser una presencia que frena la corrupción y añade bondad al mundo. No necesitás un escenario grande; tu manera de trabajar, hablar y servir ya es sal.",
    closingPrayer: "Señor, que no pierda el sabor de tu gracia. Usame para dar bondad y verdad en los lugares donde me pusiste. Amén.",
  },
  {
    day: 13,
    openingPrayer: "Dios sabio, necesito la sabiduría que viene de lo alto.",
    intro: "Santiago contrasta dos tipos de sabiduría: una terrenal, marcada por celos y contiendas, y otra que viene de lo alto. A esta última la describe con varias cualidades.",
    verseRef: "Santiago 3:17",
    reflection: "La sabiduría de Dios no se reconoce por lo mucho que sabés, sino por cómo tratás a otros. Es pura, pacífica, amable, dispuesta a escuchar y llena de misericordia. Revisá hoy una conversación reciente a la luz de esta lista.",
    closingPrayer: "Padre, dame la sabiduría que viene de vos. Que se note en mi manera de hablar, escuchar y tratar a los demás. Amén.",
  },
  {
    day: 14,
    openingPrayer: "Señor, usá mis palabras hoy para animar a alguien.",
    intro: "Proverbios observa cómo la ansiedad afecta a las personas. En este versículo contrasta el peso de la congoja con el alivio que trae una palabra amable.",
    verseRef: "Proverbios 12:25",
    reflection: "Muchas personas a tu alrededor cargan preocupaciones que no se ven. Una palabra amable, dicha a tiempo, puede aliviar más de lo que imaginás. Enviá hoy un mensaje sincero de ánimo a alguien que lo necesite.",
    closingPrayer: "Señor, abrí mis ojos a la ansiedad de otros. Poné en mi boca palabras buenas que alegren corazones. Amén.",
  },
  {
    day: 15,
    openingPrayer: "Dios bueno, guardá hoy mi boca y llenala de gracia.",
    intro: "Pablo enseña a los efesios cómo es la vida nueva en Cristo. Entre sus instrucciones prácticas habla de las palabras: que ninguna sea corrompida, sino útil para edificar.",
    verseRef: "Efesios 4:29",
    reflection: "Las palabras construyen o destruyen. Pablo propone una pregunta sencilla antes de hablar: esto que voy a decir, ¿edifica y da gracia a quien lo escucha? Practicá hoy ese filtro, especialmente con las personas más cercanas.",
    closingPrayer: "Señor, que mis palabras edifiquen y no hieran. Perdoname por lo que he dicho con dureza y enseñame a hablar con gracia. Amén.",
  },
  {
    day: 16,
    openingPrayer: "Señor, enseñame a escuchar antes de responder.",
    intro: "Santiago da un consejo breve sobre la manera de relacionarnos. Invita a dar prioridad a escuchar y a frenar tanto las palabras apresuradas como el enojo.",
    verseRef: "Santiago 1:19",
    reflection: "Escuchar bien es una forma de amar. Cuando hablamos rápido y nos enojamos rápido, solemos herir y entender poco. Hoy, en tus conversaciones, dejá que el otro termine antes de pensar en tu respuesta.",
    closingPrayer: "Padre, dame paciencia para escuchar y dominio para hablar. Guardame del enojo que no produce tu justicia. Amén.",
  },
  {
    day: 17,
    openingPrayer: "Dios santo, poné guarda a mi boca en este día.",
    intro: "David escribe este salmo como una oración de la tarde. Le pide a Dios que cuide lo que sale de su boca, como un guardia a la entrada de una ciudad.",
    verseRef: "Salmos 141:3",
    reflection: "David sabía que necesitaba ayuda para controlar su lengua. No es solo cuestión de fuerza de voluntad; es algo que podemos pedir en oración. Antes de una reunión o conversación difícil, hacé esta misma oración.",
    closingPrayer: "Señor, guardá mis labios del chisme, la queja y la crítica injusta. Que lo que salga de mi boca te honre. Amén.",
  },
  {
    day: 18,
    openingPrayer: "Señor Jesús, enseñame a tratar a otros como vos me tratás.",
    intro: "En el sermón que Lucas registra en la llanura, Jesús enseña sobre el amor a los demás. Allí da un principio sencillo: tratar a otros como queremos que ellos nos traten.",
    verseRef: "Lucas 6:31",
    reflection: "Esta regla de oro nos obliga a ponernos en el lugar del otro. No espera a que el otro empiece; toma la iniciativa del bien. Pensá hoy cómo te gustaría ser tratado en tu peor día, y tratá así a alguien.",
    closingPrayer: "Padre, dame empatía para ver a los demás como personas que vos amás. Que tome la iniciativa de hacer el bien. Amén.",
  },
  {
    day: 19,
    openingPrayer: "Padre misericordioso, gracias porque tu compasión no se agota.",
    intro: "En el mismo pasaje sobre amar a los enemigos, Jesús da el modelo para nuestra conducta. Llama a sus discípulos a ser misericordiosos como el Padre es misericordioso.",
    verseRef: "Lucas 6:36",
    reflection: "El estándar de nuestra misericordia no es lo que otros merecen, sino cómo es Dios. Él es bondadoso aun con los ingratos. Cuando te cueste ser compasivo, recordá cuántas veces el Padre lo ha sido con vos.",
    closingPrayer: "Señor, gracias por tu misericordia conmigo. Haceme reflejo de tu compasión hacia los demás. Amén.",
  },
  {
    day: 20,
    openingPrayer: "Señor Jesús, abrí mis ojos para verte en quienes necesitan ayuda.",
    intro: "Jesús cuenta una escena del juicio final en la que separa a las personas según cómo trataron a los necesitados. El Rey se identifica con los más pequeños y necesitados, y toma como hecho a él lo que se hizo por ellos.",
    verseRef: "Mateo 25:40",
    reflection: "Jesús se identifica con el hambriento, el enfermo, el extranjero y el preso. Servir al necesitado no es un extra de la fe, sino una forma de amar a Cristo. Buscá hoy a alguien olvidado a tu alrededor y servile con dignidad.",
    closingPrayer: "Señor, que no pase de largo ante quien necesita. Dame un corazón compasivo y manos dispuestas a servir. Amén.",
  },
  {
    day: 21,
    openingPrayer: "Dios de paz, ayudame a vivir en paz con los que me rodean.",
    intro: "Pablo da a los romanos una serie de instrucciones sobre el amor práctico. Entre ellas pide que, en cuanto dependa de nosotros, estemos en paz con todos.",
    verseRef: "Romanos 12:18",
    reflection: "Pablo es realista: no todo depende de vos, y a veces la otra persona no quiere paz. Pero sí podés hacer tu parte: no devolver mal por mal, pedir perdón y perdonar. Pensá hoy qué está en tus manos hacer en una relación difícil.",
    closingPrayer: "Señor, mostrame mi parte en los conflictos que vivo. Dame humildad para buscar la paz donde dependa de mí. Amén.",
  },
  {
    day: 22,
    openingPrayer: "Señor, que lo ordinario de este día sea para tu gloria.",
    intro: "Pablo responde a los corintios sobre temas prácticos, como qué comer o beber. Concluye con un principio amplio: todo lo que hagamos, hagámoslo para la gloria de Dios.",
    verseRef: "1 Corintios 10:31",
    reflection: "No existe tarea demasiado sencilla para honrar a Dios. Comer, trabajar, estudiar o limpiar la casa pueden hacerse con gratitud y cuidado. Elegí hoy una actividad rutinaria y ofrecésela a Dios mientras la hacés.",
    closingPrayer: "Padre, que mi vida diaria, aun en lo pequeño, sea para tu gloria. Dame gratitud en cada tarea. Amén.",
  },
  {
    day: 23,
    openingPrayer: "Dios compasivo, gracias porque te importan los pobres.",
    intro: "Proverbios habla con frecuencia del trato a los pobres. Este versículo afirma que quien da al pobre presta al Señor, y que Dios ve y recompensa el bien hecho.",
    verseRef: "Proverbios 19:17",
    reflection: "Este proverbio no enseña a dar para recibir más, sino que muestra cuánto valora Dios a los pobres: lo hecho por ellos, lo toma como hecho a él. Nada de lo que das con amor se pierde ante sus ojos. Dar es una manera de reflejar el corazón de Dios hacia el necesitado.",
    closingPrayer: "Señor, dame un corazón atento a los pobres. Que dé con amor y sin buscar nada a cambio. Amén.",
  },
  {
    day: 24,
    openingPrayer: "Señor, mostrame hoy a quién puedo hacer el bien.",
    intro: "Pablo termina su carta a los gálatas animándolos a no cansarse de hacer el bien. Les pide que, mientras tengan oportunidad, lo hagan a todos, y especialmente a la familia de la fe.",
    verseRef: "Gálatas 6:10",
    reflection: "Las oportunidades de hacer el bien no siempre vuelven. Pablo nos invita a aprovecharlas con todos, empezando por los hermanos de la iglesia que tenemos cerca. Pensá en alguien de tu congregación que esté pasando un tiempo difícil y buscalo hoy.",
    closingPrayer: "Padre, dame ojos para ver las oportunidades de servir. Que mi iglesia sea un lugar donde nos cuidamos unos a otros. Amén.",
  },
  {
    day: 25,
    openingPrayer: "Dios generoso, gracias por los dones que me diste. Quiero usarlos para servir.",
    intro: "Pedro escribe a iglesias que enfrentaban sufrimiento. Les recuerda que cada creyente ha recibido un don y que debe usarlo para servir a otros, como buen administrador de la gracia de Dios.",
    verseRef: "1 Pedro 4:10",
    reflection: "Nadie es tan pequeño que no tenga algo que aportar. Tus dones no son para lucirte, sino para servir; y no son tuyos, sino de Dios que te los confió. Preguntate hoy qué don te dio Dios y cómo podés ponerlo al servicio de alguien.",
    closingPrayer: "Señor, gracias por lo que me confiaste. Enseñame a administrar tus dones con humildad y fidelidad. Amén.",
  },
  {
    day: 26,
    openingPrayer: "Señor Jesús, quiero aprender la alegría de dar.",
    intro: "Pablo se despide de los ancianos de Éfeso con un discurso emotivo. Les recuerda su ejemplo de trabajo y cita una enseñanza de Jesús sobre la dicha de dar.",
    verseRef: "Hechos 20:35",
    reflection: "Pablo trabajó con sus manos para no ser carga y para ayudar a los débiles. Su vida mostraba que dar trae una alegría que el recibir no alcanza. Buscá hoy una forma sencilla de dar sin esperar nada a cambio.",
    closingPrayer: "Padre, librame del egoísmo. Dame la alegría de dar como Jesús lo enseñó. Amén.",
  },
  {
    day: 27,
    openingPrayer: "Dios de luz, que mi servicio a otros sea parte de mi adoración.",
    intro: "Isaías confronta a un pueblo que ayunaba pero oprimía a los demás. Dios les muestra el ayuno que le agrada: compartir con el hambriento y saciar al afligido, y les promete que su luz brillará en la oscuridad.",
    verseRef: "Isaías 58:10",
    reflection: "La verdadera devoción no se queda en ritos; se vuelve compasión concreta. Cuando entregás tu pan y tu atención al que sufre, tu vida se convierte en luz. No es un mérito para ganar el favor de Dios, sino fruto de haberlo recibido.",
    closingPrayer: "Señor, que mi fe se vea en compasión concreta. Usá mi vida para alumbrar a quienes están en oscuridad. Amén.",
  },
  {
    day: 28,
    openingPrayer: "Señor Jesús, me siento a tus pies. Quiero escucharte primero.",
    intro: "Jesús visitó la casa de Marta y María en Betania. Mientras Marta se afanaba con los preparativos, María se sentó a escucharlo, y Jesús le dijo a Marta que solo una cosa era necesaria.",
    verseRef: "Lucas 10:41-42",
    reflection: "Servir es bueno, pero el servicio sin comunión con Jesús termina en afán y queja. María eligió lo que no le sería quitado: estar con él. Antes de lanzarte a todas tus tareas, tomá tiempo para escucharlo.",
    closingPrayer: "Señor, perdoname cuando el afán me aleja de vos. Enseñame a servir desde la comunión con vos. Amén.",
  },
  {
    day: 29,
    openingPrayer: "Padre, este es un mandato difícil. Necesito tu gracia para cumplirlo.",
    intro: "En el Sermón del Monte, Jesús lleva el amor más allá de lo esperado. Enseña a amar a los enemigos y a orar por quienes nos persiguen.",
    verseRef: "Mateo 5:44",
    reflection: "Amar al enemigo no significa aprobar el mal ni dejar de poner límites sanos. Significa no devolver odio y desear su bien delante de Dios. Empezá por algo concreto: orá hoy por alguien que te ha herido.",
    closingPrayer: "Señor, me cuesta amar a quien me hizo daño. Ayudame a orar por esa persona y sanar mi corazón. Amén.",
  },
  {
    day: 30,
    openingPrayer: "Dios sabio, vengo a vos como fuente de toda sabiduría.",
    intro: "En Proverbios, un padre anima a su hijo a buscar la sabiduría como un tesoro escondido. Luego le recuerda de dónde viene: es el Señor quien la da.",
    verseRef: "Proverbios 2:6",
    reflection: "La sabiduría no es solo resultado del estudio o la experiencia; es un regalo de Dios. Por eso se busca con oración, en su Palabra y con humildad. Si hoy enfrentás una decisión, pedile sabiduría antes de decidir.",
    closingPrayer: "Señor, te pido sabiduría para las decisiones que tengo enfrente. Que tu Palabra guíe mi entendimiento. Amén.",
  },
  {
    day: 31,
    openingPrayer: "Señor, quiero vivir cerca de vos con integridad.",
    intro: "David abre este salmo con una pregunta: quién puede habitar en la presencia de Dios. La respuesta describe a la persona íntegra, que hace justicia y habla verdad en su corazón.",
    verseRef: "Salmos 15:1-2",
    reflection: "La integridad es ser la misma persona en público y en privado. No se trata de ganar el acceso a Dios por méritos, sino de vivir de acuerdo con la gracia que nos acercó a él. Al cerrar este mes de sabiduría y servicio, pedile un corazón íntegro.",
    closingPrayer: "Padre, gracias por recibirme en tu presencia por medio de Cristo. Formá en mí un carácter íntegro y verdadero. En el nombre de Jesús. Amén.",
  },
];
