import type { DevotionalEntry } from "./types";

// Septiembre — Mes de la Patria y de la Biblia (#199).
export const septiembre: readonly DevotionalEntry[] = [
  {
    day: 1,
    openingPrayer: "Señor, al comenzar el mes de la patria, te presento a Honduras y a su gente.",
    intro: "El salmo 33 es un canto de alabanza al Dios creador que gobierna sobre las naciones. En medio de él, el salmista declara dichosa a la nación cuyo Dios es el Señor.",
    verseRef: "Salmos 33:12",
    reflection: "La verdadera dicha de un pueblo no está en su poder ni en sus banderas, sino en reconocer a Dios. Ese reconocimiento empieza en los hogares y en las iglesias, no en los discursos. Este mes, orá para que muchos en Honduras conozcan y amen al Señor.",
    closingPrayer: "Padre, bendecí a Honduras. Que nuestro pueblo te busque y te reconozca en cada familia y comunidad. En el nombre de Jesús. Amén.",
  },
  {
    day: 2,
    openingPrayer: "Dios justo, guiá a nuestro país por caminos de rectitud.",
    intro: "Proverbios no solo habla de la vida personal, también observa la vida de los pueblos. Este versículo contrasta lo que engrandece a una nación con lo que la avergüenza.",
    verseRef: "Proverbios 14:34",
    reflection: "La justicia de una nación se construye con decisiones pequeñas de muchas personas: pagar lo justo, decir la verdad, no aceptar sobornos. Antes de señalar a otros, podemos preguntarnos qué aportamos nosotros. Tu integridad diaria también es un servicio a tu país.",
    closingPrayer: "Señor, que la justicia crezca en Honduras, empezando por mi propia vida. Librá a nuestro pueblo de la corrupción y la mentira. Amén.",
  },
  {
    day: 3,
    openingPrayer: "Señor, quiero buscar el bien del lugar donde vivo.",
    intro: "Jeremías escribió una carta a los israelitas llevados cautivos a Babilonia. En lugar de pedirles que se encerraran, les indicó que procuraran la paz de la ciudad donde estaban y oraran por ella.",
    verseRef: "Jeremías 29:7",
    reflection: "Si Dios pidió a su pueblo orar por una ciudad extranjera, cuánto más podemos orar por nuestro barrio, colonia o aldea. Buscar el bien común es parte de nuestra fe. Pensá hoy en una necesidad concreta de tu comunidad y llevala ante Dios.",
    closingPrayer: "Padre, bendecí el lugar donde vivo. Dame un corazón que busque su paz y manos dispuestas a servir. Amén.",
  },
  {
    day: 4,
    openingPrayer: "Dios soberano, te presento a quienes gobiernan nuestro país.",
    intro: "Pablo instruye a Timoteo sobre la vida de la iglesia. Lo primero que pide es que se hagan oraciones por todas las personas, incluyendo a los reyes y a todos los que están en autoridad.",
    verseRef: "1 Timoteo 2:1-2",
    reflection: "Pablo escribió esto bajo gobernantes que no eran cristianos. Orar por las autoridades no depende de si estamos de acuerdo con ellas, sino del deseo de que haya paz y que el evangelio avance. Hoy, orá por nombre por autoridades locales y nacionales.",
    closingPrayer: "Señor, dales sabiduría, honestidad y temor de vos a quienes gobiernan Honduras. Que su trabajo sirva al bien de todos. Amén.",
  },
  {
    day: 5,
    openingPrayer: "Señor, me humillo delante de vos y te pido perdón por mis pecados.",
    intro: "Este versículo es parte de la respuesta de Dios a Salomón después de dedicar el templo. Allí Dios habla de su pueblo que se humilla, ora, busca su rostro y se aparta de sus malos caminos.",
    verseRef: "2 Crónicas 7:14",
    reflection: "El llamado es primero al pueblo de Dios, no a los demás. Antes de pedir cambios en la nación, Dios nos invita a la humildad, la oración y el arrepentimiento. La sanidad que necesitamos comienza con corazones que vuelven a él.",
    closingPrayer: "Padre, empezá por mí. Dame un corazón humilde y arrepentido, y que tu iglesia en Honduras te busque con sinceridad. Amén.",
  },
  {
    day: 6,
    openingPrayer: "Señor eterno, gracias porque tu Palabra permanece firme.",
    intro: "El salmo 119 es el más largo de la Biblia y está dedicado a celebrar la Palabra de Dios. En este versículo el salmista celebra la firmeza eterna de esa Palabra, asentada en el cielo mismo.",
    verseRef: "Salmos 119:89",
    reflection: "Los gobiernos cambian, las leyes se reforman y las épocas pasan. La Palabra de Dios sigue siendo el fundamento seguro para cada generación. Este mes de la Biblia, comprometete a leerla con más constancia.",
    closingPrayer: "Señor, gracias por tu Palabra que no cambia. Dame hambre de leerla y firmeza para vivir según ella. Amén.",
  },
  {
    day: 7,
    openingPrayer: "Dios de las restauraciones, animanos a trabajar juntos por lo que está caído.",
    intro: "Nehemías llegó a Jerusalén y encontró sus muros en ruinas. Les contó a los líderes cómo la mano de Dios había estado con él, y ellos se animaron a levantarse y edificar.",
    verseRef: "Nehemías 2:18",
    reflection: "La reconstrucción comenzó cuando la gente vio que Dios estaba obrando y decidió unir esfuerzos. Nuestras comunidades también tienen muros caídos: familias rotas, jóvenes sin rumbo, vecinos sin esperanza. Preguntate hoy con quién podés unirte para levantar algo bueno.",
    closingPrayer: "Señor, danos ánimo para edificar donde hay ruinas. Que tu iglesia trabaje unida por el bien de nuestro pueblo. Amén.",
  },
  {
    day: 8,
    openingPrayer: "Señor, quiero que tu Palabra esté en mi corazón y en mi casa.",
    intro: "Moisés exhorta a Israel antes de entrar en la tierra prometida. Les pide que guarden las palabras de Dios en su corazón y en su alma, y que las tengan presentes en la vida diaria.",
    verseRef: "Deuteronomio 11:18",
    reflection: "La fe se transmite en lo cotidiano: en la mesa, en el camino, al acostarse y al levantarse. No hace falta ser experto para hablar de Dios con los hijos o los nietos. Leé hoy un pasaje breve en familia y conversen sobre él.",
    closingPrayer: "Padre, que tu Palabra llene mi corazón y mi hogar. Ayudame a enseñarla con el ejemplo y con amor. Amén.",
  },
  {
    day: 9,
    openingPrayer: "Señor Jesús, gracias por tu amor hacia los niños.",
    intro: "Algunas personas llevaban niños a Jesús para que los bendijera, y los discípulos intentaron impedirlo. Jesús los corrigió y abrió los brazos a los pequeños.",
    verseRef: "Mateo 19:14",
    reflection: "En una cultura que daba poco valor a los niños, Jesús los recibió con alegría. Mañana celebramos el Día del Niño en Honduras, y es buena ocasión para preguntarnos si nuestras iglesias y hogares abren camino a los pequeños hacia él. No estorbemos su fe; acompañémosla.",
    closingPrayer: "Señor, bendecí a los niños de Honduras. Protegelos del abuso y del abandono, y ayudanos a guiarlos hacia vos. Amén.",
  },
  {
    day: 10,
    openingPrayer: "Dios creador, gracias por la vida de cada niño y niña.",
    intro: "Hoy es el Día del Niño en Honduras. En el salmo 139, David se maravilla de que Dios lo formó desde el vientre de su madre con cuidado y propósito.",
    verseRef: "Salmos 139:13-14",
    reflection: "Cada niño es una obra de Dios, no un accidente ni una carga. Su valor no depende de su familia, su escuela o su situación económica. Hoy podés decirle a un niño cercano, con palabras y gestos, que es valioso.",
    closingPrayer: "Padre, gracias por formar a cada niño con amor. Que nuestro país los cuide, los proteja y les dé oportunidades. Amén.",
  },
  {
    day: 11,
    openingPrayer: "Dios de paz, sembrá justicia en nuestra tierra.",
    intro: "Isaías describe un tiempo en que el Espíritu de Dios renovaría a su pueblo. En ese tiempo, la justicia produciría paz, tranquilidad y seguridad duraderas.",
    verseRef: "Isaías 32:17",
    reflection: "La paz verdadera no se impone a la fuerza; brota de la justicia. Donde hay trato justo, verdad y cuidado de los débiles, la violencia pierde terreno. Orá hoy por paz en los barrios más golpeados por la violencia en Honduras.",
    closingPrayer: "Señor, que la justicia traiga paz a nuestras calles y hogares. Consolá a las familias que han sufrido violencia. Amén.",
  },
  {
    day: 12,
    openingPrayer: "Dios justo, que tu justicia corra como río en nuestra tierra.",
    intro: "Amós habló contra un pueblo que celebraba fiestas religiosas mientras oprimía a los pobres. Dios rechazó esa religión vacía y pidió que el derecho y la justicia fluyeran sin cesar.",
    verseRef: "Amós 5:24",
    reflection: "Dios no se impresiona con cultos llenos si la vida diaria desprecia al débil. La justicia que pide Amós es constante, como un río que no se seca. Nuestra adoración se vuelve creíble cuando va acompañada de trato justo a los demás.",
    closingPrayer: "Señor, que mi fe no se quede en palabras. Usame para que haya justicia y misericordia donde vivo. Amén.",
  },
  {
    day: 13,
    openingPrayer: "Señor, que tu bendición alcance a nuestras ciudades por medio de tu pueblo.",
    intro: "Proverbios compara el efecto de las personas rectas con el de los malvados en una ciudad. Los rectos traen bendición; las palabras de los perversos la derriban.",
    verseRef: "Proverbios 11:11",
    reflection: "La presencia de personas íntegras hace una diferencia real en una comunidad. Las palabras también construyen o destruyen ciudades: el rumor, la mentira y la burla dañan la convivencia. Hoy podés ser bendición en tu colonia con tus acciones y tus palabras.",
    closingPrayer: "Padre, haceme una persona que traiga bendición a mi ciudad. Guardá mi boca de palabras que dividen. Amén.",
  },
  {
    day: 14,
    openingPrayer: "Señor, gracias por la libertad que tengo en Cristo.",
    intro: "Pablo defiende ante los gálatas que en Cristo somos libres de la esclavitud de la ley. Pero aclara que esa libertad no es para servir a nuestros deseos egoístas, sino para servirnos unos a otros por amor.",
    verseRef: "Gálatas 5:13",
    reflection: "En vísperas de celebrar la independencia, vale preguntarse para qué usamos nuestra libertad. La libertad cristiana no es hacer lo que me da la gana, sino quedar libre para amar y servir. Usá hoy tu libertad para ayudar a alguien.",
    closingPrayer: "Señor, gracias por hacerme libre. Que no use esa libertad para mí mismo, sino para servir a otros en amor. Amén.",
  },
  {
    day: 15,
    openingPrayer: "Señor Jesús, en este Día de la Independencia, te agradezco por la libertad que solo vos das.",
    intro: "Hoy Honduras celebra su independencia. Jesús hablaba con judíos que afirmaban no ser esclavos de nadie, y les explicó que el pecado esclaviza y que solo el Hijo puede dar verdadera libertad.",
    verseRef: "Juan 8:36",
    reflection: "Agradecemos a Dios por la patria y su historia, pero hay una libertad más profunda que ninguna nación puede dar. Cristo libera del pecado, de la culpa y del temor. Celebrá hoy con gratitud, y recordá que tu libertad más valiosa la tenés en él.",
    closingPrayer: "Padre, gracias por Honduras y por la libertad que disfrutamos. Que muchos hondureños conozcan la libertad que Cristo ofrece. Amén.",
  },
  {
    day: 16,
    openingPrayer: "Dios eterno, gracias porque mi ciudadanía más profunda está en tu reino.",
    intro: "Pablo escribe a los filipenses, que vivían en una colonia romana y valoraban su ciudadanía. Les recuerda que, como creyentes, su ciudadanía está en los cielos, de donde esperan al Salvador.",
    verseRef: "Filipenses 3:20",
    reflection: "Amar a tu país es bueno, pero tu identidad más profunda está en Cristo. Eso no te aleja de Honduras; te hace un mejor ciudadano, alguien que sirve sin poner su esperanza en ningún gobierno. Viví hoy como embajador del reino donde Dios te puso.",
    closingPrayer: "Señor, que ame a mi país sin olvidar que pertenezco a tu reino. Ayudame a servir aquí con la esperanza puesta en vos. Amén.",
  },
  {
    day: 17,
    openingPrayer: "Señor, gracias por los maestros que me han formado.",
    intro: "Hoy es el Día del Maestro en Honduras. Esdras fue un escriba y maestro que volvió del exilio, y la Biblia dice que había preparado su corazón para estudiar la ley de Dios, cumplirla y enseñarla.",
    verseRef: "Esdras 7:10",
    reflection: "El orden importa: Esdras primero estudió, luego practicó y después enseñó. Los buenos maestros enseñan con su vida antes que con sus palabras. Agradecé hoy a un maestro que marcó tu vida y orá por quienes enseñan en las escuelas de Honduras.",
    closingPrayer: "Padre, bendecí a los maestros de nuestro país. Dales paciencia, sabiduría y fuerzas, y que sean reconocidos por su labor. Amén.",
  },
  {
    day: 18,
    openingPrayer: "Señor, abrí mis ojos para ver lo que tu Palabra me quiere mostrar.",
    intro: "En el salmo 119, el salmista sabe que no basta con leer la ley de Dios; necesita que Dios mismo le abra los ojos. Por eso le pide ver las maravillas que hay en ella.",
    verseRef: "Salmos 119:18",
    reflection: "Podemos leer la Biblia muchas veces sin ver su riqueza. Esta oración breve es una buena manera de empezar cada lectura. Antes de abrir la Escritura hoy, pedile a Dios que te muestre algo nuevo.",
    closingPrayer: "Padre, abrí mis ojos cada vez que leo tu Palabra. Que no la lea por costumbre, sino con asombro. Amén.",
  },
  {
    day: 19,
    openingPrayer: "Dios de luz, alumbrá mi entendimiento con tu Palabra.",
    intro: "Este versículo del salmo 119 habla del efecto de la Palabra cuando se abre y se explica. Afirma que alumbra y da entendimiento a los sencillos.",
    verseRef: "Salmos 119:130",
    reflection: "No necesitás títulos para entender la Biblia; Dios da entendimiento a los sencillos. Al exponerse su Palabra, llega luz a mentes y corazones. Aprovechá hoy un estudio bíblico, una prédica o una lectura en grupo para recibir esa luz.",
    closingPrayer: "Señor, gracias porque tu Palabra es para todos. Dame un corazón sencillo y atento a tu enseñanza. Amén.",
  },
  {
    day: 20,
    openingPrayer: "Señor, gracias por quienes me han explicado tu Palabra con claridad.",
    intro: "Después de reconstruir los muros, el pueblo se reunió para escuchar la lectura de la ley. Esdras y los levitas leían con claridad y explicaban el sentido para que todos entendieran.",
    verseRef: "Nehemías 8:8",
    reflection: "Leer y explicar la Escritura es un ministerio precioso. El pueblo no solo escuchó, sino que entendió, y eso cambió su vida. Si alguna vez te toca enseñar la Biblia, aunque sea a tus hijos, hacelo con claridad y amor.",
    closingPrayer: "Padre, bendecí a los pastores y maestros que explican tu Palabra en Honduras. Que la enseñen con fidelidad y claridad. Amén.",
  },
  {
    day: 21,
    openingPrayer: "Señor, necesito tu Palabra tanto como el pan de cada día.",
    intro: "Moisés recuerda a Israel sus cuarenta años en el desierto, donde Dios los alimentó con maná. Les explica que esa experiencia buscaba enseñarles que la vida depende de algo más que el pan: depende de la Palabra de Dios.",
    verseRef: "Deuteronomio 8:3",
    reflection: "Jesús usó estas mismas palabras cuando fue tentado en el desierto. Así como el cuerpo necesita alimento, el alma necesita la Palabra de Dios. ¿Estás alimentando tu alma con la misma constancia con que comés cada día?",
    closingPrayer: "Señor, que tu Palabra sea mi alimento diario. Despertá en mí el hambre de escucharte. Amén.",
  },
  {
    day: 22,
    openingPrayer: "Dios fiel, que tu Palabra sea gozo para mi corazón.",
    intro: "Jeremías fue un profeta que sufrió rechazo por anunciar el mensaje de Dios. Aun así, describe cómo recibió las palabras de Dios como alimento, y cómo ellas se volvieron gozo y alegría para su corazón.",
    verseRef: "Jeremías 15:16",
    reflection: "Jeremías no tuvo una vida fácil, pero encontró en la Palabra un gozo que las circunstancias no le quitaron. La Escritura no es solo un deber; puede ser fuente de alegría profunda. Leé hoy con la expectativa de encontrar gozo en ella.",
    closingPrayer: "Señor, que tu Palabra sea alegría para mí aun en días difíciles. Gracias por llamarme a ser tuyo. Amén.",
  },
  {
    day: 23,
    openingPrayer: "Señor, endulzá mi vida con tu Palabra.",
    intro: "El salmista compara la Palabra de Dios con el sabor de la miel. Para él, las palabras del Señor son más dulces que cualquier otra cosa.",
    verseRef: "Salmos 119:103",
    reflection: "Lo que es dulce se disfruta despacio. La Biblia se aprecia mejor cuando se lee sin prisa, saboreando cada frase. Tomá hoy un solo versículo y meditá en él varias veces durante el día.",
    closingPrayer: "Padre, enseñame a saborear tu Palabra. Que la prefiera a todo lo que el mundo me ofrece. Amén.",
  },
  {
    day: 24,
    openingPrayer: "Señor Jesús, preparame como buena tierra para tu Palabra.",
    intro: "Jesús contó la parábola del sembrador, en la que la semilla cae en distintos tipos de terreno. Al explicarla, describe la buena tierra como un corazón sincero que recibe la Palabra, la guarda y fructifica con el tiempo.",
    verseRef: "Lucas 8:15",
    reflection: "La semilla es la misma en todos los terrenos; lo que cambia es el corazón que la recibe. Retener la Palabra requiere atención, y dar fruto requiere paciencia. Preguntate hoy qué piedras o espinos necesitás quitar para que crezca en vos.",
    closingPrayer: "Señor, hacé de mi corazón buena tierra. Ayudame a retener tu Palabra y a dar fruto con paciencia. Amén.",
  },
  {
    day: 25,
    openingPrayer: "Dios de libertad, quiero mirar tu Palabra y ponerla en práctica.",
    intro: "Santiago compara a quien escucha la Palabra sin hacerla con alguien que se ve en un espejo y olvida su rostro. En contraste, habla de quien persevera en la ley de la libertad y la pone en práctica.",
    verseRef: "Santiago 1:25",
    reflection: "La Palabra de Dios es un espejo que nos muestra cómo somos y nos invita a cambiar. Santiago la llama ley de la libertad, porque obedecerla no nos encierra, nos libra. La bendición está en hacer, no solo en mirar.",
    closingPrayer: "Señor, que no olvide lo que tu Palabra me muestra. Dame perseverancia para vivir lo que leo. Amén.",
  },
  {
    day: 26,
    openingPrayer: "Señor, gracias porque tu Palabra siempre cumple su propósito.",
    intro: "Isaías compara la Palabra de Dios con la lluvia y la nieve que riegan la tierra y la hacen germinar. Así como ellas no vuelven sin efecto, la Palabra de Dios cumple aquello para lo que fue enviada.",
    verseRef: "Isaías 55:10-11",
    reflection: "A veces compartimos la Palabra y no vemos resultados inmediatos. Pero así como la lluvia trabaja bajo la tierra antes de que veamos el brote, Dios obra en silencio. Seguí sembrando su Palabra con confianza.",
    closingPrayer: "Padre, gracias porque tu Palabra no vuelve vacía. Dame confianza para compartirla y paciencia para esperar su fruto. Amén.",
  },
  {
    day: 27,
    openingPrayer: "Señor, que tu Palabra habite en mí y en mi iglesia con abundancia.",
    intro: "En América Latina se celebra en septiembre el Día de la Biblia. Pablo exhorta a los colosenses a que la palabra de Cristo more en ellos en abundancia, enseñándose y animándose con salmos, himnos y cánticos.",
    verseRef: "Colosenses 3:16",
    reflection: "La Palabra no es solo para la lectura privada; también se vive en comunidad. Se enseña, se canta y se comparte entre hermanos. Agradecé hoy por el regalo de tener la Biblia en nuestro idioma y celebrala con tu iglesia.",
    closingPrayer: "Padre, gracias por la Biblia y por quienes la tradujeron y la trajeron a nuestra tierra. Que habite en nosotros en abundancia. Amén.",
  },
  {
    day: 28,
    openingPrayer: "Dios fiel, quiero que mi vida esté plantada en tu Palabra.",
    intro: "El primer salmo describe dos caminos: el de los justos y el de los malos. El justo encuentra su deleite en la ley del Señor y medita en ella, y su vida se compara con un árbol bien regado que da fruto.",
    verseRef: "Salmos 1:2-3",
    reflection: "Meditar es volver una y otra vez a la Palabra, como quien rumia algo valioso. El fruto de esa vida no siempre es visible de inmediato, pero llega a su tiempo. Elegí hoy un versículo para pensar en él de día y de noche.",
    closingPrayer: "Señor, que encuentre deleite en tu Palabra. Plantá mi vida junto a tus aguas para dar fruto a su tiempo. Amén.",
  },
  {
    day: 29,
    openingPrayer: "Señor Jesús, quiero encontrarte a vos cuando leo las Escrituras.",
    intro: "Jesús discutía con líderes religiosos que estudiaban con cuidado las Escrituras. Les mostró que esas mismas Escrituras daban testimonio de él, pero ellos no querían venir a él.",
    verseRef: "Juan 5:39",
    reflection: "Es posible conocer mucho la Biblia y no conocer a Cristo. Toda la Escritura apunta a él, y el propósito de leerla es encontrarlo y recibir vida. Cuando leas hoy, buscá a Jesús en el texto.",
    closingPrayer: "Señor, que mi lectura bíblica me lleve siempre a vos. Librame de un conocimiento sin amor. Amén.",
  },
  {
    day: 30,
    openingPrayer: "Señor, cierro este mes de la Biblia con gratitud por tu Palabra.",
    intro: "El libro de Apocalipsis comienza con una bendición para quien lee, para quienes escuchan y para quienes guardan lo escrito. En los primeros siglos, las cartas se leían en voz alta en las iglesias.",
    verseRef: "Apocalipsis 1:3",
    reflection: "La Biblia termina con una promesa de bendición para quien la lee, la escucha y la guarda. Ese ciclo de leer, oír y obedecer es la manera de crecer en la fe. Al terminar septiembre, hacé un compromiso concreto de lectura para el próximo mes.",
    closingPrayer: "Padre, gracias por este mes de oración por mi país y por tu Palabra. Que siga leyendo, escuchando y guardando tus palabras. En el nombre de Jesús. Amén.",
  },
];
