import type { DevotionalEntry } from "./types";

// Octubre — Mes de la Reforma: Solo la Escritura, gracia y fe (#199).
export const octubre: readonly DevotionalEntry[] = [
  {
    day: 1,
    openingPrayer: "Señor, gracias por tu Palabra. Abrí mis ojos para verla como la luz que guía este día.",
    intro: "Comenzamos un mes dedicado a la Palabra de Dios. El salmista la compara con una lámpara: no ilumina todo el camino de una vez, pero sí el paso que tenemos enfrente.",
    verseRef: "Salmos 119:105",
    reflection: "No necesitás ver el año completo para dar el siguiente paso con fidelidad. La Escritura alumbra lo suficiente para hoy. Leela con calma y dejá que ponga luz en una decisión concreta.",
    closingPrayer: "Padre, que tu Palabra sea la lámpara de mis pasos este día. Cuando no vea claro, ayudame a volver a ella antes que a mis temores. En el nombre de Jesús. Amén.",
  },
  {
    day: 2,
    openingPrayer: "Dios fiel, me acerco a tu Palabra con un corazón dispuesto. Enseñame por medio de ella.",
    intro: "Pablo le recuerda a Timoteo de dónde viene la Escritura y para qué sirve. No es un libro más: es inspirada por Dios y útil para formar una vida entera.",
    verseRef: "2 Timoteo 3:16-17",
    reflection: "La Biblia no solo informa; también corrige, consuela y prepara para hacer el bien. Cuando la leés, Dios mismo está formando tu carácter. Preguntate hoy qué buena obra te está preparando a realizar.",
    closingPrayer: "Señor, gracias porque tu Palabra es suficiente para enseñarme a vivir. Corregime donde lo necesite y preparame para servir. Amén.",
  },
  {
    day: 3,
    openingPrayer: "Señor, gracias por el evangelio. Que hoy no me avergüence de él.",
    intro: "Estos versículos cambiaron la vida de Martín Lutero y encendieron la Reforma. Pablo afirma que en el evangelio se revela una justicia que viene de Dios y se recibe por la fe.",
    verseRef: "Romanos 1:16-17",
    reflection: "La buena noticia no es que podemos ganarnos el favor de Dios, sino que él nos lo regala en Cristo. Esa justicia se recibe confiando, no acumulando méritos. Por eso el evangelio es poder: transforma desde adentro a quien cree.",
    closingPrayer: "Padre, gracias porque mi esperanza no descansa en mis obras sino en Cristo. Dame valor para compartir esta buena noticia con sencillez. Amén.",
  },
  {
    day: 4,
    openingPrayer: "Dios de gracia, recibo este día como un regalo que no merezco. Gracias por tu bondad.",
    intro: "Pablo resume en pocas palabras cómo somos salvos. Ni el origen ni el mérito de la salvación están en nosotros: todo es gracia recibida por la fe.",
    verseRef: "Efesios 2:8-9",
    reflection: "La gracia te libra de dos cargas: la de demostrar que valés y la de compararte con otros. Nadie puede jactarse delante de Dios, y nadie queda fuera por no ser suficiente. Hoy podés descansar en lo que Cristo ya hizo.",
    closingPrayer: "Señor, gracias por salvarme por gracia. Quitá de mí el orgullo y también la culpa que no me deja descansar. Que mi vida responda con gratitud. Amén.",
  },
  {
    day: 5,
    openingPrayer: "Señor, abrí mi corazón a tu Palabra. Que hoy me hable con verdad.",
    intro: "La carta a los Hebreos describe la Palabra de Dios como viva y eficaz. No se queda en la superficie: llega hasta las intenciones más profundas del corazón.",
    verseRef: "Hebreos 4:12",
    reflection: "A veces leemos la Biblia buscando confirmar lo que ya pensamos. Pero la Palabra también nos examina con amor y saca a la luz lo que necesitamos entregar. Dejá que hoy toque un área que preferirías no mirar.",
    closingPrayer: "Padre, examiná mi corazón por medio de tu Palabra. Dame humildad para recibir su corrección y gozo para obedecer. Amén.",
  },
  {
    day: 6,
    openingPrayer: "Dios santo, me presento ante vos tal como soy. Gracias porque tu gracia me alcanza.",
    intro: "Antes de hablar de la solución, Pablo muestra el problema: todos hemos pecado. Pero en el mismo pasaje anuncia que somos justificados gratuitamente por la redención en Cristo.",
    verseRef: "Romanos 3:23-24",
    reflection: "Nadie está por encima de la necesidad de gracia, y nadie está por debajo de su alcance. Reconocer el pecado no es para hundirte, sino para recibir el perdón que Dios ofrece gratuitamente. La última palabra sobre tu vida la tiene la redención de Cristo.",
    closingPrayer: "Señor, reconozco que necesito tu gracia cada día. Gracias por justificarme gratuitamente en Jesús. Ayudame a mirar a otros con la misma misericordia. Amén.",
  },
  {
    day: 7,
    openingPrayer: "Señor eterno, en un mundo que cambia tanto, gracias porque tu Palabra permanece.",
    intro: "Isaías contrasta la fragilidad humana con la firmeza de la Palabra de Dios. La hierba se seca y la flor se marchita, pero lo que Dios dijo permanece para siempre.",
    verseRef: "Isaías 40:8",
    reflection: "Las noticias, las modas y hasta nuestras emociones cambian de un día a otro. La Palabra de Dios no pierde vigencia. Construir tu vida sobre ella es elegir un fundamento que no se mueve cuando todo lo demás tiembla.",
    closingPrayer: "Padre, gracias porque tus promesas no caducan. Afirmá mi vida sobre tu Palabra y no sobre lo pasajero. Amén.",
  },
  {
    day: 8,
    openingPrayer: "Señor Jesús, gracias por amarme y entregarte por mí. Que hoy viva unido a vos.",
    intro: "Pablo describe su vida cristiana como una unión con Cristo. Su vida vieja quedó crucificada con él, y ahora vive por la fe en el Hijo de Dios que lo amó.",
    verseRef: "Gálatas 2:20",
    reflection: "La vida cristiana no es esforzarte solo por imitar a un buen maestro. Es vivir confiando en Cristo, que te amó y se dio por vos. Hoy podés enfrentar tus tareas sabiendo que no las cargás solo.",
    closingPrayer: "Señor, gracias por tu amor que se entregó por mí. Que mi vida diaria refleje que vivo por la fe en vos. Amén.",
  },
  {
    day: 9,
    openingPrayer: "Dios de paz, aquieto mi corazón delante de vos. Gracias por recibirme en Cristo.",
    intro: "Después de explicar que somos justificados por la fe, Pablo muestra una consecuencia hermosa. Tenemos paz con Dios por medio de nuestro Señor Jesucristo.",
    verseRef: "Romanos 5:1",
    reflection: "La paz con Dios no depende de cómo te fue esta semana. Es un hecho firme basado en la obra de Cristo. Aun cuando sentís inquietud por dentro, tu relación con Dios está segura en él.",
    closingPrayer: "Padre, gracias porque en Cristo tengo paz con vos. Que esa seguridad calme mis ansiedades de hoy. Amén.",
  },
  {
    day: 10,
    openingPrayer: "Señor, tu ley es buena. Que hoy encuentre en ella alegría y no solo deber.",
    intro: "El salmista celebra la ley de Dios con palabras llenas de gozo. Para él, los mandamientos del Señor restauran el alma, dan sabiduría y alegran el corazón.",
    verseRef: "Salmos 19:7-8",
    reflection: "A veces pensamos en la Palabra solo como una lista de reglas. El salmista la vive como un regalo que endereza y alegra. Leela hoy esperando ser restaurado, no solo corregido.",
    closingPrayer: "Señor, gracias porque tu Palabra restaura mi alma. Dame un corazón que se alegre en tus caminos. Amén.",
  },
  {
    day: 11,
    openingPrayer: "Dios fiel, cuando no entiendo lo que pasa, quiero seguir confiando en vos.",
    intro: "Habacuc vivía tiempos difíciles y tenía preguntas honestas para Dios. En medio de su espera recibe una afirmación central: el justo vivirá por su fe.",
    verseRef: "Habacuc 2:4",
    reflection: "La fe no es tener todas las respuestas, sino confiar en Dios mientras esperamos. Este versículo, citado por Pablo, fue clave en la Reforma. Hoy podés vivir confiando aun con preguntas abiertas.",
    closingPrayer: "Padre, enseñame a vivir por la fe y no por lo que veo. Sostené mi confianza mientras espero tus respuestas. Amén.",
  },
  {
    day: 12,
    openingPrayer: "Señor Jesús, gracias por venir a habitar entre nosotros. Quiero conocerte mejor hoy.",
    intro: "Juan presenta a Jesús como el Verbo, la Palabra de Dios hecha carne. En él vemos la gloria de Dios, llena de gracia y de verdad.",
    verseRef: "Juan 1:14",
    reflection: "Dios no se quedó lejos dando instrucciones; se acercó en Jesús. Toda la Escritura apunta a él. Cuando leés la Biblia, buscá a Cristo, en quien la gracia y la verdad van juntas.",
    closingPrayer: "Padre, gracias por mostrarnos tu gloria en Jesús. Que mi vida tenga también gracia y verdad en equilibrio. Amén.",
  },
  {
    day: 13,
    openingPrayer: "Señor, quiero escuchar tu voz por medio de tu Palabra. Hacé crecer mi fe.",
    intro: "Pablo explica cómo nace la fe. No surge de la nada ni de nuestro esfuerzo, sino de oír el mensaje acerca de Cristo.",
    verseRef: "Romanos 10:17",
    reflection: "Si sentís que tu fe está débil, no te castigues; acercate a la Palabra. La fe crece cuando escuchamos una y otra vez lo que Dios ha hecho en Cristo. Un rato de lectura hoy puede ser alimento para tu confianza.",
    closingPrayer: "Señor, aumentá mi fe mientras escucho tu Palabra. Ayudame a buscarla cada día con hambre sincera. Amén.",
  },
  {
    day: 14,
    openingPrayer: "Dios misericordioso, gracias porque tu salvación no depende de mis méritos.",
    intro: "Pablo le escribe a Tito sobre el origen de nuestra salvación. Dios nos salvó no por obras de justicia que hayamos hecho, sino por su misericordia.",
    verseRef: "Tito 3:5",
    reflection: "La misericordia de Dios llega antes que nuestras buenas obras. Él lava y renueva por su Espíritu. Las obras vienen después, como fruto de una vida transformada y no como precio.",
    closingPrayer: "Padre, gracias por salvarme por tu misericordia. Renová mi interior por tu Espíritu para que viva agradecido. Amén.",
  },
  {
    day: 15,
    openingPrayer: "Señor, ordená mis pensamientos alrededor de tu Palabra este día.",
    intro: "Antes de que Josué guiara al pueblo, Dios le dio una instrucción clara. El libro de la ley debía estar en su boca y en su meditación de día y de noche.",
    verseRef: "Josué 1:8",
    reflection: "Meditar es más que leer rápido: es masticar la Palabra hasta que forme nuestras decisiones. La prosperidad de la que habla este pasaje es vivir conforme a Dios, no acumular cosas. Elegí hoy un versículo para repetirlo a lo largo del día.",
    closingPrayer: "Señor, que tu Palabra esté en mi boca y en mi corazón. Guiá mis decisiones para que te obedezca con fidelidad. Amén.",
  },
  {
    day: 16,
    openingPrayer: "Señor Jesús, gracias por la libertad que me diste. Que hoy no vuelva a cadenas viejas.",
    intro: "Los gálatas estaban siendo presionados a ganar su aceptación cumpliendo reglas. Pablo les recuerda que Cristo los hizo libres y que no deben volver a someterse a esclavitud.",
    verseRef: "Gálatas 5:1",
    reflection: "Es fácil volver a vivir como si tuvieras que ganarte el amor de Dios. Pero la libertad en Cristo es real. Mantenete firme en ella, y usala para amar y servir, no para el temor.",
    closingPrayer: "Padre, gracias por la libertad que tengo en Cristo. Librame de la religión que pesa y enseñame a vivir en tu gracia. Amén.",
  },
  {
    day: 17,
    openingPrayer: "Dios de gracia, me acerco con confianza, sabiendo que en Cristo no hay condenación.",
    intro: "Romanos 8 comienza con una de las afirmaciones más consoladoras del Nuevo Testamento. Para los que están en Cristo Jesús, ya no hay ninguna condenación.",
    verseRef: "Romanos 8:1",
    reflection: "Hay voces internas que te acusan por lo que fuiste o por lo que hiciste ayer. Si estás en Cristo, esa condena ya no tiene autoridad sobre vos. Podés confesar, recibir perdón y seguir caminando.",
    closingPrayer: "Señor, gracias porque en Cristo no hay condenación para mí. Silenciá las voces de acusación con la verdad de tu Palabra. Amén.",
  },
  {
    day: 18,
    openingPrayer: "Señor, dame un corazón dispuesto a recibir tu Palabra y a examinarla con cuidado.",
    intro: "Los creyentes de Berea recibieron el mensaje de Pablo con entusiasmo. Pero también escudriñaban cada día las Escrituras para ver si lo que oían era así.",
    verseRef: "Hechos 17:11",
    reflection: "Recibir con gusto y examinar con cuidado no se contradicen. La Escritura es la medida de toda enseñanza, incluso de la que escuchás con cariño. Abrí tu Biblia y dejá que sea ella la que confirme.",
    closingPrayer: "Padre, dame el corazón de los de Berea: dispuesto y atento. Que tu Palabra sea mi guía para discernir. Amén.",
  },
  {
    day: 19,
    openingPrayer: "Señor, guardá mi corazón hoy. Que tu Palabra viva en mí.",
    intro: "El salmista explica una forma práctica de resistir el pecado. Guarda la Palabra de Dios en su corazón para no pecar contra él.",
    verseRef: "Salmos 119:11",
    reflection: "Lo que guardás en el corazón aparece en los momentos de presión. Memorizar la Escritura no es un ejercicio escolar; es prepararte para cuando llegue la tentación. Elegí un versículo corto y llevalo con vos hoy.",
    closingPrayer: "Señor, sembrá tu Palabra en mi corazón. Que en la tentación recuerde tu verdad y elija agradarte. Amén.",
  },
  {
    day: 20,
    openingPrayer: "Dios misericordioso, te presento mi vida entera, no solo una parte.",
    intro: "Después de once capítulos sobre la misericordia de Dios, Pablo llama a responder con toda la vida. Nos invita a presentarnos como sacrificio vivo y a ser transformados en nuestra manera de pensar.",
    verseRef: "Romanos 12:1-2",
    reflection: "La entrega a Dios nace de su misericordia, no de la presión. Él renueva tu mente para que no te ajustés al molde de este mundo. Pensá en un área donde hoy podés ofrecerle tu obediencia.",
    closingPrayer: "Padre, recibí mi vida como ofrenda. Renová mi manera de pensar para que conozca tu buena voluntad. Amén.",
  },
  {
    day: 21,
    openingPrayer: "Señor Jesús, gracias porque sos el camino al Padre. Guiame hoy.",
    intro: "En la última cena, los discípulos estaban confundidos sobre a dónde iba Jesús. Él les responde que él mismo es el camino, la verdad y la vida.",
    verseRef: "Juan 14:6",
    reflection: "Jesús no solo señala el camino: él es el camino. En un mundo de muchas opiniones, podemos acercarnos al Padre por medio de Cristo con seguridad. Hoy podés traerle tus dudas, porque él es la verdad.",
    closingPrayer: "Padre, gracias por abrirnos el camino en Jesús. Que lo siga a él en cada decisión de este día. Amén.",
  },
  {
    day: 22,
    openingPrayer: "Padre, gracias porque en Cristo me llamás hijo. Quiero vivir confiado en ese amor.",
    intro: "Pablo explica a los gálatas su nueva identidad. Por la fe en Cristo Jesús, todos son hijos de Dios, sin importar su origen.",
    verseRef: "Gálatas 3:26",
    reflection: "Tu identidad más profunda no es tu trabajo, tu pasado ni lo que otros opinan. En Cristo sos hijo o hija de Dios por la fe. Desde esa seguridad podés tratar a los demás con dignidad.",
    closingPrayer: "Padre, gracias por adoptarme en tu familia. Que viva hoy con la confianza de quien pertenece a vos. Amén.",
  },
  {
    day: 23,
    openingPrayer: "Señor, gracias porque tu Palabra no nació de voluntad humana. Que la reciba con reverencia.",
    intro: "Pedro explica de dónde viene la profecía de la Escritura. No surgió de la interpretación de los profetas, sino que hablaron siendo guiados por el Espíritu Santo.",
    verseRef: "2 Pedro 1:20-21",
    reflection: "La Biblia tiene autores humanos, con su estilo y su historia, y a la vez es Palabra de Dios. Por eso podemos confiar en ella. Leela hoy con humildad, pidiendo que el Espíritu te ayude a entenderla.",
    closingPrayer: "Espíritu Santo, iluminá mi entendimiento cuando lea la Escritura. Que la reciba como Palabra de Dios para mi vida. Amén.",
  },
  {
    day: 24,
    openingPrayer: "Dios de amor, gracias por el regalo de la vida eterna en Cristo.",
    intro: "Pablo pone dos realidades lado a lado. El pecado paga con muerte, pero la dádiva de Dios es vida eterna en Cristo Jesús.",
    verseRef: "Romanos 6:23",
    reflection: "Un salario se gana; un regalo se recibe. La vida eterna no es un pago por buen comportamiento, sino la dádiva de Dios. Recibila con gratitud y dejá que esa vida nueva se note en tu manera de amar.",
    closingPrayer: "Padre, gracias por el regalo de la vida eterna. Que nunca la trate como algo que gané, sino como tu gracia. Amén.",
  },
  {
    day: 25,
    openingPrayer: "Señor, alimentá mi alma hoy. Que tenga hambre de tu Palabra.",
    intro: "En el desierto, Jesús fue tentado a convertir piedras en pan. Respondió con la Escritura: el ser humano no vive solo de pan, sino de toda palabra que sale de la boca de Dios.",
    verseRef: "Mateo 4:4",
    reflection: "Jesús enfrentó la tentación con la Palabra de Dios. Nuestras necesidades físicas son reales, pero no son todo. Así como no te saltás la comida, buscá también el alimento de la Escritura hoy.",
    closingPrayer: "Señor, gracias por el pan de cada día y por tu Palabra que alimenta mi alma. Ayudame a buscar las dos con gratitud. Amén.",
  },
  {
    day: 26,
    openingPrayer: "Dios de esperanza, que tu Palabra renueve mi ánimo este día.",
    intro: "Pablo explica por qué las Escrituras antiguas siguen siendo valiosas. Fueron escritas para nuestra enseñanza, para que por la paciencia y la consolación tengamos esperanza.",
    verseRef: "Romanos 15:4",
    reflection: "Las historias de la Biblia no son solo del pasado. Muestran a un Dios fiel con personas débiles como nosotros. Cuando tu esperanza baja, volvé a esas historias y recordá cómo Dios cumple.",
    closingPrayer: "Padre, gracias por la esperanza que me das por medio de tu Palabra. Dame paciencia y consuelo para seguir adelante. Amén.",
  },
  {
    day: 27,
    openingPrayer: "Señor Jesús, quiero conocerte más que cualquier otra cosa.",
    intro: "Pablo tenía un currículum religioso impresionante. Sin embargo, lo considera pérdida comparado con conocer a Cristo y ser hallado en él con la justicia que viene de Dios por la fe.",
    verseRef: "Filipenses 3:8-9",
    reflection: "Lo que antes daba seguridad a Pablo pasó a segundo plano frente a Cristo. No se trata de despreciar los logros, sino de no poner en ellos la confianza. Tu justicia delante de Dios viene de Cristo, no de tu historial.",
    closingPrayer: "Señor, que conocerte sea mi mayor ganancia. Librame de confiar en mis logros y enseñame a descansar en tu justicia. Amén.",
  },
  {
    day: 28,
    openingPrayer: "Dios santo, gracias porque en Cristo me diste acceso a tu presencia.",
    intro: "Pedro describe al pueblo de Dios como real sacerdocio. Los reformadores recuperaron esta verdad: todo creyente puede acercarse a Dios por medio de Cristo y servirle en su vocación.",
    verseRef: "1 Pedro 2:9",
    reflection: "No necesitás un intermediario humano para orar a Dios. Cristo abrió el camino. Y tu trabajo diario, en la casa, el campo o la oficina, puede ser un servicio que anuncia sus virtudes.",
    closingPrayer: "Padre, gracias por llamarme de las tinieblas a tu luz. Que mi vida diaria anuncie tu bondad. Amén.",
  },
  {
    day: 29,
    openingPrayer: "Señor Jesús, caminá conmigo hoy y abrime las Escrituras.",
    intro: "Dos discípulos caminaban tristes hacia Emaús. Jesús resucitado les explicó las Escrituras, y después reconocieron que su corazón ardía mientras él les hablaba.",
    verseRef: "Lucas 24:32",
    reflection: "La Palabra puede volver a encender un corazón desanimado. Jesús camina con los que están confundidos y les muestra cómo toda la Escritura habla de él. Pedile hoy que haga arder tu corazón mientras leés.",
    closingPrayer: "Señor, encendé mi corazón con tu Palabra. Que en mis días tristes recuerde que caminás conmigo. Amén.",
  },
  {
    day: 30,
    openingPrayer: "Padre, gracias por darnos un testimonio escrito de Jesús para que creamos.",
    intro: "Juan explica por qué escribió su evangelio. Lo hizo para que creamos que Jesús es el Cristo, el Hijo de Dios, y para que creyendo tengamos vida en su nombre.",
    verseRef: "Juan 20:31",
    reflection: "La Biblia no fue escrita solo para informarnos, sino para llevarnos a confiar en Jesús. Cada página tiene ese propósito. Leé hoy con la expectativa de encontrarte con él y recibir vida.",
    closingPrayer: "Señor, fortalecé mi fe en Jesús, el Hijo de Dios. Que en su nombre tenga vida abundante. Amén.",
  },
  {
    day: 31,
    openingPrayer: "Dios todopoderoso, sos mi refugio. Hoy descanso en vos.",
    intro: "En el Día de la Reforma recordamos el himno Castillo fuerte, inspirado en este salmo. El salmista confía en Dios como amparo y fortaleza aun cuando la tierra tiembla.",
    verseRef: "Salmos 46:1-2",
    reflection: "La fe de la Reforma no fue confianza en personas valientes, sino en un Dios fuerte. Los tiempos cambian y las dificultades llegan, pero Dios sigue siendo refugio. Hoy podés enfrentar lo que temés desde ese lugar seguro.",
    closingPrayer: "Señor, gracias porque sos mi castillo fuerte. Que en medio de los temblores de la vida mi confianza esté en vos. Amén.",
  },
];
