import type { DevotionalEntry } from "./types";

// Noviembre — Gratitud (#199).
export const noviembre: readonly DevotionalEntry[] = [
  {
    day: 1,
    openingPrayer: "Señor, comienzo este mes entrando a tu presencia con gratitud. Gracias por recibirme.",
    intro: "Comenzamos un mes dedicado a la gratitud. Este salmo era cantado por el pueblo al acercarse al templo, y describe la acción de gracias como la puerta por la que se entra a la presencia de Dios.",
    verseRef: "Salmos 100:4-5",
    reflection: "La gratitud no es un adorno de la fe; es la manera en que nos acercamos a Dios. El salmo da la razón: él es bueno y su fidelidad no se agota con las generaciones. Antes de pedir algo hoy, empezá por agradecer una bondad concreta que ya recibiste.",
    closingPrayer: "Padre, gracias porque tu bondad y tu fidelidad no cambian. Enseñame a llegar a vos con gratitud antes que con quejas. En el nombre de Jesús. Amén.",
  },
  {
    day: 2,
    openingPrayer: "Dios fiel, gracias por este nuevo día. Ayudame a vivirlo con un corazón agradecido.",
    intro: "Pablo cierra su primera carta a los tesalonicenses con instrucciones breves para una iglesia joven que enfrentaba oposición. Tres hábitos aparecen juntos: el gozo, la oración constante y la gratitud.",
    verseRef: "1 Tesalonicenses 5:16-18",
    reflection: "Pablo no pide dar gracias por todo lo que pasa, sino en medio de todo. Aun en días difíciles hay algo de Dios que sigue firme y que podés reconocer. Esa gratitud no niega el dolor; lo sostiene con la certeza de que Dios sigue presente.",
    closingPrayer: "Señor, ayudame a orar sin dejar de hablarte durante el día. Dame ojos para ver tu mano aun en las circunstancias que no entiendo. Amén.",
  },
  {
    day: 3,
    openingPrayer: "Señor, despertá mi alma para bendecirte con todo lo que soy.",
    intro: "David se habla a sí mismo en este salmo. Le ordena a su propia alma que bendiga a Dios y que no olvide ninguno de sus beneficios.",
    verseRef: "Salmos 103:1-2",
    reflection: "El olvido es uno de los grandes enemigos de la gratitud. Con facilidad recordamos lo que nos falta y olvidamos lo que Dios ya hizo. A veces hay que hablarle al propio corazón, como David, y traer a la memoria el perdón, el cuidado y la misericordia recibidos.",
    closingPrayer: "Padre, no quiero olvidar tus beneficios. Traé a mi memoria todo lo que has hecho por mí y que mi alma te bendiga por ello. Amén.",
  },
  {
    day: 4,
    openingPrayer: "Señor Jesús, que tu paz gobierne hoy mi corazón y mis relaciones.",
    intro: "Pablo escribe a los colosenses sobre la vida nueva en Cristo y sobre cómo convivir en comunidad. Después de hablar del perdón y del amor, pide que la paz de Cristo sea árbitro en el corazón, y añade una instrucción sencilla: sean agradecidos.",
    verseRef: "Colosenses 3:15",
    reflection: "La paz de Cristo funciona como un árbitro que decide qué voz manda en tu interior. La gratitud y la paz suelen caminar juntas: es difícil agradecer y guardar resentimiento al mismo tiempo. Pensá en alguien de tu iglesia o tu familia por quien podés dar gracias hoy.",
    closingPrayer: "Señor, que tu paz decida en mi corazón y no mi enojo. Haceme una persona agradecida con quienes caminan conmigo. Amén.",
  },
  {
    day: 5,
    openingPrayer: "Dios bueno, tu misericordia me alcanzó otra vez esta mañana. Gracias.",
    intro: "El Salmo 136 repite en cada versículo la misma respuesta: la misericordia de Dios es para siempre. Probablemente se cantaba en dos coros, uno que narraba las obras de Dios y otro que respondía.",
    verseRef: "Salmos 136:1",
    reflection: "La repetición no es descuido; es una forma de grabar una verdad en el corazón. Cada parte de la historia del pueblo, buena o dura, termina con el mismo recordatorio. Probá hoy repasar tu propia historia y, después de cada recuerdo, reconocer que la misericordia de Dios siguió ahí.",
    closingPrayer: "Padre, gracias porque tu misericordia no tiene fecha de vencimiento. Que mi vida sea un coro que responde a tu bondad. Amén.",
  },
  {
    day: 6,
    openingPrayer: "Señor, no quiero recibir tus bendiciones y seguir de largo. Enseñame a volver para agradecerte.",
    intro: "Jesús sanó a diez leprosos que le pidieron misericordia en el camino. Solo uno de ellos, un samaritano, regresó glorificando a Dios y se postró a sus pies para darle gracias.",
    verseRef: "Lucas 17:15-16",
    reflection: "Los diez recibieron el mismo milagro, pero solo uno volvió. Es fácil pedir con urgencia y olvidar agradecer cuando llega la respuesta. Hoy podés regresar a Jesús por una oración contestada que dejaste pasar sin darle gracias.",
    closingPrayer: "Señor Jesús, perdoname por las veces que recibí y seguí mi camino sin mirarte. Hoy vuelvo a tus pies con gratitud. Amén.",
  },
  {
    day: 7,
    openingPrayer: "Dios mío, enseñame a encontrar contentamiento en vos y no en lo que tengo.",
    intro: "Pablo escribe a los filipenses desde la prisión, agradeciendo una ofrenda que le enviaron. Aclara que no habla por necesidad, porque ha aprendido a estar contento en cualquier situación.",
    verseRef: "Filipenses 4:11",
    reflection: "El contentamiento no fue algo natural para Pablo; lo aprendió. No depende de tener mucho ni poco, sino de saber que Cristo es suficiente en ambos casos. Es una lección que se aprende despacio, en los días de escasez y también en los de abundancia.",
    closingPrayer: "Señor, enseñame a estar contento con lo que me das hoy. Librame de la comparación y de la ansiedad por tener más. En el nombre de Jesús. Amén.",
  },
  {
    day: 8,
    openingPrayer: "Padre de las luces, gracias por cada cosa buena que llega a mi vida.",
    intro: "Santiago escribe a creyentes que pasaban por pruebas. En medio de su consejo les recuerda de dónde viene todo lo bueno: de un Padre que no cambia ni tiene sombra de variación.",
    verseRef: "Santiago 1:17",
    reflection: "Todo lo bueno que tenés tiene un origen: la familia, el trabajo, un amigo, el pan de hoy. Reconocer que vienen de Dios cambia la forma en que los recibís y los cuidás. Y saber que él no cambia te da estabilidad cuando todo lo demás se mueve.",
    closingPrayer: "Padre, gracias porque todo lo bueno viene de tu mano. Ayudame a reconocerte detrás de cada regalo y a confiar en que no cambiás. Amén.",
  },
  {
    day: 9,
    openingPrayer: "Señor, gracias porque sos bueno aunque mis días no siempre lo sean.",
    intro: "El Salmo 107 abre invitando a dar gracias a Dios por su bondad. Luego cuenta historias de personas perdidas, cautivas, enfermas y en peligro que clamaron a él y fueron rescatadas.",
    verseRef: "Salmos 107:1",
    reflection: "Este salmo invita a los rescatados a contar su historia. La gratitud se vuelve testimonio cuando decimos en voz alta lo que Dios hizo. Pensá en un momento en que clamaste y él te sostuvo, y buscá hoy a alguien con quien compartirlo.",
    closingPrayer: "Dios bueno, gracias por rescatarme tantas veces. Dame valor para contar tu bondad a quienes necesitan escucharla. Amén.",
  },
  {
    day: 10,
    openingPrayer: "Señor, me uno a tu pueblo para celebrar tu bondad.",
    intro: "Cuando el arca del pacto llegó a Jerusalén, David organizó una gran celebración y entregó a los levitas un cántico de acción de gracias. Este versículo es parte de ese canto colectivo.",
    verseRef: "1 Crónicas 16:34",
    reflection: "La gratitud no es solo un asunto privado; también se celebra en comunidad. Cuando la iglesia canta junta la bondad de Dios, la fe de uno fortalece la de otro. Este domingo o en tu próxima reunión, cantá pensando en lo que Dios hizo por todos ustedes.",
    closingPrayer: "Padre, gracias por mi iglesia y por los hermanos con quienes te alabo. Que juntos celebremos tu misericordia que permanece. Amén.",
  },
  {
    day: 11,
    openingPrayer: "Señor Jesús, que mi gratitud hoy lleve tu nombre.",
    intro: "Pablo describe a los efesios cómo es una vida llena del Espíritu. Entre otras cosas, se caracteriza por dar gracias siempre a Dios Padre en el nombre de Jesucristo.",
    verseRef: "Efesios 5:20",
    reflection: "Damos gracias en el nombre de Jesús porque es por él que tenemos acceso al Padre. Nuestra gratitud no se apoya en que todo salga bien, sino en lo que Cristo ya hizo. Por eso puede ser constante, incluso cuando las circunstancias cambian.",
    closingPrayer: "Padre, gracias por darme acceso a vos por medio de Jesús. Llename de tu Espíritu para que la gratitud sea mi respuesta constante. Amén.",
  },
  {
    day: 12,
    openingPrayer: "Señor, en esta mañana quiero anunciar tu misericordia.",
    intro: "El Salmo 92 era un cántico para el día de reposo. El salmista dice que es bueno alabar a Dios, anunciando su misericordia por la mañana y su fidelidad cada noche.",
    verseRef: "Salmos 92:1-2",
    reflection: "El día tiene dos momentos naturales para agradecer: al empezar y al terminar. En la mañana podés recordar que su misericordia te acompaña; en la noche, repasar cómo fue fiel durante el día. Hacelo un hábito sencillo y vas a notar su mano con más claridad.",
    closingPrayer: "Señor, gracias por tu misericordia esta mañana. Esta noche quiero volver a darte gracias por tu fidelidad. Amén.",
  },
  {
    day: 13,
    openingPrayer: "Padre, gracias por el regalo más grande que me diste en Cristo.",
    intro: "Pablo escribe a los corintios sobre una ofrenda para los creyentes pobres de Jerusalén. Después de hablar de la generosidad, termina con una exclamación de gratitud por el don de Dios que no se puede describir con palabras.",
    verseRef: "2 Corintios 9:15",
    reflection: "Toda nuestra generosidad nace de una generosidad mayor: Dios nos dio a su Hijo. Hay regalos que las palabras no alcanzan a explicar, y Cristo es el primero de ellos. Cuando damos a otros, reflejamos un poco de ese amor que primero recibimos.",
    closingPrayer: "Dios generoso, gracias por Jesús, tu don inefable. Haceme generoso con otros porque vos lo fuiste conmigo. Amén.",
  },
  {
    day: 14,
    openingPrayer: "Señor, quiero alabarte hoy con todo mi corazón, no a medias.",
    intro: "David abre este salmo decidiendo alabar a Dios de corazón completo. Promete contar todas sus maravillas y alegrarse en él.",
    verseRef: "Salmos 9:1",
    reflection: "Es posible agradecer de forma automática, con la boca pero con la mente en otro lado. David elige alabar con todo el corazón. Una buena manera de empezar es ser específico: nombrar una por una las maravillas que Dios ha hecho en tu vida.",
    closingPrayer: "Señor, perdoná mi gratitud distraída. Hoy te alabo con todo mi corazón por cada maravilla que has hecho. Amén.",
  },
  {
    day: 15,
    openingPrayer: "Señor Jesús, por medio de vos te ofrezco mi alabanza hoy.",
    intro: "La carta a los Hebreos explica que el sacrificio de Cristo fue suficiente y definitivo. Por eso los creyentes ya no ofrecen animales, sino un sacrificio de alabanza que sale de los labios.",
    verseRef: "Hebreos 13:15",
    reflection: "La alabanza a veces cuesta, y por eso se llama sacrificio. Hay días en que agradecer requiere decisión más que emoción. Pero no ofrecemos esa alabanza para ganar algo, sino como respuesta a lo que Cristo ya ganó por nosotros.",
    closingPrayer: "Padre, aun en los días difíciles quiero ofrecerte alabanza. Gracias porque por Jesús mi ofrenda es aceptada. Amén.",
  },
  {
    day: 16,
    openingPrayer: "Señor, tus beneficios son tantos que no sé cómo responder. Enseñame.",
    intro: "El autor del Salmo 116 había estado en angustia mortal y Dios lo libró. Ahora se pregunta qué podrá darle al Señor a cambio de tantos beneficios.",
    verseRef: "Salmos 116:12",
    reflection: "Nunca podremos pagarle a Dios lo que nos ha dado, y él no nos lo pide. En los versículos siguientes el salmista responde invocando su nombre y cumpliendo sus promesas delante del pueblo. La mejor respuesta a la gracia no es un pago, sino una vida entregada con gratitud.",
    closingPrayer: "Padre, no tengo con qué pagarte, pero te entrego mi vida con gratitud. Que mi obediencia sea mi respuesta a tu bondad. Amén.",
  },
  {
    day: 17,
    openingPrayer: "Señor Jesús, quiero estar arraigado en vos hoy.",
    intro: "Pablo anima a los colosenses a seguir viviendo en Cristo tal como lo recibieron. Usa imágenes de raíces y de edificio, y termina diciendo que esa vida firme abunda en acción de gracias.",
    verseRef: "Colosenses 2:6-7",
    reflection: "Un árbol con raíces profundas no cae con el primer viento. Pablo conecta la firmeza de la fe con la gratitud: quien está arraigado en Cristo tiene motivos para agradecer siempre. Cuanto más conocés lo que tenés en él, más crece tu gratitud.",
    closingPrayer: "Señor, afirmá mis raíces en vos. Que mi fe crezca firme y que mi vida rebose de gratitud. Amén.",
  },
  {
    day: 18,
    openingPrayer: "Dios fiel, quiero orar y darte gracias aun cuando las cosas se complican.",
    intro: "En Babilonia se publicó un decreto que prohibía orar a cualquier dios fuera del rey. Daniel lo supo, entró a su casa y, como lo hacía siempre, oró tres veces al día dando gracias a Dios.",
    verseRef: "Daniel 6:10",
    reflection: "Daniel no inventó una disciplina nueva ante la crisis; siguió con la que ya tenía. Y lo que hizo fue dar gracias, no solo pedir ayuda. Los hábitos de gratitud que formás en días tranquilos son los que te sostienen cuando llegan las pruebas.",
    closingPrayer: "Señor, ayudame a formar hábitos de oración y gratitud que permanezcan en la presión. Dame la firmeza serena de Daniel. Amén.",
  },
  {
    day: 19,
    openingPrayer: "Señor, que tu alabanza esté en mi boca todo este día.",
    intro: "Según el título del salmo, David lo escribió después de escapar de un rey filisteo fingiendo locura. Venía de un momento humillante y peligroso, y aun así decidió bendecir a Dios en todo tiempo.",
    verseRef: "Salmos 34:1",
    reflection: "David no escribió esto en un buen momento, sino al salir de uno de los peores. La alabanza en todo tiempo no depende de cómo te fue, sino de quién es Dios. Hoy, sin importar cómo amaneciste, podés reconocer que él sigue siendo digno.",
    closingPrayer: "Padre, en lo bueno y en lo difícil quiero bendecirte. Que mis palabras de hoy hablen bien de vos. Amén.",
  },
  {
    day: 20,
    openingPrayer: "Señor Jesús, gracias por la victoria que ganaste por mí.",
    intro: "Pablo termina su gran capítulo sobre la resurrección con una explosión de gratitud. Después de hablar de la muerte y del pecado, da gracias a Dios porque nos da la victoria por medio de Jesucristo.",
    verseRef: "1 Corintios 15:57",
    reflection: "La victoria de la que habla Pablo no es éxito en los negocios ni ausencia de problemas. Es la victoria de Cristo sobre el pecado y la muerte, que él comparte con quienes creen. Esa es una gratitud que ninguna pérdida de esta vida puede quitarte.",
    closingPrayer: "Padre, gracias porque la muerte no tiene la última palabra. Gracias por la victoria de Jesús, que también es mía por la fe. Amén.",
  },
  {
    day: 21,
    openingPrayer: "Señor, gracias porque tus misericordias son nuevas esta mañana.",
    intro: "Lamentaciones fue escrito entre las ruinas de Jerusalén después de su destrucción. En medio del llanto, el autor recuerda algo que le devuelve la esperanza: la fidelidad de Dios se renueva cada mañana.",
    verseRef: "Lamentaciones 3:22-23",
    reflection: "Este texto no nació en un día tranquilo, sino en medio de una tragedia. La gratitud no siempre llega después del problema; a veces aparece dentro de él. Si hoy estás cansado o dolido, Dios te ofrece misericordia nueva para este día, no para todo el año de una vez.",
    closingPrayer: "Dios fiel, gracias porque tu misericordia no se agota. Dame la porción de gracia que necesito para hoy. Amén.",
  },
  {
    day: 22,
    openingPrayer: "Señor, vengo a cantarte con alegría. Recibí mi gratitud.",
    intro: "El Salmo 95 es una invitación a la adoración. Llama al pueblo a cantar con júbilo a Dios, la roca de su salvación, y a presentarse ante él con acción de gracias.",
    verseRef: "Salmos 95:1-2",
    reflection: "El salmo llama a Dios roca de salvación: firme, segura, confiable. La alegría del canto nace de saber que estamos parados sobre algo que no se derrumba. Hoy podés cantar, aunque sea en voz baja, recordando que tu salvación está segura en él.",
    closingPrayer: "Señor, sos la roca de mi salvación. Llená mi boca de cantos de gratitud y mi corazón de alegría. Amén.",
  },
  {
    day: 23,
    openingPrayer: "Señor Jesús, gracias por el pan de cada día.",
    intro: "Una gran multitud siguió a Jesús hasta un lugar apartado. Un muchacho tenía cinco panes y dos peces; Jesús los tomó, dio gracias y los repartió hasta que todos comieron.",
    verseRef: "Juan 6:11",
    reflection: "Antes del milagro, Jesús dio gracias por lo poco que había. No esperó a tener suficiente para agradecer. Lo que hoy te parece poco, puesto en manos de Cristo con gratitud, puede servir para bendecir a otros más de lo que imaginás.",
    closingPrayer: "Señor, gracias por lo que tengo, aunque parezca poco. Lo pongo en tus manos para que lo uses como quieras. Amén.",
  },
  {
    day: 24,
    openingPrayer: "Padre, gracias por tu bondad que me ha acompañado todo este año.",
    intro: "El Salmo 65 celebra a Dios como creador y sustentador de la tierra. Habla de la lluvia, los campos y las cosechas, y dice que Dios corona el año con su bondad.",
    verseRef: "Salmos 65:11",
    reflection: "Faltando poco para terminar el año, es buen momento para mirar atrás. No todo fue fácil, pero seguramente hay huellas de la bondad de Dios en el camino. Tomá unos minutos para anotar tres maneras en que él te sostuvo este año.",
    closingPrayer: "Señor, gracias por coronar mi año con tu bondad. Ayudame a ver tus huellas en los días que ya pasaron. Amén.",
  },
  {
    day: 25,
    openingPrayer: "Señor, gracias por las personas que pusiste en mi camino.",
    intro: "Pablo abre su carta a los filipenses diciéndoles que da gracias a Dios cada vez que se acuerda de ellos. Esa iglesia lo había acompañado y apoyado desde el principio.",
    verseRef: "Filipenses 1:3",
    reflection: "Hay personas que son un regalo de Dios para tu vida: quienes te enseñaron la fe, te apoyaron o te acompañaron en un momento difícil. Pablo no solo agradecía en privado, también se los decía. Hoy podés mandarle un mensaje a alguien para contarle que das gracias por su vida.",
    closingPrayer: "Padre, gracias por cada persona que usaste para bendecirme. Ayudame a decirles lo agradecido que estoy. Amén.",
  },
  {
    day: 26,
    openingPrayer: "Señor, gracias por el alimento y por todo lo que me sostiene.",
    intro: "Moisés prepara al pueblo de Israel antes de entrar a la tierra prometida. Les advierte que, cuando coman y estén saciados, no olviden bendecir al Señor por la buena tierra que les dio.",
    verseRef: "Deuteronomio 8:10",
    reflection: "Moisés sabía que el peligro no estaba solo en el desierto, sino también en la abundancia. Cuando tenemos lo necesario, es fácil olvidar de dónde vino. Dar gracias antes o después de comer es una costumbre sencilla que mantiene el corazón humilde.",
    closingPrayer: "Señor, gracias por el pan de mi mesa. Que la abundancia o la escasez nunca me hagan olvidar que todo viene de vos. Amén.",
  },
  {
    day: 27,
    openingPrayer: "Buen Pastor, gracias porque cuidás de mí.",
    intro: "David, que fue pastor de ovejas en su juventud, describe a Dios como su pastor. Desde esa imagen afirma que, con Dios cuidándolo, no le faltará lo que de verdad necesita.",
    verseRef: "Salmos 23:1",
    reflection: "Este versículo no promete que tendrás todo lo que querés, sino que el Pastor sabe lo que su rebaño necesita. La gratitud nace de confiar en su cuidado más que en nuestros planes. Hoy podés descansar sabiendo que no caminás sin pastor.",
    closingPrayer: "Señor, gracias por ser mi pastor. Enseñame a confiar en tu cuidado y a seguirte de cerca. En el nombre de Jesús. Amén.",
  },
  {
    day: 28,
    openingPrayer: "Señor, aun cuando falte lo que esperaba, quiero alegrarme en vos.",
    intro: "Habacuc vio venir tiempos muy duros para su pueblo. Al final de su libro imagina la escasez total, sin cosecha ni ganado, y aun así declara que se alegrará en el Dios de su salvación.",
    verseRef: "Habacuc 3:17-18",
    reflection: "La gratitud más profunda no depende de lo que hay en el granero. Habacuc no fingió que todo estaba bien; describió la pérdida con honestidad. Pero encontró en Dios mismo una razón para alegrarse que ninguna crisis podía quitarle.",
    closingPrayer: "Dios de mi salvación, si me falta algo, que no me faltes vos. Dame una alegría que no dependa de mis circunstancias. Amén.",
  },
  {
    day: 29,
    openingPrayer: "Señor, todo viene de vos y todo es para vos. Recibí mi adoración.",
    intro: "Después de varios capítulos explicando el plan de Dios para judíos y gentiles, Pablo termina con una alabanza. Reconoce que todas las cosas proceden de Dios, existen por él y son para él.",
    verseRef: "Romanos 11:36",
    reflection: "Cuando Pablo llega al final de lo que puede explicar, no se frustra: adora. No entendemos todo lo que Dios hace, pero sabemos que todo empieza y termina en él. Esa confianza convierte las preguntas sin respuesta en una ocasión para la gratitud.",
    closingPrayer: "Padre, a vos sea la gloria por todo lo que sos y hacés. Aun lo que no entiendo lo pongo en tus manos. Amén.",
  },
  {
    day: 30,
    openingPrayer: "Señor, mientras tenga aliento quiero alabarte.",
    intro: "Terminamos el mes de la gratitud con el último versículo del libro de los Salmos. Después de ciento cincuenta cantos de alegría, lamento y súplica, el libro cierra con una invitación a todo ser que respira.",
    verseRef: "Salmos 150:6",
    reflection: "Si tenés aliento, tenés un motivo y una manera de alabar a Dios. Cada respiración es un regalo que solemos dar por sentado. Que la gratitud practicada este mes no termine hoy, sino que siga con vos en los días que vienen.",
    closingPrayer: "Señor, gracias por cada respiro de vida. Que la gratitud de este mes se quede en mi corazón para siempre. En el nombre de Jesús. Amén.",
  },
];
