import type { DevotionalEntry } from "./types";

// Diciembre — Adviento y Navidad; cierre del año (#199).
export const diciembre: readonly DevotionalEntry[] = [
  {
    day: 1,
    openingPrayer: "Señor, comienzo este Adviento esperando a Cristo con un corazón atento.",
    intro: "Comenzamos el Adviento, el tiempo en que la iglesia se prepara para celebrar la venida de Jesús. Siglos antes de su nacimiento, Isaías anunció a un niño que traería gobierno, consejo y paz.",
    verseRef: "Isaías 9:6",
    reflection: "Los nombres que Isaías da a este niño describen todo lo que Cristo es para su pueblo. Es consejero cuando no sabés qué hacer, Dios fuerte cuando te sentís débil y Príncipe de paz cuando hay conflicto. Este mes, dejá que cada uno de esos nombres te lleve a confiar más en él.",
    closingPrayer: "Padre, gracias por el niño que anunciaste por medio de los profetas. Preparame este mes para recibir a Jesús con gozo. Amén.",
  },
  {
    day: 2,
    openingPrayer: "Señor, prepará mi corazón como un camino para tu llegada.",
    intro: "Isaías habla de una voz que clama en el desierto para preparar el camino del Señor. Los evangelios ven en Juan el Bautista el cumplimiento de esta profecía, porque preparó al pueblo para recibir a Jesús.",
    verseRef: "Isaías 40:3",
    reflection: "Preparar el camino significaba quitar piedras y enderezar senderos. El Adviento es una invitación a revisar qué obstáculos hay en tu corazón: rencores, distracciones o cansancio. No para ganar la venida de Cristo, sino para recibirlo con espacio y atención.",
    closingPrayer: "Señor, quitá de mi corazón lo que estorba tu paso. Enderezá mis caminos para recibirte bien esta Navidad. Amén.",
  },
  {
    day: 3,
    openingPrayer: "Dios, gracias porque usás lo pequeño para hacer cosas grandes.",
    intro: "El profeta Miqueas anunció que de Belén, una aldea pequeña de Judá, saldría el gobernante de Israel. Siglos después, Jesús nació precisamente allí.",
    verseRef: "Miqueas 5:2",
    reflection: "Belén no era una ciudad importante, y sin embargo Dios la escogió. Él no mide como medimos nosotros. Si hoy te sentís pequeño o poco relevante, recordá que Dios suele obrar en lugares y personas que el mundo pasa por alto.",
    closingPrayer: "Padre, gracias porque no despreciás lo pequeño. Usá mi vida sencilla para tu gloria. En el nombre de Jesús. Amén.",
  },
  {
    day: 4,
    openingPrayer: "Señor, gracias porque cumplís tus promesas a tu tiempo.",
    intro: "Isaías habló al rey Acaz en un momento de miedo y amenaza. Dios le ofreció una señal: una virgen concebiría y daría a luz un hijo llamado Emanuel. Mateo ve su cumplimiento pleno en el nacimiento de Jesús.",
    verseRef: "Isaías 7:14",
    reflection: "La señal fue dada a un rey que no quería confiar en Dios. Aun así, Dios siguió adelante con su promesa. Su fidelidad no depende de nuestra fe perfecta, y en el nacimiento de Jesús esa promesa llegó más lejos de lo que nadie imaginaba.",
    closingPrayer: "Señor, cuando tenga miedo, recordame que estás cerca. Gracias porque tus promesas se cumplen aunque mi fe sea pequeña. Amén.",
  },
  {
    day: 5,
    openingPrayer: "Dios de gracia, gracias porque tu favor me alcanza sin merecerlo.",
    intro: "El ángel Gabriel visitó a María, una joven de Nazaret comprometida con José. Le dijo que no temiera, porque había hallado gracia delante de Dios, y le anunció que tendría un hijo llamado Jesús.",
    verseRef: "Lucas 1:30-31",
    reflection: "Lo primero que María escuchó fue que no tuviera miedo. El favor de Dios no la eximió de un camino difícil, pero le aseguró que no lo recorrería sola. Cuando Dios te llama a algo que te asusta, su gracia va delante de vos.",
    closingPrayer: "Padre, gracias por tu gracia que me sostiene. Quitá el temor que me paraliza y ayudame a confiar en tu plan. Amén.",
  },
  {
    day: 6,
    openingPrayer: "Señor, quiero decirte sí, aunque no entienda todo.",
    intro: "Después de escuchar el anuncio del ángel y hacer sus preguntas, María respondió con una entrega sencilla. Se reconoció sierva del Señor y aceptó que se cumpliera en ella su palabra.",
    verseRef: "Lucas 1:38",
    reflection: "María no tenía todas las respuestas, pero confió en quien le hablaba. Su disposición no fue ingenua; preguntó primero y después se rindió. Hacer preguntas a Dios no está mal, y la fe madura también sabe decir sí antes de ver el final.",
    closingPrayer: "Señor, aquí está mi vida, disponible para vos. Dame la confianza humilde de María para aceptar tu voluntad. Amén.",
  },
  {
    day: 7,
    openingPrayer: "Señor, cuando todo parece cortado, gracias porque podés hacer brotar vida nueva.",
    intro: "Isaías usa la imagen de un tronco cortado, el de Isaí, padre de David. De ese tronco que parecía muerto saldría un retoño sobre el cual reposaría el Espíritu del Señor con sabiduría y entendimiento.",
    verseRef: "Isaías 11:1-2",
    reflection: "La familia de David parecía terminada, como un árbol talado. Pero Dios no había olvidado su promesa, y de allí vino el Mesías. Si hay algo en tu vida que parece cortado, Dios todavía puede traer esperanza desde donde no la esperás.",
    closingPrayer: "Padre, gracias porque tus promesas no mueren. Hacé brotar esperanza en las áreas de mi vida que parecen secas. Amén.",
  },
  {
    day: 8,
    openingPrayer: "Señor, mi alma quiere engrandecerte hoy.",
    intro: "María visitó a su pariente Elisabet, que también esperaba un hijo. Al ser recibida con alegría, María entonó un cántico que la iglesia ha llamado el Magníficat, en el que alaba a Dios como su Salvador.",
    verseRef: "Lucas 1:46-47",
    reflection: "María no se puso a sí misma en el centro; engrandeció a Dios. Se alegró en él como su Salvador, reconociendo que ella también necesitaba ser salvada. La alabanza verdadera nos hace pequeños con gozo, porque pone a Dios en el lugar que le corresponde.",
    closingPrayer: "Señor, mi alma te engrandece y mi espíritu se alegra en vos. Gracias por ser mi Salvador. Amén.",
  },
  {
    day: 9,
    openingPrayer: "Padre, gracias porque enviaste a tu Hijo en el momento exacto.",
    intro: "Pablo explica a los gálatas que, cuando llegó el cumplimiento del tiempo, Dios envió a su Hijo, nacido de mujer y bajo la ley. Lo hizo para redimirnos y para que recibiéramos la adopción como hijos.",
    verseRef: "Gálatas 4:4-5",
    reflection: "Dios no llegó tarde ni temprano; envió a su Hijo en el tiempo preciso. Y el propósito no fue solo perdonarnos, sino adoptarnos en su familia. En Navidad no celebramos solo un nacimiento, sino que por ese niño podemos llamar Padre a Dios.",
    closingPrayer: "Padre, gracias por adoptarme como hijo por medio de Jesús. Ayudame a confiar en tus tiempos, que siempre son perfectos. Amén.",
  },
  {
    day: 10,
    openingPrayer: "Señor, gracias por el Rey justo que prometiste.",
    intro: "Jeremías denunció a los malos líderes de su tiempo, que dispersaron al pueblo como pastores descuidados. En contraste, anunció que Dios levantaría a David un renuevo justo, un rey que actuaría con sabiduría y justicia.",
    verseRef: "Jeremías 23:5",
    reflection: "En un mundo donde abundan los líderes que decepcionan, la promesa de un rey justo es una buena noticia. Jesús es ese Rey que gobierna con justicia y cuida a su rebaño. Tu esperanza no está en ningún gobierno humano, sino en el Rey que ya vino y volverá.",
    closingPrayer: "Señor Jesús, sos el Rey justo que necesita este mundo. Reiná en mi corazón y dame esperanza firme en tu reino. Amén.",
  },
  {
    day: 11,
    openingPrayer: "Dios de Israel, gracias porque visitaste a tu pueblo.",
    intro: "Zacarías, el padre de Juan el Bautista, había quedado mudo por no creer el anuncio del ángel. Cuando nació su hijo, recuperó el habla y lo primero que hizo fue bendecir a Dios por haber visitado y redimido a su pueblo.",
    verseRef: "Lucas 1:68",
    reflection: "Después de meses de silencio, las primeras palabras de Zacarías fueron de alabanza. A veces Dios usa los tiempos de espera para formar en nosotros una gratitud más profunda. Su visita en Cristo no fue un gesto lejano: vino a rescatar personalmente a los suyos.",
    closingPrayer: "Señor, que mis palabras de hoy sean de bendición para vos. Gracias por visitarme y redimirme en Jesús. Amén.",
  },
  {
    day: 12,
    openingPrayer: "Señor, cuando mis planes se desordenan, ayudame a escucharte.",
    intro: "José estaba comprometido con María y pensaba dejarla en secreto al saber que estaba embarazada. Un ángel le habló en sueños, le dijo que no temiera recibirla y le explicó que el niño se llamaría Jesús, porque salvaría a su pueblo de sus pecados.",
    verseRef: "Mateo 1:20-21",
    reflection: "José era un hombre justo que intentaba hacer lo correcto con la información que tenía. Dios le mostró un plan más grande, y él obedeció. El nombre de Jesús resume su misión: vino a salvar del pecado, que es nuestra necesidad más profunda.",
    closingPrayer: "Padre, dame la obediencia sencilla de José. Gracias porque Jesús vino a salvarme de mis pecados. Amén.",
  },
  {
    day: 13,
    openingPrayer: "Señor, que tu luz brille en mí y a través de mí.",
    intro: "Isaías escribe a un pueblo que había vivido en oscuridad y exilio. Lo llama a levantarse y resplandecer, porque la luz y la gloria del Señor han llegado sobre él.",
    verseRef: "Isaías 60:1",
    reflection: "La luz no es nuestra; es la gloria de Dios que nos alcanza. Por eso no se trata de fabricar brillo propio, sino de reflejar el suyo. En esta temporada de luces navideñas, pensá cómo tu vida puede mostrar la luz de Cristo a alguien cercano.",
    closingPrayer: "Señor, levantame de mi desánimo para reflejar tu luz. Que alguien vea hoy tu bondad en mí. Amén.",
  },
  {
    day: 14,
    openingPrayer: "Dios misericordioso, gracias por el amanecer de tu salvación.",
    intro: "Al final de su cántico, Zacarías describe la venida del Mesías como un amanecer que nos visita desde lo alto. Esa luz viene a quienes están en tinieblas y sombra de muerte, para guiarlos por camino de paz.",
    verseRef: "Lucas 1:78-79",
    reflection: "Zacarías dice que esta visita nace de la entrañable misericordia de Dios. Cristo no vino porque lo mereciéramos, sino porque Dios se compadeció. Si hoy caminás en sombras, su luz puede guiar tus pasos hacia la paz.",
    closingPrayer: "Padre, gracias por enviar a Jesús como luz a mi oscuridad. Guiá mis pies por el camino de la paz. Amén.",
  },
  {
    day: 15,
    openingPrayer: "Señor Jesús, sos la luz que la oscuridad no puede apagar.",
    intro: "Juan comienza su evangelio presentando a Jesús como el Verbo eterno y la luz de los hombres. Afirma que esa luz resplandece en las tinieblas y que las tinieblas no la han vencido.",
    verseRef: "Juan 1:5",
    reflection: "La oscuridad es real: hay dolor, injusticia y pecado. Pero Juan afirma que no tiene la última palabra. La luz de Cristo sigue brillando, y ninguna noche, por larga que sea, puede extinguirla.",
    closingPrayer: "Señor, cuando la oscuridad me rodee, recordame que tu luz no se apaga. Confío en vos. Amén.",
  },
  {
    day: 16,
    openingPrayer: "Señor, gracias por las buenas nuevas que llegaron a mi vida.",
    intro: "Isaías describe a un mensajero que cruza los montes con una noticia de paz y salvación para Jerusalén. Pablo cita este pasaje para hablar de quienes llevan el evangelio a otros.",
    verseRef: "Isaías 52:7",
    reflection: "Alguien caminó hasta vos para contarte de Cristo, y eso fue hermoso a los ojos de Dios. Ahora vos también podés llevar esa noticia. En Navidad muchas personas están más abiertas a escuchar; una invitación sencilla puede ser el comienzo.",
    closingPrayer: "Padre, gracias por quienes me anunciaron el evangelio. Usame para llevar buenas nuevas a alguien esta Navidad. Amén.",
  },
  {
    day: 17,
    openingPrayer: "Señor, que tu justicia amanezca en mi corazón.",
    intro: "Malaquías es el último libro del Antiguo Testamento. Su autor anuncia que, para quienes temen el nombre de Dios, se levantará un sol de justicia que trae restauración, y que ellos saltarán de alegría.",
    verseRef: "Malaquías 4:2",
    reflection: "Después de Malaquías vinieron siglos de silencio profético, hasta que llegó Jesús. La imagen del sol que se levanta habla de una espera que termina en luz y restauración. Cristo trae sanidad al alma: perdón, reconciliación y gozo renovado.",
    closingPrayer: "Señor Jesús, sos el sol de justicia que esperamos. Restaurá mi corazón y llenalo de tu alegría. Amén.",
  },
  {
    day: 18,
    openingPrayer: "Dios de esperanza, llená mi corazón de gozo y paz hoy.",
    intro: "Pablo cierra una sección de su carta a los romanos con una bendición. Pide que el Dios de la esperanza llene a los creyentes de gozo y paz en la fe, para que abunden en esperanza por el poder del Espíritu Santo.",
    verseRef: "Romanos 15:13",
    reflection: "La esperanza cristiana no es optimismo forzado. Es un regalo de Dios que crece mientras confiamos en él, y el Espíritu Santo es quien la sostiene. Si diciembre te trae nostalgia o cansancio, pedile a Dios que renueve tu esperanza.",
    closingPrayer: "Dios de esperanza, llename de gozo y paz mientras confío en vos. Que tu Espíritu haga crecer mi esperanza. Amén.",
  },
  {
    day: 19,
    openingPrayer: "Señor, gracias porque estás conmigo hoy.",
    intro: "Mateo cita la profecía de Isaías y explica el significado del nombre Emanuel: Dios con nosotros. Para Mateo, el nacimiento de Jesús es el cumplimiento de esa promesa.",
    verseRef: "Mateo 1:23",
    reflection: "El centro de la Navidad es que Dios no se quedó lejos. En Jesús se acercó a nuestra historia, nuestro dolor y nuestra vida diaria. No hay rincón de tu semana donde él no pueda estar presente.",
    closingPrayer: "Padre, gracias porque en Jesús estás con nosotros. Ayudame a recordar tu presencia en cada momento de este día. Amén.",
  },
  {
    day: 20,
    openingPrayer: "Señor Jesús, gracias por hacerte humilde por amor a mí.",
    intro: "Pablo invita a los filipenses a tener la misma actitud de Cristo. Describe cómo él, siendo igual a Dios, no se aferró a esa posición, sino que se despojó a sí mismo y tomó forma de siervo, haciéndose semejante a los hombres.",
    verseRef: "Filipenses 2:6-7",
    reflection: "El pesebre es la imagen más clara de esta humildad. El que tenía toda la gloria escogió nacer en pobreza y servir. Pablo no lo cuenta solo para admirarlo, sino para que aprendamos a vivir con la misma actitud hacia los demás.",
    closingPrayer: "Señor, gracias por tu humildad. Enseñame a servir a otros como vos me serviste. Amén.",
  },
  {
    day: 21,
    openingPrayer: "Dios de luz, gracias porque tu luz llegó a quienes andaban en oscuridad.",
    intro: "Isaías anuncia que el pueblo que andaba en tinieblas vería una gran luz. Mateo aplica este texto al comienzo del ministerio de Jesús en Galilea, una región despreciada por muchos.",
    verseRef: "Isaías 9:2",
    reflection: "La luz de Dios no llegó primero a los lugares importantes, sino a una región considerada de segunda categoría. Nadie está demasiado lejos ni demasiado oscuro para ser alcanzado. Si conocés a alguien que vive en tinieblas, orá por esa persona u ofrecele compañía estos días.",
    closingPrayer: "Señor, gracias porque tu luz alcanza a los olvidados. Hacé brillar a Cristo en mi hogar y en mi barrio. Amén.",
  },
  {
    day: 22,
    openingPrayer: "Señor Jesús, quiero hacerte espacio en mi vida.",
    intro: "Lucas cuenta que María dio a luz a su primer hijo en Belén. Lo envolvió en pañales y lo acostó en un pesebre, porque no había lugar para ellos en el mesón.",
    verseRef: "Lucas 2:7",
    reflection: "El Hijo de Dios entró al mundo sin un lugar preparado. En diciembre, nuestras agendas se llenan de compras, viajes y compromisos. Pensá hoy qué espacio real le estás dando a Jesús en medio de todo eso.",
    closingPrayer: "Señor, no quiero que mi vida esté tan llena que no haya lugar para vos. Hacé tu hogar en mi corazón. Amén.",
  },
  {
    day: 23,
    openingPrayer: "Señor, recibo con gozo las buenas nuevas de tu salvación.",
    intro: "Unos pastores cuidaban sus rebaños de noche cerca de Belén. Un ángel se les apareció y les anunció una noticia de gran gozo para todo el pueblo: había nacido el Salvador, que es Cristo el Señor.",
    verseRef: "Lucas 2:10-11",
    reflection: "Los primeros en oír la noticia no fueron los poderosos, sino pastores trabajando de noche. La buena noticia es para todo el pueblo, sin excepciones. Esta Navidad, no importa cuál sea tu historia, el Salvador también nació para vos.",
    closingPrayer: "Padre, gracias por enviar un Salvador para mí. Llená mi corazón de ese gran gozo que anunciaron los ángeles. Amén.",
  },
  {
    day: 24,
    openingPrayer: "Dios de gloria, esta Nochebuena me uno a los ángeles para alabarte.",
    intro: "Después del anuncio a los pastores, apareció una multitud de ángeles alabando a Dios. Proclamaron gloria a Dios en las alturas y paz en la tierra para las personas que reciben su favor.",
    verseRef: "Lucas 2:13-14",
    reflection: "La paz que anunciaron los ángeles no es solo ausencia de conflicto, sino reconciliación con Dios. Esa paz es un regalo de su gracia, no algo que conseguimos. Esta Nochebuena, en medio de la comida y la familia, tomá un momento para darle gloria a Dios.",
    closingPrayer: "Señor, gloria a vos por el nacimiento de Jesús. Que tu paz llene mi hogar esta noche. Amén.",
  },
  {
    day: 25,
    openingPrayer: "Padre, gracias por el regalo de tu Hijo. Feliz Navidad, Señor.",
    intro: "En el día de Navidad leemos el versículo que resume el evangelio. Jesús se lo explicó a Nicodemo, un maestro religioso que lo buscó de noche: el amor de Dios por el mundo lo llevó a dar a su Hijo.",
    verseRef: "Juan 3:16",
    reflection: "Detrás del pesebre está la cruz, y detrás de ambos, el amor de Dios. La Navidad no es solo la historia de un nacimiento, sino el comienzo de un rescate. Todo el que cree en Jesús recibe vida eterna; ese es el regalo que ningún otro puede igualar.",
    closingPrayer: "Padre, gracias por amar al mundo y amarme a mí. Gracias por Jesús, el mejor regalo de esta Navidad. Amén.",
  },
  {
    day: 26,
    openingPrayer: "Señor, en la calma después de la fiesta quiero meditar en vos.",
    intro: "Después de la visita de los pastores, todos se maravillaban de lo que contaban. Pero Lucas destaca que María guardaba todas estas cosas y las meditaba en su corazón.",
    verseRef: "Lucas 2:19",
    reflection: "Mientras otros se maravillaban y seguían su camino, María se detuvo a reflexionar. El día después de Navidad es buen momento para hacer lo mismo. ¿Qué te mostró Dios en estas fiestas que valga la pena guardar?",
    closingPrayer: "Señor, ayudame a guardar en mi corazón lo que me has mostrado. Que la Navidad no pase de largo en mi vida. Amén.",
  },
  {
    day: 27,
    openingPrayer: "Señor Jesús, como los magos, vengo a adorarte.",
    intro: "Unos magos del oriente siguieron una estrella hasta encontrar al niño Jesús. Al ver la estrella se alegraron mucho; al encontrarlo, lo adoraron y le ofrecieron oro, incienso y mirra.",
    verseRef: "Mateo 2:10-11",
    reflection: "Los magos recorrieron un largo camino para adorar al niño. Su gozo no estuvo en los regalos que recibieron, sino en encontrar a Jesús. Hoy podés preguntarte qué le estás ofreciendo: tu tiempo, tu confianza, tu servicio.",
    closingPrayer: "Señor, te ofrezco lo mejor que tengo. Que mi mayor gozo sea encontrarte y adorarte. Amén.",
  },
  {
    day: 28,
    openingPrayer: "Dios fiel, gracias porque mis ojos han visto tu salvación en Cristo.",
    intro: "Simeón era un hombre justo que esperaba la consolación de Israel. Cuando María y José llevaron a Jesús al templo, lo tomó en brazos y bendijo a Dios porque había visto la salvación prometida.",
    verseRef: "Lucas 2:29-30",
    reflection: "Simeón esperó años sin perder la fe, y su espera terminó en paz. Ver a Jesús le bastó para despedirse tranquilo. Cuando Cristo es tu salvación, podés enfrentar cualquier final y cualquier comienzo con serenidad.",
    closingPrayer: "Padre, gracias porque en Jesús veo tu salvación. Dame la paz y la paciencia de Simeón. Amén.",
  },
  {
    day: 29,
    openingPrayer: "Señor, quiero seguir creciendo en vos el próximo año.",
    intro: "Lucas resume en un solo versículo los años de infancia y juventud de Jesús en Nazaret. Dice que crecía en sabiduría, en estatura y en gracia para con Dios y los hombres.",
    verseRef: "Lucas 2:52",
    reflection: "Aun Jesús vivió un proceso de crecimiento en la vida ordinaria. El crecimiento espiritual no se da de golpe; ocurre día tras día, en lo sencillo. Al acercarse un nuevo año, pensá en un área donde querés crecer con la ayuda de Dios.",
    closingPrayer: "Señor, ayudame a crecer en sabiduría y en gracia. Que el próximo año me acerque más a vos. Amén.",
  },
  {
    day: 30,
    openingPrayer: "Dios eterno, al terminar el año pongo mis días delante de vos.",
    intro: "El Salmo 90 se atribuye a Moisés y reflexiona sobre la eternidad de Dios y la brevedad de la vida humana. En medio de esa reflexión, pide a Dios que nos enseñe a contar nuestros días.",
    verseRef: "Salmos 90:12",
    reflection: "Contar los días no es vivir con angustia por el tiempo, sino con sabiduría. Al mirar el año que termina, podés agradecer lo vivido y entregarle a Dios lo que dolió. Pedile un corazón sabio para usar bien los días que vienen.",
    closingPrayer: "Señor, enseñame a contar mis días. Gracias por este año y dame un corazón sabio para el que viene. Amén.",
  },
  {
    day: 31,
    openingPrayer: "Señor, gracias por guardarme todo este año. Pongo el nuevo en tus manos.",
    intro: "El Salmo 121 era cantado por los peregrinos que subían a Jerusalén. Termina afirmando que el Señor guardará a su pueblo, cuidando su salida y su entrada desde ahora y para siempre.",
    verseRef: "Salmos 121:7-8",
    reflection: "El año termina y otro comienza, como quien sale de un lugar y entra a otro. El salmo no promete un camino sin problemas, pero sí un Dios que acompaña cada paso. Entrá al nuevo año confiando en que él sigue siendo tu guardador.",
    closingPrayer: "Padre, gracias por tu cuidado en cada día de este año. Guardá mi salida y mi entrada en el año que comienza. En el nombre de Jesús. Amén.",
  },
];
